- WolvenKit.Bundles/BundleManager.cs
- WolvenKit.CR2W/WolvenKit.CR2W.csproj
- WolvenKit/Forms/frmMain.cs
Implemented:
Refreshing mod assets browser when adding file from mod.
Fixed:
- Removed CFont.cs from project.
- When user adds file from mod the asset list is refreshed on opening asset browser form.
> Refreshing mod assets where adding file from mod.

- WolvenKit.CR2W/CR2W/CR2WFile.cs
- WolvenKit/Forms/frmModExplorer.cs
Implemented:
- Bautified original xml dump
Fixed:
- context XML Dump menu is disabled when file is either: xml, csv, ws or is directory.
Context menu enable/disable requires fixing for other options as well.
> Basic XML Dump beutified and context menu fixed

- CR2WTests/StressTest.cs
- WolvenKit.Bundles/BundleItem.cs
- WolvenKit.CR2W/CR2W/CR2WBuffer.cs
- WolvenKit.CR2W/CR2W/CR2WFile.cs
- WolvenKit.Common/Wcc/enums.cs
- WolvenKit/Forms/frmAbout.cs
- WolvenKit/Forms/frmImportUtility.Designer.cs
- WolvenKit/Forms/frmImportUtility.cs
- WolvenKit/Forms/frmMain.cs
- WolvenKit/MainController.cs
- WolvenKit/Properties/AssemblyInfo.cs
- updated the assmembly version
Implemented:
- readded areosnap at the cost of a white menu strip
- import utility themeing
Fixed:
- fixed two inconsistencies in raw file importing
- fixed a bug where saving uncooked files would not write buffer data
- fixed a bug whith the import utility crashing on theme change
- fixed an issue that prevented the game from launching while Wkit is running
> Release 0.5 Hotfixes

- WolvenKit/Forms/frmMenuCreator.cs
Fixed:
- Menu Creator: I was unable to load any XML menus provided by mods, due to exception: "There is no Unicode byte-mark."  These modded menus specified their encoding as "utf-16", when the files were actually "utf-8".  I imagine this is because the authors copied the encoding line from CDPR, but didn't actually save the files as UTF-16.  
I have worked around this issue by loading the XML file into a string, then passing that to XDocument.Parse, which I assume bypasses the encoding checking.
> Menu creator fix: load XML file into string prior to parsing, which avoids exception when file is wrongly labelled as "utf-16".

- WolvenKit/Forms/frmCR2WtoText.cs
Fixed:
- Avoid exceptions when mod project is open while Dump CR2W Text is running by creating a new dummy LoggerService rather than re-using the one on MainController.
> Bugfix: avoid exceptions when mod project is opened

- WolvenKit/Forms/frmCR2WtoText.Designer.cs
- WolvenKit/Forms/frmCR2WtoText.cs
Implemented:
- New option to enable dumping localized strings instead of just their IDs; defaults to checked.
> Dump CR2W To Text Localized Strings

- WolvenKit.App/ViewModels/ImportViewModel.cs
- WolvenKit.CR2W/Types/Utils/CR2WTypeManager.cs
- WolvenKit.CR2W/Types/Utils/Enums.cs
- WolvenKit/Forms/frmMain.cs
- WolvenKit/Forms/frmModExplorer.cs
- WolvenKit/Forms/frmScriptEditor.cs
Implemented:
- added ELightChannel enum
- F5 : pack and install mod
- Ctrl+F5: pack and install mod, launch game
Fixed:
- fixed relative path copying in ModExplorer
- fixed a bug where files in frmScriptEditor would be saved in utf8 instead of utf16LE
- fixed a bug where dlc textures would get imported as bundle in the **importUtility**
- fixed launching the game when packing is cancelled
> Release 0.6.2 bugfixes

- README.md
- Update.xml
Fixed:
- fixed invalid old discord invite link in the readme
closes #187
> Fixes 0.6.1 - Update README.md

- WolvenKit.App/ViewModels/MainViewModel.cs
- WolvenKit.Common/Model/W3Mod.cs
- WolvenKit/Forms/MVVM/frmMain.cs
- WolvenKit/Forms/MVVM/frmModExplorer.Designer.cs
- WolvenKit/Forms/MVVM/frmModExplorer.cs
- WolvenKit/Forms/UserControl/frmPackSettings.Designer.cs
- WolvenKit/Forms/UserControl/frmPackSettings.cs
- WolvenKit/Properties/Resources.Designer.cs
Implemented:
- trim 2 first folders when adding a file from a dlc *as* a dlc-file
- added support for older mod projects with a different dlc structure
Fixed:
- fixed a bug where virtual links were not linked correctly
- fixed a bug where the pack settings were not displayed correctly
#246
> mod workflow fixes

- WolvenKit.Irrlicht/source/COBJMeshWriter.cpp
- WolvenKit.Irrlicht/source/CSceneManagerWolvenKit.cpp
- WolvenKit.Irrlicht/source/CTerrainSceneNodeWolvenKit.cpp
- WolvenKit.Irrlicht/source/CW3EntLoader.cpp
- WolvenKit.Render/frmLevelScene.cs
Fixed coordinate system transformation issue.  Witcher is RHCS and Irrlicht is LHCS.  Hack that was in before had some issues so investigated a better fix - this is it.
Implemented:
- none
Fixed:
- mesh and terrain are loaded as is.  Transformation is applied to a root node in the scene graph.
> fix for RHCS to LHCS

- WolvenKit.App/ViewModels/Documents/CR2WDocumentViewModel.cs
- WolvenKit.App/ViewModels/Documents/ScriptDocumentViewModel.cs
- WolvenKit.CR2W/CR2WManager.cs
- WolvenKit.CR2W/CR2WTypeManager.cs
- WolvenKit.CR2W/Types/Primitive/Enums.cs
- WolvenKit/Forms/MVVM/frmMain.Designer.cs
- WolvenKit/Forms/MVVM/frmMain.cs
- WolvenKit/Forms/frmChunkProperties.cs
- WolvenKit/Forms/frmScriptEditor.cs
Implemented:
- add copy-paste for derived types
- add compilation of custom enums
- added a document layout resest option in case sthg goes wrong
Fixed:
- fixed a bug where copying localized strings would crash
- fixed a bug where the script editor would not change title when saving
> custom enums and chunk copy

- .github/workflows/Nightly.yml
- .github/workflows/main.yml
Fixed:
- fixed workfow file after deprecation of add-path command (https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/): migrated to https://github.com/marketplace/actions/setup-nuget-exe-for-use-with-actions
> Fix Github Actions - Setup Nuget and ms build

- WolvenKit.Render/frmRender.Designer.cs
- WolvenKit.Render/frmRender.cs
- WolvenKit.Render/frmRenderEventHandler.cs
frmRender levels of detail for exporting
Fixed:
- loading all lod meshbuffers
Loading all mesh buffers using the scenegraph mesh loading rather than WKMesh since WKMesh only loads the first lod.  We need to clean up frmRender and fastRender as they both do similar things but in different ways which makes maintenance difficult.
> frmRender lods

- WolvenKit.Modkit/Modkit/Helper/Common/MaterialSetup.cs
- WolvenKit.Modkit/Modkit/Helper/Common/MaterialTypes.cs
- WolvenKit.Modkit/Modkit/Helper/Common/Structs.cs
- WolvenKit.Modkit/Modkit/Helper/Functions/MaterialFunctions.cs
- WolvenKit.Modkit/Modkit/Helper/Functions/MeshFunctions.cs
Implemented:
Material Setup and Template Dump with Material.json, External MaterialEntries parsing aswell, Separate Methods for usingAssetLib and using Archive List.
Fixed:
- <Fixes>
Some Exception Handling, changed method for getting material buffer(to UTF8 error in some cases)
using DirectoryInfo and FileInfo instead of strings. one time MATERIAL object initialization with Archives list, so as not to read Archives from GameDir every time mesh is exported, i.e. efficient, fast for multiple exports
> mlsetup, mltemplate dump support and fixes/improvements

- WolvenKit.Modkit/Modkit/Helper/Functions/MaterialFunctions.cs
Implemented:
Fixed:
- <Fixes>
.mlmasks should be uncooked rather just exported but in some instances the uncook for them breaks due to wrong identification of atlasBuffer[0] and tilesBuffer[1]
> Simple Material Repository Generator

- WolvenKit.Common/Model/AssetBrowserData.cs
- WolvenKit/Views/Editor/Basic/AssetBrowserView.xaml.cs
Fixed:
- <Fixes>
sort file names in asset browser alphanumerically and adding suffixes to the file sizes
> AB file sort alphabetically, size suffixes

- WolvenKit.Modkit/RED4/Uncook.cs
Fixed:
- <Fixes>
mesh dependency files haven been moved in archives in patch 1.3 so re collecting certain archives causes missing dependencies, removed re collection
> no archive list re collection for mesh exports

- WolvenKit.Modkit/RED4/Tools/MlmaskImportTools.cs
Fixed:
- <Fixes>
mask images in mlmask imports being horizontally off from the original images has been fixed
> mlmask images offset fix

- WolvenKit.RED4.CR2W/Types/Generic/Arrays/CArrayBase.cs
Fixed:
- Fixed: CArrayBase caused an exception when writing certain data types (UInt8) if internal buffer is null.
> Fixed exception on writing null buffers in CArrayBase

- WolvenKit.CLI/Commands/TweakCommand.cs
- WolvenKit.CLI/Program.cs
- WolvenKit.Modkit/RED4/Tasks/TweakTask.cs
Checks for in & out paths, and assigns the current directory if one isn't assigned. Also adds an option to not delete the output directory, if supplied.
> Adds a .tweak->TweakDB .bin conversion command to the CLI

- WolvenKit.Modkit/RED4/Serialization/Serialization.cs
- WolvenKit.Modkit/RED4/Serialization/yaml/IParserExtensions.cs
- WolvenKit.Modkit/RED4/Serialization/yaml/TweakTypeConverter.cs
- WolvenKit.RED4.TweakDB/Enums.cs
- WolvenKit.RED4.TweakDB/FlatsPool.cs
- WolvenKit.RED4.TweakDB/TweakDB.cs
- WolvenKit.RED4.TweakDB/Types/CResource.cs
- WolvenKit.RED4.TweakDB/Types/LocKey.cs
- WolvenKit.RED4.TweakDB/Types/TweakDBID.cs
Adds TweakDB compilation for TweakDBIDs, raRef:CResources, and LocKeys, fixes some issues with arrays. Supports the `-` array YAML format now as well.
TweakDBIDs can be the full paths, or IDs in the format `TDBID:12345678:12` (with some variations), where the numbers are hexadecimals.
> TweakDB Compilation Improvements for CLI

- WolvenKit.Common/Extensions/MemoryMappedFileExtensions.cs
- WolvenKit.Common/RED4/Red4ParserServiceExtensions.cs
- WolvenKit.Modkit/RED4/Unbundle.cs
On initial read of an archive file, a memory mapped file (MMF) is checked for existence. If it does not exist, the IOException that's thrown is caught and a MMF is created.  Names are added to MMFs on creation to enable sharing of the mapped files across multiple processes, allowing multiple WolvenKit.CLI processes to simultaneously access the same archive file.  Once MMF handling is completed, the MMF is explicitly disposed.
Changes allow for  multiple simultaneous unbundling instances on the same archive file, and also allows multiple simultaneous uncooking instances on the same archive file (with each instance writing to its own output location).
> Allow simultaneous reads from a single archive file by multiple WolvenKit.CLI processes

- WolvenKit/WolvenKit.csproj
Adds the WolvenKit CLI to the main project, and therefore the installer, so folks installing the app from the .exe will have the CLI available to them once installed.
Github workflow for release was tested here, where you can download the installer to test it out: https://github.com/jackhumbert/WolvenKit/releases/tag/untagged-b429e677e83651d8c4bc
> Adds the CLI to the installer

- WolvenKit.RED4.TweakDB/Types/CResource.cs
Only parses decimal since that's the only format I've ever seen CResources in - please correct me if I'm mistaken!
> Adds UInt64 parsing for raRef:CResource in TweakDB compilation

- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
Affects the right-click "Copy relative path" option in the Project Explorer,
> Get the full relative path instead of filename for CopyRelPath

- WolvenKit.App/Functionality/Controllers/RED4Controller.cs
* Only delete .archive files in `cp77Proj.PackedModDirectory` (`archive/pc/mod`) instead of the whole directory, allowing other files to be placed here & packed
* Removes `mod` prefix from .archive filenames*
* Preserve folder names from `cp77Proj.TweakDirectory` when compiling to `cp77Proj.PackedTweakDirectory`
\* This will cause duplicate .archive files if you're zipping up the packed folder & dropping it in - do we have a way to notify people of a change like this?
> Tweaks to the pack/build process

- .github/workflows/Nightly.yml
- .github/workflows/draft_release.yml
- .github/workflows/main.yml
- WolvenKit.CLI/WolvenKit.CLI.csproj
- WolvenKit/WolvenKit.csproj
Fixes the mistake I made in #627 (which was to add self contained as flag in the publish command) by making **only** the WolvenKit.CLI project self contained. Tested to be functional with WINE on Linux as well, as opposed to the current situation which has a couple missing libraries in the release.
> Make CLI self contained

- .github/workflows/Nightly.yml
- .github/workflows/draft_release.yml
- .github/workflows/main.yml
This prevents libraries needed for WINE to function properly from being excluded in the build/
Redid the PR because I accidentally used the master branch for the other one.
> Remove "SelfContained=False" from publish workflows

- WolvenKit/Views/Wizards/ProjectWizardView.xaml.cs
Added a timer that checks whether the folder path is valid every 1s. This is necessary since the project wizard will otherwise not notice when a folder path has been made valid since it last time was checked. 
Example:
appending a (non-existing) sub-folder in the text-field will cause the wizard to correctly note that the folder doesn't exist and mark the path as invalid. When opening the browser through the button and adding that folder, in the browse UI, the path won't change, thus no check will be made, even though the folder now exists and the path should be valid. 
I have no experience with C# so I'd appreciate any feedback on the changes.
> Add Timer to Check Folder Path Validity in ProjectWizard

- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
- WolvenKit/Views/Tools/AssetBrowserView.xaml
Implemented:
- Toggle button to switch between the game base archives and installed mod archives. This was previously only available in the ribbon.
Fixed:
- The 'home' button in the Asset Browser was a little confusing, changed it to a FoldUp icon and a 'back to top level' tooltip
Didn't remove the existing toggle from the ribbon view yet.
> Add Base/Mod Files Toggle to Asset Browser

- WolvenKit.RED4.Archive/Buffer/Package04Structs.cs
- WolvenKit.RED4.Archive/IO/PackageReader.File.cs
- WolvenKit.RED4.Archive/IO/PackageWriter.File.cs
- WolvenKit.RED4.Archive/IO/PackageWriter.cs
- WolvenKit.RED4.Types/EnumsExt/InternalEnums.cs
It looks the bit in the import header is whether that reference is a `CResourceReference` (`1`) or `CResourceAsyncReference` (`0`). Moves the flag to the second bit (1), but allows for anything besides the first (`> 0`) to set the Sync flag, not that it matters, since the Package flags aren't used anywhere else to my knowledge.
Closes #643
> Hooks up Import Sync Flag to IResource(Async)References

- WolvenKit.Core/Compression/KrakenNative.cs
- WolvenKit.Core/Compression/OozNative.cs
- WolvenKit.Core/WolvenKit.Core.csproj
The whole lib subdirectoy was a problematic so I think it's better to reference them by name in the main directory as it's not platform-specific.
Also fixes the issue where it tries to load a Linux lib on Windows.
> Add libs to main directory and reference them by name and not path

- WolvenKit.Modkit/RED4/Tools/MaterialTools.cs
Currently, when exporting a mesh with materials into an empty depot, materials referenced in an mltemplate file are not exported along with the json. This leads to unreferenced textures, for example, when importing an mltemplate texture into Blender.
This pull request finds all CBitmapTextures (or rather their CResourceReferences) and exports the associated file if not previously done so.
> Export textures referenced in .mltemplate files

- WolvenKit.App/Services/ISettingsManager.cs
- WolvenKit.App/Services/SettingsManager.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit/Views/Shell/RibbonView.xaml
- WolvenKit/Views/Shell/RibbonView.xaml.cs
Implemented:
- Launch Game button in the main toolbar (Closes #702)
Notes:
- Just launches the game. Could have it pack & install automatically, but I suspect quite often folks will want to do or simply do that separately. So it's two clicks rather than possibly rebuilding the mod when you don't want to.
- No implementation for the Ribbon (which is to be retired)
> Add Launch Game button to main toolbar

- WolvenKit.App/ViewModels/Documents/RDTDataViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.RED4.Archive/Buffer/CR2WList.cs
- WolvenKit.RED4.Archive/Buffer/Package04.cs
- WolvenKit.RED4.Types/Primitives/CHandle.cs
- WolvenKit.RED4.Types/Primitives/Simples/DataBuffer.cs
- WolvenKit.RED4.Types/Primitives/Simples/SerializationDeferredDataBuffer.cs
- WolvenKit.RED4.Types/Primitives/Simples/SharedDataBuffer.cs
- WolvenKit/Views/Editors/RedTypeView.xaml
- WolvenKit/Views/Tools/RedTreeView.xaml
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
Implemented:
* Copy & paste an array item within the same tab (is copy & pasting from different files/tabs desirable?)
* Duplicate array item (handles & value types work too)
* Dragging items rearranges them, holding control duplicates them with confirmation (previously was too easy to accidentally duplicate)
Fixed:
* Array index for identical primitives
* Array index width in the treeview & editor
Fixes #642, fixes #644 (possibly fixed earlier), and fixes #676
> Array item copy, paste & duplication, array index clean-up

- WolvenKit.Modkit/RED4/Tools/MaterialTools.cs
First part of enabling gradient texture imports in Blender. These are used in the gradient eye textures, for example.
See here for the plug-in pull request (PR#14): https://github.com/HitmanHimself/cp77research/pull/14
> export .gradient files to .gradient.json

- WolvenKit.App/ViewModels/Documents/RDTDataViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
* Cleans-up the tooltip for dragging, shows the current action (duplicate or move), and note about using control to switch
* Allows copy & pasting and dragging between two open files (move & duplicate)
* Paste/duplicate after the selected item's index (pasting into array row itself puts it at the end)
* Allows items to be dragged above an item, instead of just below
> TreeView Drag & Drop, Copy & Paste Enhancements

- WolvenKit.App/Services/ISettingsManager.cs
- WolvenKit.App/Services/SettingsManager.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.App/ViewModels/Wizards/FirstSetupWizardViewModel.cs
- WolvenKit/Views/HomePage/Pages/SettingsPageView.xaml.cs
New stuffs:
- SettingsDto is versioned; the idea is to keep the Dto always on the current version but maintain a set of migrations that are always run on load/save. When eventually there's a v3 settings, then for any v2 settings we should run MigrateV2ToV3 (which does whatever fixes) and for any undefined/v1 settings it's MigrateV1ToV2, then MigrateV2ToV3.
- v2 settings include LaunchCommand and LaunchOptions to support the thing I was ACTUALLY doing, which is enabling using alternative launch stuffs for the Launch Button (as req'd in #735 and was part of #718)
Fixed stuffs:
- TweakDB loading could crash on startup on first run because settings might not exist at that point yet
Pictures:
- Initial setup ![image](https://user-images.githubusercontent.com/13802421/159192117-77c2460e-9732-4e6 …
> LaunchCommand/LaunchOptions In Settings, Used By Launch Button (Plus Versioned Settings Support..)

- WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
If a mesh starts with a number, WolvenKit will crash when previewed. XAML names have restrictions "[m]ost notably, a Name must start with a letter or the underscore character (_), and must contain only letters, digits, or underscores"
Source: https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.name?view=windowsdesktop-6.0
Example of mesh that crashes: "base\entities\cameras\3dmap\3dmap_roads.mesh"
Fixed:
- prepend an underscore character (_) to the name of a mesh that begins with a number (occurs in preview only)
> RDTMeshViewModel: fix for meshes that start with a number

- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
Clipboard crash #744 fix
Implemented:
Clipboard SetText fails whereas SetDataObject does not
Fixed:
Changed Clipboard.SetText to Clipboard.SetDataObject
See https://stackoverflow.com/questions/44538513/clipboard-settext-fails-whereas-setdataobject-does-not#:~:text=From%20MSDN-,Clipboard.,adds%20text%20data%20to%20it.
> Clipboard error fix - Clipboard crash #744

- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit/Views/Shell/RibbonView.xaml
- WolvenKit/Views/Shell/RibbonView.xaml.cs
Adds a function and a button to the shell next to the existing "Launch Game" button that runs the default steam id for Cyberpunk 2077. Not fully added to the ribbon view however as i don't know how to do that. Seemingly "RibbonView.g.i.cs" would have to be generated again.
I hardly know what I'm doing so please be careful with this (and someone would have to add it to the ribbon view properly)
> Added function/button to launch CP77 via Steam

- WolvenKit.Modkit/Managers/ArchiveManager.cs
Quick guard so it won't crash on activating the mod browser. Underlying error is still unresolved.
> Hotfix For Mod Browser Read Error Crash

- WolvenKit.Modkit/RED4/Uncook.cs
Fixes the path separators for Linux when performing an uncook operation with WolvenKit.CLI. Without the change, single files are created with the literal name of the relative path in the archives, rather than creating a directory structure.
Confirmed to still work on Windows as well.
> Fix file path separator for Linux during uncook

- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
> 🐛 Use SaveAs Dialog When Saving Editor With Nonexistent Dir Path

- .gitignore
- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
- WolvenKit.App/WolvenKit.App.csproj
- WolvenKit/Views/Tools/AssetBrowserView.xaml
- WolvenKit/Views/Tools/AssetBrowserView.xaml.cs
Generally:
- Search syntax unified a bit, improved (?) syntax and filtering (see below)
- Search game files or mods based on mod toggle in Asset Browser
- Removed secondary search bar, there's just one
- Basic error handling + regexp timeouts
Search syntax:
- Search is a sequential filter split on ` > `, i.e. you can do `judy > quest` to _first_ match `judy` and then in those results `quest`. (Alternative would be `quest judy` because quest is first in the path, but it might be more ergonomic to just tack on further refinements rather than modify the earlier.)
- Spaces to split 'terms', anything allowed to match between terms. I.e. `quest judy` => `quest.*?judy`.
- Partial match anything anywhere. Term `ma` will match a whole lot, e.g. `../market/.../..`, `../machete.xbm` and whatever.
- …
> Search Enhancements

- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
Hash search requires `hash:` prefix like `hash:123455633`. Otherwise numbers are handled like any other substring.
Closes #804
> 🐛 Asset Search Requires Type Prefix For Hash Search

- WolvenKit.App/ViewModels/Tools/ImportExportViewModel.cs
- WolvenKit.Core/FNV1A/FNV1A64HashAlgorithm.cs
- WolvenKit.RED4.Archive/Buffer/RedPackageStructs.cs
- WolvenKit.RED4.Archive/IO/CR2WWriter.File.cs
- WolvenKit.RED4.Archive/IO/RedPackageWriter.cs
- WolvenKit.RED4.Types/IO/Red4Writer.cs
- WolvenKit.RED4.Types/Primitives/Simples/CName.cs
- WolvenKit.RED4.Types/Primitives/Simples/NodeRef.cs
- WolvenKit.RED4.Types/Reflection/RedReflection.cs
Fixed:
- Hashing for CName and NodeRefs (again...)
- Duplicated fileName writing in CR2W
- Wrongly shifted size field in RedPackageNameHeader
- Enum writing for enums where value is "None"
- A bug introduced while merging #799 
- Moved buffer generation, so the newly generated bytes are written
- Removed showing success message on import/export when the action failed
- Prevent empty soundbank creation while processing all imports/exports
- Filter out "old" files from rig selection
> Random fixes

- WolvenKit.Modkit/RED4/Uncook.cs
This PR is fixing an issue with the Wolvenkit CLI.
When doing a batch export of meshes with materials, any meshes which references the same material than another mesh has a high chance of failing to be correctly extracted.
Here is the stacktrace that this PR is fixing:
```
[ 0: Error       ] - base\environment\decoration\unique\quest\q114\q114_blockade_a_dst\q114_blockade_a_dst_dynamic.mesh - The process cannot access the file 'G:\MaterialDepot\base\surfaces\materials\concrete\concrete_new\concrete_new_clean_01_300.mltemplate' because it is being used by another process.
[ 0: Error       ] - ========================
System.IO.IOException: The process cannot access the file 'G:\MaterialDepot\base\surfaces\materials\concrete\concrete_new\concrete_new_clean_01_300.mltemplate' because it is …
```
> WolvenKIT.CLI: Fix System.IO.IOException when batch export meshes with materials

- WolvenKit.Modkit/RED4/Tasks/UnbundleTask.cs
- WolvenKit.Modkit/RED4/Tasks/UncookTask.cs
The unbundle command would add a directory as prefix to the output path containing the name of the archive the file would come out from.
The uncook command doesn't have this behavior, which makes sense because it would make it complicated when files have depenendencies accross multiple archives.
I mentioned this issue a few days ago on Discord, and decided to take a look at it.
It seems to be the only place where the archive name is prefixed before exporting assets. So I also removed the other case where the archive name is added to the root folder when no output folder is specified.
> WolvenKit CLI: Remove the unconsistant archive name prefix on unbundle and uncook commands

- WolvenKit.Modkit/RED4/Tools/MaterialTools.cs
Support material exports for meshes which in their ExternalMaterial array reference, directly link Material Templates instead of Material Instances.
The investigation for the bug is in the issue ticket.
I also investigated if the externalMaterials type could be changed as a list of IMaterial, but there's code later on working on properties specific to material instances, and we would loose the data for the material overrides. Instead, the easier solution implemented here transforms the material template into a "dummy material instance".
We might need the same fix for preloaded external materials. If I realize that it's needed there too, I'll make a follow-up PR.
Fixes:
- #812
> Fix issue #812: Material exports which reference material templates from external materials

- WolvenKit.Modkit/RED4/Tools/AnimationTools.cs
- WolvenKit.Modkit/RED4/Tools/MaterialTools.cs
- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
- WolvenKit.Modkit/RED4/Tools/MorphTargetTools.cs
The default mesh export GLTF settings for Materials, Morphtargets or Animations do not try to fix invalid values while exporting, leading to an internal error.
I went through all the method calls for saving the GLTF models and copied the behavior from the default export mode.
Here a link to the code where it's already implemented as such: https://github.com/WolvenKit/WolvenKit/blob/develop/WolvenKit.Modkit/RED4/Tools/MeshTools.cs#L97
--- 
`base\environment\architecture\common\int\int_nkt_jp_corridor_a\_dst\int_nkt_jp_corridor_a_zengarden_a_dst_a_dynamic.mesh`
```
[06/06/2022 22:11:53] base\environment\architecture\common\int\int_nkt_jp_corridor_a\_dst\int_nkt_jp_corridor_a_zengarden_a_dst_a_dynamic.mesh - .NET number values such as positive and negative infinity cannot be written as valid …
```
> Fix mesh export json serialization exception

- WolvenKit.Modkit/RED4/Tools/MaterialTools.cs
Some meshes have local materials which reference MaterialTemplates, which themselves only exists within their own cr2w part of the embeddedFiles. This currently breaks the mesh exports with Material for these meshes. This PR aims to fix this.
`base\gameplay\community\crowd.mesh`
```
========================
4%[ 0: Error       ] - base\gameplay\community\crowd.mesh - base\materials\long_distant_crowds.mt
[ 0: Error       ] - ========================
System.IO.FileNotFoundException: base\materials\long_distant_crowds.mt
at WolvenKit.Modkit.RED4.ModTools.LoadFile(String path, List`1 archives) in E:\WolvenKit\WolvenKit.Modkit\RED4\Tools\MaterialTools.cs:line 1080
at WolvenKit.Modkit.RED4.ModTools.GetMaterialChain(CMaterialInstance cMaterialInstance, List`1 archives, Dictionary`2& mts) in …
```
> Fix embedded material template in mesh materials exports

- WolvenKit.CLI/Commands/UncookCommand.cs
- WolvenKit.Common/Interfaces/IModTools.cs
- WolvenKit.Modkit/RED4/Tasks/ConsoleFunctions.cs
- WolvenKit.Modkit/RED4/Tasks/UncookTask.cs
- WolvenKit.Modkit/RED4/Uncook.cs
There's no direct way to export to json from the CLI. The current flow would be unbundle the file, then use the cr2w command to transform the exported file to json. This is rather cumbersome when doing batch exports. This PR adds a way to directly extract to JSON from the CLI.
- This PR adds a new exposed CLI flag to the `uncook` command: `-s` or `--serialize`
- Using this flag adds a new step in the uncook process which exports the file to json with the `.json` file extension appended to the end of its path.
- To prevent errors with unsupported files to be uncooked, when the serialize option is used, it does not try to uncook the buffers.
For now this argument only serializes the main chunk, but I plan to implement in further PRs serializing the other chunks for embedded resources. But …
> CLI: Add ability to directly export to JSON from the archives

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
At a glance looked like the rest of the file was using the correct logic but might be worth a check.
closes #847
> 🐛 InsertChild Checks Item Can Be Assigned To Array, Not The Other Way Around

- WolvenKit.App/ViewModels/Documents/RDTInkTextureAtlasViewModel.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewModel.cs
Fixed:
- RedDocumentViewModel.GetFileFromDepotPath
> Fix RedDocumentViewModel.GetFileFromDepotPath

- WolvenKit.App/Services/PluginService.cs
- Check for the redmod executable instead of the non-existent version.txt file
- Temporary fix until the version.txt file and the remote version exists
> Temporarily Fix RedMod not being detected

- WolvenKit.App/Helpers/RegistryHelpers.cs
- WolvenKit.App/ViewModels/Dialogs/FirstSetupViewModel.cs
- WolvenKit/Views/Dialogs/Windows/FirstSetupView.xaml.cs
- No new features.
- Automatic "Cyberpunk2077.exe" install location lookup sometimes did not work on first time run.
Made some optimizations.
* Introduced high probability default install location check for Steam first.
* Code duplication reduction.
* Partially moved from the `FirstSetupViewModel.cs` into a new static `RegistryHelpers.cs` class.
* Parallel Loop state introduced to gracefully exit without finishing the loops (similar to `break;`).
* Skip second parallel loop if we already have the `FileNamePath`.
* Removal of unneeded local `void` method for assignment since assignment.
* Really shouldn't be parallel assignments occurring other than really weird multi-official installation locations (if that is even possible).
* Removed or added blank lines where appropriate in the areas I …
>  Fix for automatic Cyberpunk 2077 FileNamePath lookup.

- WolvenKit/App.xaml.cs
- WolvenKit/WolvenKit.csproj
For #930
* Better Serilog WriteTo.File default options.
* Introduce Serilog Async for performance.
* Customize Logging visibility level based on `#if DEBUG`.
Introducing [Serilog.Sinks.Async](https://github.com/serilog/serilog-sinks-async). This allows logging to be buffered and performed on background threads, thus freeing up the MAIN/UI thread when possible. I have seen some non-zero CPU utilization when logging was involved.
Added some healthy defaults for Serilog File sinks and introduced them as async.
`Log.CloseAndFlush()` missing on Application Exit();
Users - unless using a debug build - will no longer get the verbose logging by default. I feel this should be configurable as it could potentially interfere with troubleshooting. Unless of course its mainly just warning/error logs …
> Serilog Enhancements

- WolvenKit/App.xaml.cs
* Adding a shutdown log, this helps make sure Flush on Close is working as intended.
* Unsatisfied with the delay in writing to Disk, forcing the a write from buffer every a minute.
I was unsatisfied with the delay of writing to disk when adding a buffer. Rather than rolling back buffered logging as it does improve performance and cut down on disk writes, I researched how to trigger forced write on time interval. It is configured to every minute now.
* New log on application exit, no real value other than knowing Serilog Close/Flush is working.
* Regardless of whether the Serilog LogFile write buffer is full or not, it will write every minute and still write on close.
#930 
@houseofcat
> Buffered Serilog Write Time Improvement

- WolvenKit/App.xaml.cs
It's admittedly not the best solution, but helpful until all commands that have `ThrowsExceptions` can be subscribed to.
* Similar to Global Exception Handler.
N/A
When debugging, it will automatically break at time of Exception received.
> RxApp DefaultExceptionHandler

- WolvenKit.App/ViewModels/Tools/ImportExportViewModel.cs
Early exit out of `ImportSettings` with no `ActiveProject`.
Used `RelayCommand` attribute's property `CanExecute` and a new property to determine if we `HasActiveProject`.
@seberoth mentioned how a user could try importing/load settings without having an `ActiveProject`. This leads to an `NullReferenceException` and crash to desktop. I just short circuit in this scenario and early return out without error.
The crash was in a method called `SaveSettings()` but it didn't seem like any of this code should execute without the `ActiveProject` so moved the check further up the call stack.
> Fix for ImportExportViewModel Crash

- WolvenKit.App/Services/IProjectManager.cs
- WolvenKit.App/ViewModels/Tools/ImportExportViewModel.cs
- WolvenKit/Views/Tools/ImportExportView.xaml.cs
* Re-enable button after Projects are loaded into memory.
* Just the correct amount of wiring for Observable to trigger and updating the Interface to allow React Observability on the target property.
#934 
@houseofcat
> Continued Fix For ImportSettings Code

- WolvenKit.CLI/Commands/UncookCommand.cs
- WolvenKit.Modkit/RED4/Tasks/ConsoleFunctions.cs
- WolvenKit.Modkit/RED4/Tasks/UncookTask.cs
Add CLI options to export meshes.
`--mesh-export-type` which matches the export types in the UI
`--mesh-export-material-repo` which optionally allows to have a material repo in a different folder than the output
Added as well a small refactor for the uncook options to make it easier in the future to add more options.
When reviewing, I recommend enabling the hide whitespace changes option, it renders the refactor much easier to read.
Fixed:
- #805
> Add --mesh-export options to the uncook CLI command

- WolvenKit.App/ViewModels/Shell/MenuBarViewModel.cs
- WolvenKit.Common/Interfaces/IModTools.cs
- WolvenKit.Core/Extensions/IEnumerableExtensions.cs
- WolvenKit.Core/Interfaces/IGameFile.cs
- WolvenKit.Modkit/RED4/Tools/MlmaskTools.cs
- WolvenKit.Modkit/RED4/Uncook.cs
- WolvenKit.RED4.Archive/Base/FileEntry.cs
- WolvenKit/App.xaml.cs
- WolvenKit/Views/Dialogs/Windows/MaterialsRepositoryDialog.xaml
- WolvenKit/Views/Dialogs/Windows/MaterialsRepositoryDialog.xaml.cs
- WolvenKit/Views/Shell/MenuBarView.xaml
- WolvenKit/Views/Shell/MenuBarView.xaml.cs
- Ja-to's command improvements.
- Added new parallelism style that should be more responsive to the entire system and UI.
- Added ability to feature flag revert to legacy parallelism.
- Enhance legacy parallelism with options.
- Some arithmetic bug fixes on range / division operations. Relates to #939
- Better logging on Uncook exceptions that were getting lost in the ether.
```ini
i9 12900K @ 5.0 GHz, 32 GB of DDR4 4000 MHz
// DEBUG
12:37:29 pm - tweaked parallel foreach starttime
12:40:17 pm - endtime
2 minutes 48 seconds
// expected to be slower but better system responsiveness
// DEBUG
12:59:35 pm - new parallelforeach async starttime
13:01:54 pm - endtime
2 minutes 19 seconds
```
While the results showed it was faster, I would caution that the results are dependent on the system and …
> Rework Depot Operations

- WolvenKit.Modkit/RED4/Tools/MaterialTools.cs
- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
- WolvenKit.Modkit/RED4/Tools/MorphTargetImportTools.cs
- WolvenKit.Modkit/RED4/Tools/MorphTargetTools.cs
This nullcheck already exists in a few places, but it seems some of the assertions were forgotten.
Wolvenkit doesn't really support extracting non-rendered meshes. There's a few of them in the base folder of the archives, and right now they trigger NullPointerExceptions.
If we want to support these later, we'll probably want to have different extracting functions altogether, or it would need at least some bigger refactoring.
> Add extra nullchecks for the RenderResourceBlob

- WolvenKit/Views/Dialogs/Windows/RenameDialog.xaml.cs
- WolvenKit/Views/Tools/ProjectExplorerView.xaml
- WolvenKit/Views/Tools/ProjectExplorerView.xaml.cs
Improve Rename in Project File Explorer and add Key Shortcuts
Implemented:
- Rename Dialog now selects the filename of the file to be renamed
- Add keyboard shortcut (F2) for rename dialog
- Add keyboard shortcut (Del) for delete dialog
I had to attach the keyboard shortcuts to KeyUp rather than KeyDown because F2 wouldn't work with KeyDown. Not sure why that is.
> Improve Rename in Project File Explorer and add Key Shortcuts

- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
- WolvenKit/Views/Tools/AssetBrowserView.xaml
- WolvenKit/Views/Tools/AssetBrowserView.xaml.cs
Implemented:
- Asset Browser will open the directory tree to the Depo Path and scroll it into view
- Right side File View will show all files in directory, but select desired file
- Notification system will now warn if the file could not be found in the Asset Browser
> Update "Open in Asset Browser" to full expand Browser to file path

- WolvenKit.CLI/Program.cs
When starting a very slow command with the CLI, there's no currently way to stop the program from running until it reaches completion, except by killing it's process from another terminal or task manager.
Ctrl-C as an "emergency" shortcut, is the current convention on all modern system to cancel a console command.
`Environment.Exit` cannot be used because there's many exception handlers which swallow unknown errors which ignores the command to exit, and simply continues to run.
We don't really care about graceful shutdown since it's a cancellation action from the user. It should act as fast as possible.
> Implement Ctrl-C shortcut for the CLI

- WolvenKit.App/Extensions/SharpDXExtensions.cs
- WolvenKit.App/Helpers/MeshHelpers.cs
Fix UV map for mesh preview
Fixed:
- Flips UV map for the file editor mesh preview. Mesh UV's in the previewer are now aligned with textures after XBM changes.
Closes #962
> Fix UV map for mesh preview

- WolvenKit/Views/Tools/AssetBrowserView.xaml.cs
Add Arrow Key Support for Asset Browser Navigation
Implemented:
- Add left and right arrow key support for Asset Browser navigation (left column). The keys will collapse / expand nodes and jump up and down the hierarchy.
Notes:
The tooltip hover behaves really wonky. I don't know if my changes resulted in the behavior of if they just "spotlight" them. Also, I had to register to KeyUp since the SfTreeGrid eats left and right key presses as it would normally use them to move between columns. Not sure how to solve this.
> Add Arrow Key Support for Asset Browser Navigation

- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
- WolvenKit/Views/Tools/AssetBrowserView.xaml
- WolvenKit/Views/Tools/AssetBrowserView.xaml.cs
Enables browse to folder for all files in the right file view. This is most useful for opening the folders to the selected file after a search is performed.
Also a small performance increase by removing ToAsyncEnumerable in "FindUsing" and "FindUses"
> AssetBrowserViewModel: Browse to Folder

- WolvenKit.CLI/Commands/UncookCommand.cs
- WolvenKit.Common/Model/Arguments/ExportArgs.cs
- WolvenKit.Modkit/RED4/Tasks/UncookTask.cs
- WolvenKit.Modkit/RED4/Tools/Common/Structs.cs
- WolvenKit.Modkit/RED4/Tools/MaterialTools.cs
- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
- WolvenKit.Modkit/RED4/Uncook.cs
This adds a new option for mesh exports, where submeshes are exported as primitives of a mesh inside the GLTF scene, instead of what currently is happening where the submeshes are individual meshes.
This makes it much easier to work with meshes when trying to visualize streaming sectors in third-party programs, because meshes are properly hierarchy organized, instead of all at the root of the scene.
This also will make it simpler in the future if we want to use the GLTF extension for material variants (which I plan to try to add soon).
This is heavily based on the work from @jackhumbert in his [mesh-import-export branch](https://github.com/WolvenKit/WolvenKit/tree/mesh-import-export-cleanup).
- Added a meshExportArgument to merge submeshes on export
- Added 2 CLI options to try it out as …
> Experimental merged mesh export option

- WolvenKit.App/Helpers/Utils.cs
- WolvenKit.App/ViewModels/Documents/MeshPreviewBlock.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- Adds a `QuestPrefabRefHash` to all nodes that get added by importing into a sector from `.json`. The hash is needed to make objects interactable and persistent
- Log a clicked mesh's name to the log in sector preview, makes finding the right node a lot easier
> Sector Editing Tweaks

- WolvenKit.CLI/Commands/SettingsCommand.cs
> Fix the settings command for OSes other than Windows

- WolvenKit.App/Services/ISettingsDto.cs
- WolvenKit.App/Services/SettingsDto.cs
- WolvenKit.App/Services/SettingsManager.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
@rfuzzo 's suggestion: to use a textbox in WolvenKit Settings that delegates _all_ listed extensions to the default System Editor.
How it looks in the Settings Dialog:
**Notes**
Delimiter is currently set to pipe/vertical bar "|".  Comparisons are all lowercase, following existing code. I did a simple Trim() for a bit more robust user entry handling.
**Testing done:**
Limited functional testing w.r.t the change, such as entering multiple extensions and seeing how the double clicking responds. Results satisfies the requirements.
> Issue 993--Add a textbox to the settings to add ignored extensions

- WolvenKit.App/ViewModels/Tools/ImportExportViewModel.cs
**Addresses the following issue:**
(EDIT: correct discord link)
https://discord.com/channels/717692382849663036/1038844130341695538/1038844130341695538
The discord issue mentioned only import. Adding it to export is trivial and may provide useful.
- Logged failed items when importing/exporting
- Notify users of failed items when importing/exporting. Coalesced into one notification window only.
**Bug Fixed:**
- Total count is not populated when executing Process All, specifically when Importing. Fix is simple and obvious.
**Testing Done:**
Tests are done on my personal project of 100 files. The following scenarios were successfully tested for both Import/Export:
- All valid files
- Several invalid files
- Clicking Process Selected when there is nothing selected
Test …
> QOL: Discord Issue--Notify and Log items that fail Import/Export. Total count bugfix

- WolvenKit.App/ViewModels/Tools/ImportExportViewModel.cs
Title says it all. Referencing methods will not feel any difference.
- Congruent code paths moved into a new Process Bulk method
**Testing Done:**
- Ensure that Process All and Process Selected works just like before from the UI.
> ImportExportViewModel Refactoring: consolidating Process Selected and Process All paths

- WolvenKit.App/ViewModels/Tools/ImportExportViewModel.cs
My oversight introduced a _potential_ performance difference for Process All in https://github.com/WolvenKit/WolvenKit/pull/1000
This _may_ be observed when the user has a lot of files to process. I figured I'd do the right thing while it's still fresh in my brain. 
Fixed:
- Flip the boolean condition check so Process All results in a short-circuit eval, theoretically providing equal performance as before.
- use the `total` variable--this approach wasn't introduced in my change, but I feel that we should be consistent. Might as well.
> Restore performance--fix a potential slight slowdown introduced by PR#1000

- WolvenKit.App/Controllers/RED4Controller.cs
Addresses https://github.com/WolvenKit/WolvenKit/issues/926
- Specification discussion was done earlier thru discord and can be ref'd if needed.
- Supports all present and future scripting elements--assuming they are deployed under the game directory.  
- The sample testbed I used contain CET, redscript, and red4ext dlls for deployment.
**Implemented**
_Assumptions for the preliminary approach: the user is responsible for structuring their scripts to match the target deployment directory structure._
- The ability to deploy scripting elements user puts under `resource` into `packed`. Please see the testbed below for a sample structure.
- Simple as-is copying, skipping the special `yaml` and `xl` files.
**Notes**
Hot deployment seems to follow a separate path and is not touched by this PR. …
> Enhancement--Script deployment support. Issue 926

- WolvenKit.App/Helpers/WKitUIScripting.cs
- WolvenKit.App/ViewModels/Documents/WScriptDocumentViewModel.cs
Implemented:
- Export files from wkit scripts (requires file to already be added to project)
```js
// export either a single item
wkit.ExportFiles("base\\gameplay\\gui\\world\\arcade_games\\roach_race\\art\\roach_race_sprites_1080p.xbm");
// or an array of items
wkit.ExportFiles(["base\\gameplay\\gui\\world\\arcade_games\\roach_race\\art\\roach_race_sprites_1080p.xbm",
"base\\gameplay\\gui\\world\\arcade_games\\roach_race\\art\\roach_race_sides.xbm"]);
// function can warn of files that do not exist in the project
wkit.ExportFiles(["base\\gameplay\\gui\\world\\arcade_games\\roach_race\\art\\roach_race_sprites_1080p.xbm",
"base\\gameplay\\code\\CDPR_bugless_code\\literally_anything.cpp"]);
// function can error on invalid type conversions (e.g. random integer)
wkit.ExportFiles(0); …
```
> feat: Add ExportFiles command to WKit Scripting

- WolvenKit.Modkit/RED4/Tools/AnimationTools.cs
- WolvenKit.Modkit/RED4/Tools/Common/Structs.cs
- WolvenKit.Modkit/RED4/Tools/MaterialTools.cs
Add the apps list of mesh items to the material.json when exporting withMaterial
Implemented:
- Add the apps list of mesh items to the material.json when exporting withMaterial
This will allow the Blender plugin to be modified to only bring in a selected material, currently theres not enough information to go from entity>appearance>mesh and select the right material as the appearance names and material names can be different in the mesh. 
I've done some exports and cant find any problems, and have imported the resulting files to blender with the current plugin without issue.
> Add the apps list of the mesh to the material.json

- WolvenKit.App/Controllers/IGameController.cs
- WolvenKit.App/Controllers/MockGameController.cs
- WolvenKit.App/Controllers/RED4Controller.cs
- WolvenKit.App/Models/LaunchProfile.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit/Views/Shell/MenuBarView.xaml
- WolvenKit/Views/Shell/MenuBarView.xaml.cs
Thought this would be a simple UI addition, but it turns out not so:
Prior to this proposed change, the only way for the user to cleanup changes/removals/renames to "other" (e.g. `r6/scripts/myscript.reds` => `r6/scripts/thecorrectnameformyscript.reds`) already-packed files under `resources` is to **manually delete** them from the `packed` directory themselves.
I also added `LaunchProfile` entry and missing code path to `Cleanup()` to completely clean as an option. This allows it to clean misc items added or removed in resources dir, such as scripts. 
Implemented and Added:
- The `Clean All` button
- Added `LaunchProfile` options to do so.
- Added optional code path to `Cleanup()` to handle the rest of the `resources/` dir not covered by it. Options are done thru `LaunchProfile`s. The …
> Clean all button--issue 1022. 

- WolvenKit.App/ViewModels/Documents/MeshPreviewBlock.cs
- WolvenKit.App/ViewModels/Documents/MeshPreviewSector.cs
- WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
Implemented:
-  Add worldNodeData index on the logged message of LeftClick event over Mesh Component in MeshPreview View
---
On "Sector Preview" view, when clicking on a Mesh, prints in the log 
```
[13/12/2022 19:21:24] worldNodeData[205] : _instancedMeshNode
````
instead of 
```
[13/12/2022 19:21:24] Mesh Name  : _instancedMeshNode
```
> Improves tracebility on MeshPreview to respective worldNodeData

- WolvenKit.App/Helpers/MeshHelpers.cs
- WolvenKit.App/ViewModels/Documents/MeshPreviewBlock.cs
- WolvenKit.App/ViewModels/Documents/MeshPreviewEntity.cs
- WolvenKit.App/ViewModels/Documents/MeshPreviewSector.cs
- WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
- WolvenKit/Views/Documents/RDTDataView.xaml.cs
- WolvenKit/Views/Documents/RDTMeshView.xaml
- WolvenKit/Views/Documents/RDTMeshView.xaml.cs
Adds a visual and textual feedback when selecting a rendered mesh on `Sector Preview` view. 
https://user-images.githubusercontent.com/4053748/210269985-c1bc9da3-709a-48c0-8f4e-df31941f7abc.mp4
Capturing the click over a mesh will select it and display in blue `#0000FF` to give a visual contrast of current used colors. Also, the worldNode will be displayed on new grid item called "Selection", e.g. : *worldNode [145] instanceMeshNode*
Implemented:
- Mesh selection on Sector Preview view. Highlighting the Mesh in blue and displaying the name in selection field.
- Renames header from `Sector Previews` to `All Sector Preview`, in **MeshPreviewBlock.cs**
- Split mouse events per type of Preview : Mesh, All Sector, Sector and Entity
Fixed:
-  Mouse events on all previews is properly restored …
> Adds Mesh selection on Sector Preview

- WolvenKit.App/Helpers/WKitUIScripting.cs
- WolvenKit.Common/Model/Arguments/ExportArgs.cs
- WolvenKit/Resources/SyntaxHighlighting/JavaScript-DarkMode.xshd
Fixed:
- Refactored `wkit.ExportFiles` for scripting
Currently just a draft PR to track adding in export options. PR could be merged now to restore functionality without the additional feature
> Restore ExportFiles for Scripting and Add Export Settings

- WolvenKit.App/ViewModels/Documents/WScriptDocumentViewModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
Fixed:
- SaveAs acting as regular save
It now opens a proper SaveFileDialog and gives the opportunity to save the script with a new name and theoretically in a different folder (might not be good?). I also reopen the saved file on saving to make sure that the UI updates accordingly.
closes #1028
> Implemented saveAs for wscript files (Issue #1028)

- WolvenKit.Common/Model/Arguments/ImportArgs.cs
- WolvenKit.Modkit/RED4/Tools/MeshImportTools.cs
- WolvenKit.Modkit/RED4/Tools/MorphTargetImportTools.cs
- Added toggle in import screen that allows the importer to handle LOD0 submeshes as LOD8, if found.
closes #854
> Implemented import option to handle LOD0 as LOD8 if needed.

- WolvenKit/Views/Documents/RDTWidgetView.xaml.cs
There are inkwidget files which contain libraryItems with empty packageData.
An example would be the wardrobe.inkwidget from EquipmentEx which has two libraryItems (Root and OutfitManager which don't seem to contain any packageData) resulting WolvenKit running into an exception and displaying absolutely nothing.
This small change will skip those libraryItems and atleast display the ones that contain packageData.
closes #1075
> Skip packages with empty chunks instead of running into an exception

- WolvenKit.Modkit/RED4/Uncook.cs
fix:
- inkatlas export will now log if it fails, because it can't find a xbm file in a game archive
Closes #979
> fix: added logging if can't find xbm on inkatlas export

- WolvenKit.Modkit/RED4/Tools/MeshImportTools.cs
This fixes the submesh order not being determined by object name in Blender, but rather the mesh name that is connected to the object. Those occasionally get mixed up when joining and separating.
Closes #1036
> Fix submesh order being determined by mesh name (MeshData in Blender) instead of node name (Object name in Blender)

- WolvenKit.App/Controllers/RED4Controller.cs
If a user creates a subdirectory to the Resources folder and it contains TweakXL yaml files, this change will pack the project with those relative paths.
This partially satisfies the custom path request by Apart on Discord.
> Enable TweakXL Subdirectories

- WolvenKit.Common/Model/Arguments/ExportArgs.cs
- WolvenKit.Common/Model/Arguments/ImportArgs.cs
- WolvenKit.Modkit/RED4/Tools/Common/Structs.cs
- WolvenKit.Modkit/RED4/Tools/MaterialTools.cs
- WolvenKit.Modkit/RED4/Tools/MeshImportTools.cs
- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
- WolvenKit.Modkit/RED4/Uncook.cs
Include Garment Support for Custom Garments
Implemented:
- Write to custom accessors in glb when exporting garment mesh
- Write to Garment Support parameters when importing mesh with garment support data
> Include Garment Support for Custom Garments

- WolvenKit.Modkit/RED4/Tasks/UncookTask.cs
Apply meshes uext arg to uncook command
Implemented:
- Applied #1029 also to uncook
> fix: Apply meshes uext arg to uncook command

- WolvenKit.Common/RED4/RedImage.cs
Fixed:
- don't compress images when compression is "none"
#1135
> Texture Import fixes

- WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
Clicking the "Generate materials for appearance" button will now recreate the materials. This was previously done only once (abort condition: rendered), and the user would be required to re-open the file if they changed anything.
Fixed: Exception breaking mesh preview
If more materialEntries than material definitions are present, there would be exceptions, and the mesh preview would break. 
New behaviour: it will now stop parsing when it has reached the end of the list. Appearances with missing materials won't be listed. (Potentially it might be better to assign a default material? Maybe screaming pink with "UNDEFINED" on it? I don't know how, though.)
Will create a follow-up ticket.
> Mesh preview robustness

- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
Implemented:
- Case-insensitive string match on archive path for Asset Browser search
It's a refinement, so can be used in any valid refinement position (but first probs usually makes sense):
`a:auska > .mesh > gold` == `.mesh > a:auska > gold`
> ✨ `a[rchive]:<string>` Refinement Matches on Archive Path

- WolvenKit.App/Models/SlotSet.cs
- WolvenKit.App/Models/TweakXL.cs
- WolvenKit.App/ViewModels/Documents/RDTGraphViewModel.cs
- WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.Common/Conversion/inkWidgetSerializer.cs
- WolvenKit.RED4/Archive/IO/CR2WWriter.cs
- WolvenKit.RED4/Archive/IO/RedPackageWriter.cs
- WolvenKit.RED4/Save/Parser/PersistencySystem2Parser.cs
- WolvenKit.RED4/TweakDB/TweakDB.cs
- WolvenKit.RED4/Types/Classes/worldBenchmarkSummary.cs
- WolvenKit.RED4/Types/RedBaseClass.cs
- WolvenKit.RED4/Types/Reflection/ExtendedEnumInfo.cs
- WolvenKit.RED4/Types/Reflection/ExtendedPropertyInfo.cs
- WolvenKit.RED4/Types/Reflection/ExtendedTypeInfo.cs
- WolvenKit.RED4/Types/Reflection/RedReflection.cs
- WolvenKit/Views/Documents/RedDocumentView.xaml.cs
General fixes
Implemented:
- Mesh/Graph Preview: Load preview only after the tab is selected (speeds up CR2W loading time)
Fixed:
- Streamingsector Preview: Fixed an ArgumentNullException
- CEnum: Fixed wrong value if the default value is != 0
- Tweak to YAML: Fixed crash if a TweakDBID is unresolveable
Refactor:
- Moved default check from `RedReflection` to `ExtendedPropertyInfo`
Added missing property for 1.61_DLSS3
Updated `tweakdbstr.kark`
> General fixes

- WolvenKit/Views/Tools/ProjectExplorerView.xaml.cs
Implemented:
- Dragging-and-dropping a folder on itself will no longer copy the folder to the folder [(1146)](https://github.com/WolvenKit/WolvenKit/issues/1146)
_yo dawg, we heard you liked folders_
closes #1146
> 1146: prevent adding folders to themselves by accident

- WolvenKit.App/ViewModels/Exporters/TextureExportViewModel.cs
- WolvenKit.Common/Model/Arguments/ExportArgs.cs
- WolvenKit.Modkit/RED4/Tools/MaterialTools.cs
- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
- WolvenKit.Modkit/RED4/Uncook.cs
Trying to get rid of duplication and possible NOT duplication in the mesh/withrig/multi export path. The import already uses one code path.
⚗️ Experimental category + feature toggle for new mesh export logic
✨ Happy path for single mesh export works
> ♻️ Experimental Unified Mesh Exporter

- WolvenKit.App/ViewModels/Exporters/TextureExportViewModel.cs
- WolvenKit.Common/Model/Arguments/ExportArgs.cs
- WolvenKit.Modkit/RED4/Import.cs
- WolvenKit.Modkit/RED4/ModTools.Types.cs
- WolvenKit.Modkit/RED4/Tools/MaterialTools.cs
- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
- WolvenKit.Modkit/RED4/Tools/MorphTargetTools.cs
- WolvenKit.Modkit/RED4/Uncook.cs
Minimal, unstructured scaffolding to import/export type-tagged GLTFs. Since this is more involved than is ideal, export is just supported for `.morphtarget` (so that it is distinct from a `.mesh` export.) 
You can, however, use file naming to avoid having to select the import format for GLTFs. 
Rather than try to surgically fix things here and there, I think the best option is to:
1. Get rid of the separate Mesh, WithRig and Multimesh exports and just treat everything as cases of Multimesh in a single code path (which is what import does on the return trip.) This also needs a better UI, but should work transparently anyway. -> Doing this in #1197 
2. Try to separate import/export data handling from the filesystem ops, either by returning data streams from the exporters, or by passing in a …
> 📛 Export/Import Type Tagged `.morphtarget` GLTF

- WolvenKit.Modkit/RED4/Tools/MeshImportTools.cs
Garment Support attribute check and type fix
Implemented:
- Removed unnecessary check for color attribute before writing to garment support parameters, since importing garment support is currently driven by a checkbox in import settings
Fixed:
- Fixed an incorrect integer type being written to a parameter in the off chance that the cap color attribute has a value
> Garment Support fixes

- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
Fixes persistent crash on deployment in Mod Manager
To reproduce crash:
1. Go to Mod Manager screen
2. Refresh to show all mods if none listed
3. Force Deploy all mods
4. Watch Crash when progress reaches step 5/5
This occurs when `TaskStatus` is updated by `ProgressService_PropertyChanged` but not on the main thread, causing "System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it." This change invokes the status update on the main thread when `ProgressService_PropertyChanged` is called.
> fix: Move AppViewModel TaskStatus to update on main thread

- WolvenKit.App/ViewModels/HomePage/Pages/ModsViewModel.cs
- WolvenKit/Converters/BooleanToSfStepTypeConverter.cs
- WolvenKit/Views/HomePage/Pages/ModsView.xaml
Mod Manager QoL Improvements:
* Changes deployment page to use a step progress bar
* Hides log by default for a cleaner look (can be shown after deployment completes or fails)
https://user-images.githubusercontent.com/931177/224888488-10e29c63-35f9-439b-bfde-cf65df47b731.mp4
Note: video shows 1s animation time between steps, changed to 0.75s in PR
> feat: Display REDmod deploy progress steps

- WolvenKit.Modkit/RED4/Uncook.cs
Implemented:
Currently the Multimesh has a list labelled 'additional meshes' that you have to include the selected mesh into to get it to export. Minor change that adds the selected mesh to the export list if its not in there. Added to both old and new export flows, but cant test the old one as its not working for other reasons.
Fixed:
- never got round to filing a bug, but the fact the additional list wasn't additional at all but the whole export list, and the selected file wasn't automatically added.
> Add the selected mesh to the export list for multimesh 

- WolvenKit.App/Controllers/RED4Controller.cs
Fixed:
* `.tweak` deployments and simplified it by removing the function. I can add it back in if we really want, but for now, it simplifies the logic.
Changed:
* `IsScript` is now `IsCDPRScript` to avoid any possible confusion for future things we may do with `.reds`
> fix: .tweak files don't deploy upon packing a REDmod mod

- WolvenKit.Modkit/RED4/Tools/MorphTargetImportTools.cs
- WolvenKit.Modkit/RED4/Tools/MorphTargetTools.cs
Export: produces correct data so that it actually *can* be imported correctly\*
Import: produces working morphtargets for vanilla/modified/custom morphs\*\*
Previously exported and/or imported morphtargets are likely to have at least some issues. Users may need to re-export and port their work on top of that.
The commits are kinda split up and the commit messages worth reading but, YMMV, it may be easier to actually review the code by reading the entire file instead of a diff.
\*,\*\* I mean, like, _probably_? I haven't tested that extensively.
_Evidence for the defense: sculpted neck on a head morph (with still-working customization & expressions)_
> fix: Morphtarget Export and Import

- WolvenKit.Modkit/RED4/Tools/MorphTargetImportTools.cs
The influences can be combined. Whether they're treated as cumulative or mutually exclusive is completely external semantics. We must assume cumulative in order to create a big enough bounding box and quantization space.
> fix: Calculate Morphtarget Bounds Cumulatively on Import

- WolvenKit.Modkit/Scripting/ScriptService.cs
- WolvenKit.Modkit/Scripting/WKitScripting.cs
Implemented:
- Use the `Stopwatch.StartNew()` method to create and start a new Stopwatch instance.
- Use the C# `readonly` modifier for fields that are only set in the constructor and should not be modified afterward, such as `_archiveManager` and `_redParserService`.~
- Use expression body for simple getter like methods for a consistent code style
Fixed:
- Fixes #1287
> Fix #1287, Quality of live improvements for Scripting namespace

- WolvenKit.Modkit/RED4/Export.cs
Implemented:
- `?` to avoid possibly null reference
- Naming scheme for some variables
- Added missing param tag in XML comment
Fixed:
- Fixes #1289
> Fix #1289, Possibly null reference

- WolvenKit.App/Services/ExtendedScriptService.cs
- WolvenKit/Resources/Scripts/Wolvenkit/Logger.wscript
- WolvenKit/Resources/Scripts/Wolvenkit/Wolvenkit_FileValidation.wscript
- WolvenKit/Resources/Scripts/onSave_anims.wscript
- WolvenKit/Resources/Scripts/onSave_app.wscript
- WolvenKit/Resources/Scripts/onSave_csv.wscript
- WolvenKit/Resources/Scripts/onSave_ent.wscript
- WolvenKit/Resources/Scripts/onSave_workspot.wscript
- WolvenKit/WolvenKit.csproj
file validation in WScript
Implemented:
- Added file validation for app, ent, workspot and anims
- changed file structure of WScript folder: Wolvenkit subfolder will always overwrite, everything else only if not present
- moved Logger to subdirectory
- made Logger a bit more null-proof
The original logger won't be deleted, so this shouldn't break existing scripts
> more file validation in WScript

- WolvenKit/Resources/Scripts/Wolvenkit/Wolvenkit_FileValidation.wscript
- WolvenKit/Resources/Scripts/onSave_workspot.wscript
Added a null check
Fixed:
- Validation of workspot file failing if an embedded .anims couldn't be read
> Validation scripts: Added a null check

- WolvenKit.Modkit/RED4/Tools/MorphTargetImportTools.cs
Fixed:
- Import eye (`he0`) morphtargets correctly
Mesh import assumes targets mean garmentSupport, and it _seems_ that the reason it fails for eyes only is because of the `doubled` submesh that creates a buffer size discrepancy.
> fix: Delete Incorrectly Assumed GarmentSupport on MorphTargetImport

- WolvenKit/Resources/Scripts/Wolvenkit_FileValidation.wscript
- WolvenKit/Resources/Scripts/hook_global.wscript
- WolvenKit/Resources/Scripts/hook_settings.wscript
Implemented:
- File validation is using settings objects again (Thanks Seb - or is it Serb now? 0.0)
- Exceptions, null-proofing
- DepotPaths will now be checked for equality with "0" and this will be treated as unset
> file validation: now using settings objects

- WolvenKit/Resources/Scripts/Export_Mesh.wscript
- WolvenKit/Resources/Scripts/Export_Sector.wscript
- WolvenKit/Resources/Scripts/Export_Vehicle_Ent.wscript
Updated the scripts to all have the add from project, and to load project files over base game if available. Added a seperate list for types to be added/exported if embedded so you can export mlmasks/xbms only if embedded.
Added a script to allow you to export the embedded from a file without having to export an ent/sector.
> wscript updates

- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
Fixed:
- Single-joint models (like many hats) are exported with correct rigging
SharpGLTF's ancestor finder assumes a single node is the root node, so it calculates the inverse bind matrix incorrectly.
https://github.com/vpenades/SharpGLTF/blob/b23b5ce225637f38a00be67f4641c991ed36435d/src/SharpGLTF.Core/Schema2/gltf.Skin.cs#L238
> FIX: Provide Root Explicitly for Single-Joint Rig Export

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelTools.cs
in tree view, opening/closing a node with shift key will also affect its children. 
Implemented extra checks for some objects in mesh/app, as these are the ones where not having it annoyed me the most. 
Feedback welcome, I have actually no idea what the correct way is of getting this helper class into the model.
> treeview: recursive folding/unfolding with shift key held down

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
This is a fix for
```
System.Windows.Data Error: 40 : BindingExpression path error: 'IsDeletable' property not found on 'object' ''ChunkViewModel' (HashCode=2829827)'. BindingExpression:Path=IsDeletable; DataItem='ChunkViewModel' (HashCode=2829827); target element is 'StackPanel' (Name=''); target property is 'Visibility' (type 'Visibility')
```
> fix annoying error msg spam

- WolvenKit.App/Controllers/RED4Controller.cs
- WolvenKit.App/ViewModels/Dialogs/NewFileViewModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/TweakBrowserViewModel.cs
this is a small project change so PR
Fixed:
- tweaks and scripts now nest the same under project/resources
- "override tweaks" now just creates the file and no save file dialogue
closes #1296
> fix: standardize tweaks and scripts in resources folder

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
Appearances: will list chunk materials 
CMaterialInstances (local materials): Will show name and base material
External materials: Will show name and base material 
Values (CKeyValuePairs): Will show key and value now:
> .mesh: improved a few descriptors

- Directory.Packages.props
- WolvenKit.Modkit/RED4/Tools/Animation/AnimSpline.cs
- WolvenKit.Modkit/RED4/Tools/Animation/Shared.cs
- WolvenKit.Modkit/RED4/Tools/AnimationTools.cs
- WolvenKit.Modkit/RED4/Tools/Common/Structs.cs
- WolvenKit.Modkit/RED4/Tools/RigTools.cs
- WolvenKit.RED4/Types/ClassesExt/CustomData/animAnimationBufferCompressed.cs
Basic support for all motion animation export/import. There's very likely a lot of work left to support all cases.
- Fixed data decoding/encoding of `.anims` buffers
- Added decoding/encoding for track information from the buffer
- Added track and other non-buffer animation data to GLTF encoded into the `extra` field (there isn't really any way to represent it in the standard `animations` format.)
Only manually validated on a limited set of `.anims`
Previously exported `.anims` contain incorrect/incomplete data. Need to see about a migration path, unless it's ~trivial to fix it on the Blender side and/or using new buffer logic 
- All `.anims` data isn't exported yet
- Root Motion not reimported
- Only existing animations can be edited
Additional work tracked in #1425
Probably needs work …
> Fix: .anims Export and Import

- WolvenKit.Modkit/RED4/Tools/Animation/AnimSIMD.cs
- WolvenKit.Modkit/RED4/Tools/AnimationTools.cs
An imported animset can:
- Omit animations that exist in the original, in which case the existing ones are copied to the new animset
- Include animations that do not exist in the original, in which case they're added into the animset\*
- (And obvs still update/overwrite existing ones)
\* Can you do anything with that? Who knows
> feat(anims): Partial Animset Import 

- WolvenKit.Modkit/RED4/Tools/MaterialTools.cs
- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
- WolvenKit.Modkit/RED4/Uncook.cs
Multimesh Material JSON Appearance fix
Implemented:
- added the mesh names to the submeshes rather than just the numerical prefix (only on multimesh)
- added the mesh names to the appearances in the material json so that if multimesh import has 2 meshes with the same named appearances both still get imported.
Fixed:
- Materials being available for multimesh output
Still need to do a bit of work on the Blender side to make appearance selection work, as they dont have the same name the app file has for them (but I'm not sure this has worked previously either)
> Multi mesh materials

- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
- WolvenKit.Modkit/Managers/ArchiveManager.cs
- WolvenKit/Converters/IGameArchiveToMenuItemStringConverter.cs
- WolvenKit/Views/Tools/AssetBrowserView.xaml
- WolvenKit/Views/Tools/AssetBrowserView.xaml.cs
Updates the asset browser to support pulling files from specific archives (including mod archives). Also will sort the mod browser by the (a?) load order to show the first loaded files up top. This also includes support for `modlist.txt` in `archive/pc/mod` and REDmod mods. No support for REDmod `modlist.txt` as of this update. See example image.
> Asset Browser: Extract from Specific Archive and Load Order

- WolvenKit.App/Services/PluginService.cs
Fix retrieved plugin version might be unstable version
Fixed:
- Retrieved plugin versions are now the latest stable version
The plugin version installed are the last published, as opposed to the latest stable version released. This is an issue with Redscript which has newer, but unstable and incompatible versions.
Fixes #1476
> Fix retrieved plugin version might be unstable version

- WolvenKit/Views/Templates/RedStringEditor.xaml
- turned on toggle to make string fields wrapped so that long pieces of text can be viewed in full when editing.
The use case for this feature is for when editing custom localization files in Wolvenkit. It's not easy to edit a large piece of text with only a small part of it showing at once. Editing the exported json files in a text editor can be difficult because of special characters like `\u003CRich color=\u0022TooltipText.cyberwareDescriptionHighlightColor\u0022 style=\u0022Semi-Bold\u0022\u003EFury\u003C/\u003E state`.
Here is an example before and after from `onscreens_final.json`:
Before:
After:
- I tested editing and saving a localization value, which worked.
- Nothing visually looks wrong that I can see.
- I'm not familiar enough with the code to know if there are any likely side …
> Add text wrapping to String fields

- WolvenKit.Common/Model/Arguments/ImportArgs.cs
- WolvenKit.Modkit/RED4/Tools/MeshImportTools.cs
- WolvenKit.Modkit/RED4/Tools/MorphTargetImportTools.cs
- `.morphtarget`s can include GarmentSupport data, i.e. they can (typically) shrink under clothing when GS is active
- GarmentSupport is checked by default for import for both `.mesh` and `.morphtarget` (it was already default on export)
NB: `GarmentSupport` *must* be first shapekey/target and let's require that naming too.
General GarmentSupport guide [on the redmodding wiki](https://wiki.redmodding.org/cyberpunk-2077-modding/modding-know-how/3d-modelling/garment-support-how-does-it-work)
1. In Blender, create a shapekey named `GarmentSupport` for each submesh that you want to deform for GS, typically shrinking the mesh a bit so that it doesn't clip with tighter fits
2. Ensure `GarmentSupport` is the first shapekey (after `Basis`)
3. Include `_GARMENTSUPPORTWEIGHT` and …
> fix: Morphtarget Meshes Can Also Include GarmentSupport

- WolvenKit.Common/Model/Arguments/ImportArgs.cs
- WolvenKit.Modkit/RED4/Tools/MeshImportTools.cs
maintaining backwards compatibility by setting the flag for mesh import behaviour to true as default
> setting previous import behaviour as default

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.Common/Model/Arguments/ImportArgs.cs
Mesh materials will now actually check if the material definition's index property is matching before just assuming that everything is fine if the array index is fine
> Mesh material name index fix

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
when trying to delete items in arrays that don't exist anymore, but the view somehow didn't refresh to reflect that
> chunkviewmodel: fixed an exception

- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
- WolvenKit/Layout/SFDataGridCommands.cs
- WolvenKit/Views/Tools/AssetBrowserView.xaml
- "Select all" checkbox is working again
- "Add to project" context menu item will only be visible if there's a project
- Changed asset browser message for manual loading
https://github.com/WolvenKit/WolvenKit/issues/1420
> #1420 Asset Browser select all checkbox

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
For meshMaterialEntries (mesh: material definition) and worldCompiledEffectPlacementInfo (placement tags), the index property will be auto-updated after creating an item via `Duplicate`. @seberoth, I hope you don't hate this <3
> QOL: update "index" property after node duplication

- WolvenKit.Modkit/RED4/Tools/Common/MaterialExtractor.cs
Will now fall back to metal_base.remt if material export fails.
This could probably use some indicator that the material has been substituted. Or maybe a log file entry.
> assign default material if material export fails

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
Super useful, I will be using the shit out of this. Display is strictly conditional and will only display for the right node type.
https://github.com/WolvenKit/WolvenKit/assets/965785/653913fe-4263-4371-915d-dd366dd4542f
> renumber child index properties

- WolvenKit.Core/Services/SerilogWrapper.cs
- WolvenKit.Modkit/RED4/Tools/Common/MaterialExtractor.cs
- WolvenKit.Modkit/RED4/Tools/MaterialTools.cs
I hope this didn't break the singleton
> mesh material: more fallback upon export failures, better logging

- WolvenKit.App/ViewModels/Tools/ChunkViewModel.ExpansionStates.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit/Views/Tools/ProjectExplorerView.xaml.cs
Double-clicking on a treeview item will now collapse/expand its children
The "Expand all" and "Collapse all" buttons are now context-aware (e.g. if you're in the `archive` tab, it will leave your `raw` files alone)
> Collapse expand treeview nodes

- WolvenKit.App/ViewModels/Exporters/ExportViewModel.cs
- WolvenKit.App/ViewModels/HomePage/Pages/ModsViewModel.cs
- WolvenKit.App/ViewModels/Importers/ImportViewModel.cs
- WolvenKit.App/ViewModels/Shell/RibbonViewModel.cs
- WolvenKit.App/ViewModels/Tools/ImportExportItemViewModel.cs
- WolvenKit.App/ViewModels/Tools/ImportExportViewModel.cs
- WolvenKit.App/ViewModels/Tools/ImportableItemViewModel.cs
- WolvenKit.Common/Model/Arguments/ExportArgs.cs
- WolvenKit.Common/Model/Arguments/ImportArgs.cs
- WolvenKit.Modkit/RED4/Import.cs
- WolvenKit.Modkit/RED4/ModTools.Types.cs
- WolvenKit.Modkit/RED4/RedMod.cs
- WolvenKit.Modkit/RED4/Tools/AnimationTools.cs
- WolvenKit.Modkit/RED4/Tools/MorphTargetTools.cs
- WolvenKit.Modkit/RED4/Uncook.cs
- WolvenKit/Views/Exporters/ExportView.xaml.cs
- WolvenKit/Views/Importers/TextureImportView.xaml.cs
- WolvenKit/Views/Shell/RibbonView.xaml
- WolvenKit/Views/Shell/RibbonView.xaml.cs
- Morphtargets will now have a checkbox (disabled by default) to export their texture files
- Pasting import/export settings will now refresh the property display of changed items
- Fixed the annoying multiselect bug where the active item would get deselected
- .anims will now export to .anims.glb (and automatically import to Animation)
- minor refactoring in import tool to allow better type switching from file name
> Import export tools bugfixes

- WolvenKit/Views/Tools/ProjectExplorerView.xaml.cs
Project browser's drag&drop move often failed silently - this is hopefully more robust. 
Additionally, copying without overwriting will now create `- Copy` items, the same as Windows Explorer.
> projectFileBrowser: hopefully more robust copy

- WolvenKit.App/ViewModels/GraphEditor/Nodes/Scene/scnChoiceNodeWrapper.cs
Fixed issue with scene graph loading when NotablePoints and LocStore are missing. The issue was in choice node which tried to get data from NotablePoints and LocStore, but if those are missing, it raises exception.
> scene graph load fix when NotablePoints and LocStore are missing

- WolvenKit.Common/Model/Arguments/ExportArgs.cs
- WolvenKit.Common/Model/Arguments/ImportArgs.cs
- WolvenKit.Modkit/RED4/Import.cs
- WolvenKit.Modkit/RED4/Tools/Animation/AnimSIMD.cs
- WolvenKit.Modkit/RED4/Tools/Animation/AnimSpline.cs
- WolvenKit.Modkit/RED4/Tools/Animation/Shared.cs
- WolvenKit.Modkit/RED4/Tools/AnimationTools.cs
- WolvenKit.Modkit/RED4/Tools/MeshImportTools.cs
- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
- WolvenKit.Modkit/RED4/Uncook.cs
**Fixed:**
- Reimporting additive anims now correctly strips out the local transform, with the power of basic math
- Added epsilon comparison and normalization helpers that are used to ensure we don't e.g. scale incorrectly because of floating point division imprecision.
- Import and Export toggles for including the local transform for additive animations. Should be used symmetrically, default is to use local transform (current behavior.)
**Warnings:**
- Raw additive animations don't seem to survive roundtripping through Blender. Default behavior is current, though, so might as well include it and then try to solve it in Blender.
**Open Questions:**
- Opened #1630 to further review animation scale handling logic. Currently only anims that use `1f` scale throughout are …
> fix(anims): Additive Anim Import Uses Correct Math to Strip Local Transform

- WolvenKit.Modkit/RED4/Tools/MeshImportTools.cs
Allow either normal `VEC4` or optimized `VEC3` for the `COLOR_` attributes in glTF imports. Alpha is set to `1` for the `VEC3` case.
Blender 4.1 compatibility.
closes #1635
> fix(mesh, import): Allow Optimized VEC3 COLOR_ Attributes in glTF

- WolvenKit.App/Factories/DocumentViewmodelFactory.cs
- WolvenKit.App/Helpers/StringHelper.cs
- WolvenKit.App/Helpers/StringHelpers/StringHelperAnimNode.cs
- WolvenKit.App/Helpers/StringHelpers/StringHelperWorldNode.cs
- WolvenKit.App/Services/ISettingsDto.cs
- WolvenKit.App/Services/ISettingsManager.cs
- WolvenKit.App/Services/SettingsDto.cs
- WolvenKit.App/Services/SettingsManager.cs
- WolvenKit.App/ViewModels/Documents/DocumentViewModel.cs
- WolvenKit.App/ViewModels/Documents/RDTDataViewModel.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentTabViewModel.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.Descriptor.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.UserInteractionStates.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.Value.cs
- WolvenKit/Views/Documents/RedDocumentView.xaml
- WolvenKit/Views/Documents/RedDocumentView.xaml.cs
- WolvenKit/Views/Shell/MainView.xaml.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
- Refactored both to use switch statements rather than endless if/then/else blocks
- CVM will now check if it should be read only 
- Stub implementation for ~~noob filter~~simple editor mode (I didn't manage to hide the rows in the treeview, or I'd have left it in)
From the first commit, only `WolvenKit.App/ViewModels/Tools/ChunkViewModel.UserInteractionStates.cs` is relevant for the review (read-only)
> descriptor read-only, "simple mode" editor

- WolvenKit.App/Helpers/ArchiveXlHelper.cs
- WolvenKit.App/Models/LoadableModel.cs
- WolvenKit.App/Models/ProjectManagement/Project/Cp77Project.cs
- WolvenKit.App/Models/ResourcePathWrapper.cs
- WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewModel.cs
- WolvenKit.App/WolvenKit.App.csproj
- WolvenKit/Views/Documents/RDTMeshView.xaml.cs
**Fixed:**
- mesh entity preview for meshes with dynamic path subsitutions
- currently, only one appearance is added, but at least you can see _something_
Partially resolves #1563 (or maybe does resolve it, but root entity file previews don't work yet. See the TODOs in `RDTMeshViewModel:RenderEntity`)
> ArchiveXL dynamic paths, fixes mesh_ent preview

- WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewModel.cs
Turns out that the check was a little too thorough
> skipping dynamic path resolution (and check)  for non-mesh-components

- WolvenKit.App/Services/HashServiceExt.cs
Force adding project files to custom hashes. Prevents some unresolveable paths for modded files when the custom lookup is missing on load.
> Custom hash improvement

- WolvenKit.App/Scripting/AppScriptFunctions.cs
- `CreateInstanceAsJSON(className)`
- Takes the name of the class of which an instance is to be created, and returns it as a JSON formated string
- e.g. `wkit.CreateInstanceAsJSON("worldStaticMeshNode")`
- Implements #1668, except for always returning JSON, as cr2w does not make any sense in this use-case
> Added WScript CreateInstanceAsJSON function

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.UserInteractionStates.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
better icon+text for "Paste and overwrite"
after updating data, recalculate parent and grandparent value if they're interpolated
Added `localMaterialInstances` (not the one in "materials") to the list of hidden items
> minor tweaks&fixes

- WolvenKit.App/Scripting/AppScriptFunctions.cs
- `HashString(data, method) -> ulong`
- `data`: The string to be hashed
- `method`: What hash method to use, can be `fnv1a64` or `default` (Uses the built-in `String` hash method)
- e.g. `wkit.HashString("borpaSpin", "default")` -> `18446744072867596000`
P.S. I synced my fork with the main repo, but for some reason the old commits still show up here???
> Feature: WScript HashString function

- WolvenKit.App/Controllers/RED4Controller.cs
- WolvenKit.App/Services/SettingsManager.cs
- WolvenKit/Helpers/LogCodeHelper.cs
Before: 
```
Unhandled exception in WolvenKit vx.x.x.x
Message: Cannot start process because a file name has not been provided.
Source: System.Diagnostics.Process
StackTrace:    at System.Diagnostics.Process.Start()
at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
at WolvenKit.App.Controllers.RED4Controller.LaunchProject(LaunchProfile options) in D:\a\WolvenKit\WolvenKit\WolvenKit.App\Controllers\RED4Controller.cs:line 423
at WolvenKit.App.ViewModels.Shell.RibbonViewModel.LaunchProfileAsync() in D:\a\WolvenKit\WolvenKit\WolvenKit.App\ViewModels\Shell\RibbonViewModel.cs:line 86
at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
at …
```
> handling&doku when game executable couldn't be launched

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
Very useful for ArchiveXL if your materials live in a template file
> added clear all materials

- WolvenKit.RED4/Types/ClassesExt/Appendix/scnAnimName.cs
Fix for [Discord link](https://discord.com/channels/717692382849663036/1173444494247600259/1173444494247600259)
It fixes wrong name / index for RID animation container. Now it puts a string from string pool defined in the scene file. It somehow works, but it's a nightmare for editing and very hard to edit it.
This fix changes internal reading from CName to UInt16, hence changes usage of "unk1" to "unk2". I tested it on several scene files and it works as expected.
**Only problem with this fix is that already exported scene files in json can't be converted back. You first need to export them with the new fix and then you can import them back. This should be somehow noted before releasing.**
> scenes - animName - rid animation container index name

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
Fixed entVisualControllerComponent generation
**Fixed:**
- entVisualControllerComponent generation
Not sure if the condition is 100% correct but validated this behaviour against all vanilla apps and it worked.
> Fixed entVisualControllerComponent generation

- WolvenKit.App/Services/WatcherService.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit/Views/Shell/MainView.xaml.cs
- WolvenKit/Views/Tools/ProjectExplorerView.xaml.cs
ProjectExplorer fixes
- Saving of states while closing WolvenKit
**Fixed:**
- Fixed an issue where not all states were saved while using `ExpandAllNodes` and `CollapseAllNodes`
- Fixed an issue where a new instance of `ProjectExplorer` was created instead of using the existing one
> ProjectExplorer fixes

- WolvenKit.App/Models/FileSystemModel.cs
- WolvenKit.App/Services/WatcherService.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit/Views/Tools/ProjectExplorerView.xaml.cs
**Fixed:**
- Renaming folder losing expansion state
- Pasting folder structures into project folder not adding the child items
- Filtered ProjectExplorer showing wrong folders
> Project Explorer fixes

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
fixed an exception when trying to access `localMaterialBuffer` (null) in meshes with `preloadLocalMaterialInstances`
> delete unused materials: fixed exceptions

- WolvenKit.Common/Constants.cs
- WolvenKit.Common/RED4/CR2W/JSON/RedJsonSerializer.cs
Given how small this PR is and how many classes this ultimately affects during json exports, further study may be needed, but this works for every file type I've test so far.
- Closes #1701
- Forces the default character escaping outside of `UnicodeRanges.BasicLatin` character range which will fail json validation
- Bumps json version number since this is a different encoding than previously used (`UnicodeRanges.All`)
Example of previously failing json in linked issue
> Use Default Encoder for RedJsonSerializer

- WolvenKit/Views/Dialogs/Windows/ChooseCollectionView.xaml
Renamed the right column of this window when for example choosing audio hashes to export from opusinfo:
> fix: Change header text to "Selected" for the column of selected items

- WolvenKit.App/Services/IModifierViewStateService.cs
- WolvenKit.App/Services/ModifierViewStateService.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit/Views/Shell/MainView.xaml
- WolvenKit/Views/Shell/MainView.xaml.cs
- WolvenKit/Views/Tools/ProjectExplorerView.xaml
- WolvenKit/Views/Tools/ProjectExplorerView.xaml.cs
- WolvenKit/WolvenKit.csproj
- Fixed the context menu getting stuck sometimes (by adding another modifier state listener to the main app)
- Added visibility toggle for expand/collapse children (shift modifier)
- Added "find currently open file" button. It'll only be enabled if there's a currently active file.
TODO: Enable the button only for files in current project.
no shift
shift
> ProjectExplorer: fixed modifier state tracking

- WolvenKit.Common/Services/HashService.cs
- WolvenKit.Core/Compression/KrakenNative.cs
- WolvenKit.Core/Compression/Oodle.cs
- WolvenKit.Core/Compression/OodleLib.cs
- WolvenKit.Core/Helpers/GCHelper.cs
- WolvenKit.Core/Unmanaged/UnmanagedMemory.cs
- WolvenKit.RED4/Types/Pools/ResourcePathPool.cs
- WolvenKit/Initializations.cs
- Oodle decompressing now allocates/deallocates unmanaged memory only to prevent massive byte[] going into LOH
- Right after shell initialization application now requests LOH (and every other generation) cleanup to handle other unfixed LOH cases for now.
> Another memory optimization patch

- Tests/WolvenKit.UnitTests/FNV1A64Tests.cs
- WolvenKit/Views/Tools/HashToolView.xaml.cs
**Fixed:**
- Hash Tool window used old algorithm to calculate NodeRef's hash. That is fixed now.
> HashTool window now uses new algo to calculate NodeRef's hash

- WolvenKit.App/Services/ISettingsDto.cs
- WolvenKit.App/Services/SettingsDto.cs
- WolvenKit.App/Services/SettingsManager.cs
- WolvenKit/Views/Dialogs/ProjectWizardView.xaml.cs
Added modder name and e-mail to settings. On creation of a new project, the default values will be populated, if they are set. 
Closes #1753
> 1753: name and e-mail default for new project in settings

- WolvenKit.App/ViewModels/Documents/RDTDataViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.ExpansionStates.cs
After opening an .mi file: Will select the first element in `values` (if there is one)
When generating materials: Will now correctly understand dynamic materials
> Cvm: more default expansion states

- WolvenKit.App/Controllers/RED4Controller.cs
- WolvenKit.App/Interaction/Interactions.cs
- WolvenKit.App/Models/LaunchProfile.cs
- WolvenKit.App/Models/SaveGame.cs
- WolvenKit.App/Resources/launchprofiles.json
- WolvenKit.App/Services/ISettingsDto.cs
- WolvenKit.App/Services/ISettingsManager.cs
- WolvenKit.App/Services/SettingsDto.cs
- WolvenKit.App/Services/SettingsManager.cs
- WolvenKit.App/ViewModels/Dialogs/LaunchProfileViewModel.cs
- WolvenKit.App/ViewModels/Dialogs/LaunchProfilesViewModel.cs
- WolvenKit.App/ViewModels/Dialogs/SaveGameSelectionDialogModel.cs
- WolvenKit.App/ViewModels/HomePage/Pages/ModsViewModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.App/ViewModels/Shell/RibbonViewModel.cs
- WolvenKit.App/WolvenKit.App.csproj
- WolvenKit/GenericHost.cs
- WolvenKit/Views/Dialogs/Windows/LaunchProfilesView.xaml
- WolvenKit/Views/Dialogs/Windows/LaunchProfilesView.xaml.cs
- WolvenKit/Views/Dialogs/Windows/SaveGameSelectionDialog.xaml
- WolvenKit/Views/Dialogs/Windows/SaveGameSelectionDialog.xaml.cs
- WolvenKit/Views/Shell/MainView.xaml.cs
- WolvenKit/Views/Shell/RibbonView.xaml
- WolvenKit/Views/Shell/RibbonView.xaml.cs
- WolvenKit/WolvenKit.csproj
Moves "Launch game and load last save" from the title bar into the launch options, where it should be.
closes issue #1486 
- REDMod install and launch options are now hidden from the ribbon, can be brought back via settings
- More launch profiles. If you don't want to use the default ones, you can turn that off via setting as well.
- WKit now remembers the last launch profile between restarts
- Changed property descriptions to make clearer what they do
- You can load a named savegame:
> Launchprofiles refactoring & overhaul

- WolvenKit.App/ViewModels/Dialogs/SearchAndReplaceDialogViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.SearchAndReplace.cs
- WolvenKit/Views/Dialogs/Windows/SearchAndReplaceDialogView.xaml
- WolvenKit/Views/Dialogs/Windows/SearchAndReplaceDialogView.xaml.cs
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
Search and replace: 
- removed "ignore case" checkbox (which did nothing)
- won't abort on "contains" anymore. Also, checking more hashes
> Search&Replace: removed "ignore case", some fixes

- WolvenKit.Modkit/RED4/Tools/Animation/AnimRootMotion.cs
- WolvenKit.Modkit/RED4/Tools/Animation/AnimSIMD.cs
- WolvenKit.Modkit/RED4/Tools/Animation/AnimSpline.cs
- WolvenKit.Modkit/RED4/Tools/Animation/Shared.cs
- WolvenKit.Modkit/RED4/Tools/AnimationTools.cs
- WolvenKit.RED4/Types/ClassesExt/CustomData/animAnimationBufferCompressed.cs
- Root Motion export with toggle, import without toggle based on glTF data
- Root Motion is `Translation` and possibly `Rotation`, type dependent. No `Scale`.
- Only Root Motion *or* regular root joint transforms (if any) are exported, not both, not mixed
- glTF storage for RM is in root joint, as per above
- glTF extras for each anime schema v4 includes `RootMotionType` that tries to be clearer on intent
- `None` if RM requested but there's none
- `Unknown` if not requested (whether or not one exists)
- Others if requested and found
- Previous schemas migrated with `RootMotionType.Unknown`
- `None` uses root transforms as regular and deletes old RM
- `Unknown` copies old RM from CR2W, if any, doesn't touch root joint, essentially equivalent to toggle
- Others store indicated type and …
> Root Motion

- WolvenKit.Modkit/RED4/Uncook.cs
Worst case: bin is still extracted and the file conversion will fail. Best case: you actually get the uncooked file.
> CLI: Use guessed extension when uncooking

- WolvenKit.Modkit/RED4/Tools/OpusInfo.cs
- WolvenKit.Modkit/RED4/Tools/OpusTools.cs
**Fixed:**
- Importing .wav files to opuspaks "broke" the whole opuspak
I don't know if it still builds :D
> Fix importing opuspaks not producing new opuspaks

- WolvenKit.App/Controllers/RED4Controller.cs
- WolvenKit.App/Models/FileSystemArchive.cs
- WolvenKit.App/Models/TweakXL.cs
- WolvenKit.App/ViewModels/Documents/RDTDataViewModel.cs
- WolvenKit.App/ViewModels/Documents/RDTInkTextureAtlasViewModel.cs
- WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
- WolvenKit.App/ViewModels/Documents/RDTWidgetViewModel.cs
- WolvenKit.App/ViewModels/HomePage/Pages/ModsViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.ExpansionStates.cs
- WolvenKit.Modkit/Managers/ArchiveManager.cs
- WolvenKit.Modkit/RED4/Serialization/yaml/TweakTypeConverter.cs
- WolvenKit.Modkit/RED4/Tools/MaterialTools.cs
- WolvenKit.Modkit/RED4/Tools/MorphTargetTools.cs
- WolvenKit.RED4/Archive/IO/PreProcessor/CMeshPreProcessor.cs
- WolvenKit.RED4/Types/Primitives/Simples/ResourcePath.cs
- WolvenKit/Views/Templates/RedRefEditor.xaml.cs
- added auto-unfolding for inkatlas
- added warning about CET entity spawn when launching with `-save` arg
> fixed validating depot path editor

- .github/workflows/publish-nugets.yml
**Fixed:**
- Core hasn't been published as a nuget since 2021, making the .RED4 package useless to publish as it requires the .Core project. This simply adds core to the list of published packages, which I assume will fix the issue.
> Add Core to list of published packages

- WolvenKit.App/Controllers/RED4Controller.cs
**Fixed:**
Creating a REDmod zip will now generate a .json file again (only installing as REDmod did that before)
closes #1880
> fix: #1880 redmod.json generation

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
Works without performance issues on `base\worlds\03_night_city\_compiled\default\ep1\always_loaded_0.streamingsector` (or at least doesn't add any performance issues that weren't already there)
> ArrayIndexWidth will now be calculated based on _actual_ width

- WolvenKit.Modkit/RED4/Tools/OpusTools.cs
- WolvenKit.Modkit/RED4/Uncook.cs
**Fixed:**
- ~~Seb~~ Someone forgot to dump JSON from OpusInfo when requested in Export Tool, I fixed that
It simply serializes the OpusInfo class, just like original sacred scripts from HitmanHimself did.
> Fix uncooking OpusInfo not dumping JSON

- WolvenKit.Modkit/RED4/Tools/OpusTools.cs
- WolvenKit.Modkit/RED4/Uncook.cs
**Fixed:**
- Rare bug where if depoth path was `""` the Export Tool only worked once per file per session
Un
> Fix rare bug with empty depot path and exporting

- WolvenKit.App/ViewModels/Exporters/ExportViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.Value.cs
- WolvenKit.CLI/Commands/UncookCommand.cs
- WolvenKit.Common/Model/Arguments/ExportArgs.cs
- WolvenKit.Modkit/RED4/Tasks/UncookTask.cs
- WolvenKit.Modkit/RED4/Tools/OpusInfo.cs
- WolvenKit.Modkit/RED4/Tools/OpusTools.cs
- WolvenKit.Modkit/RED4/Uncook.cs
- Exporting of all sounds from OpusInfo/Paks (hidden in GUI)
- Options to configure the `uncook` command for OpusInfo
- Alcohol into my bloodstream
Closes #1909 
Depends on #1914 
Also is waiting for #1913
> Add OpusPak/OpusInfo support to CLI

- WolvenKit.CLI/Program.cs
**Fixed:**
- WolvenKit.CLI immediately crashing on Linux/macOS due to attempted nt.dll library load
- Linux on average has a PATH_MAX of 4096 but it depends on the filesystem.
- macOS on HFS+ has a PATH_MAX of 1024, APFS has no defined PATH_MAX.
**Fixed Exception:**
```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'ntdll' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment 
at WolvenKit.Core.NativeMethods.RtlAreLongPathsEnabled()
at WolvenKit.CLI.Program.Main(String[] args) in /home/runner/work/WolvenKit/WolvenKit/WolvenKit.CLI/Program.cs:line 32
```
> Fix non-windows platforms trying to load nt.dll for RtlAreLongPathsEnabled

- WolvenKit.CLI/Commands/UncookCommand.cs
- WolvenKit.Modkit/RED4/Tasks/UncookTask.cs
- WolvenKit.Modkit/RED4/Uncook.cs
- Make opus uncooking use the --serialize flag
**Fixed:**
- Opus uncooking didn't use the --serialize flag, it had it's own flag
closes_issue_number
> Make opus uncooking use the --serialize flag

- WolvenKit.App/ViewModels/Scripting/ScriptFileViewModel.cs
- WolvenKit.Modkit/Scripting/ScriptFile.cs
- WolvenKit/Views/Dialogs/ScriptManagerView.xaml
- WolvenKit/Views/Dialogs/ScriptManagerView.xaml.cs
- Added `@description` and `@usage` script file headers. Closes #1936 
Description and Usage blocks are terminated by either a non comment line or the next keyword.
**Example:**
```
// @description
// Line 1 of description
// Line 2 of description
// ...
// Last line of description
// 
// @usage
// Line 1 of usage
// Line 2 of usage
// ...
// Last line of usage
var test = 0;
```
> Scripting: Added `@description` and `@usage` script file headers.

- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
> ProjectExplorer: Fixed issue were parent OnPropertyChanged wasn't called

- WolvenKit.App/ViewModels/Dialogs/ScriptManagerViewModel.cs
> Remove redundant filewatcher in ScriptManagerViewModel

- WolvenKit.App/Factories/PaneViewModelFactory.cs
- WolvenKit.App/ViewModels/Scripting/ScriptFileViewModel.cs
- WolvenKit.App/ViewModels/Tools/LogViewModel.cs
- WolvenKit/Views/Tools/LogView.xaml
- WolvenKit/Views/Tools/LogView.xaml.cs
Closes #1932 
**Ideas:**
- Create a single endpoint (e.g. ScriptFileRepository) to keep track of script files, emit updated scripts, trigger reload w/ filesystem... It could be reused in Script Manager and in Log.
**Old demo**
> Select and run a wscript from Log dock

- WolvenKit.App/Scripting/AppScriptFunctions.cs
- WolvenKit.Common/Services/TweakDBService.cs
In `wkit` module:
- declare `GetRecords`/`GetFlats`/`GetQueries`/`GetGroupTags`
- declare `GetRecord`/`GetFlat`/`GetQuery`/`GetGroupTag`
- declare `HasTDBID`/`GetTDBIDPath`
WIP, it needs testing.
Closes #1942
It should allow this kind of usage:
```javascript
import * as Logger from 'Logger.wscript';
const paths = [...wkit.GetRecords()];
Logger.Info(`Found ${paths.length} records.`);
paths.filter((path) => path === 'Vehicle.v_sport2_mizutani_shion_nomad')
.forEach((path) => {
Logger.Info(`Record of "${path}":`);
const record = JSON.parse(wkit.GetRecord(path));
Info(JSON.stringify(record, undefined, '  '));
});
```
> Add TweakDB API in wscript

- WolvenKit.App/ViewModels/Tools/LogViewModel.cs
- WolvenKit/Views/Tools/LogView.xaml
Shows stop button instead of play button when a script is running.
Closes #1971
> Added button to stop running script in Log view

- WolvenKit.Modkit/Scripting/ScriptService.cs
- Catches exception when script engine interrupts execution.
- Shows a nice log instead of an exception's stacktrace:
> User interrupted execution of script
> Logs a nice message when interrupting a wscript

- WolvenKit.App/ViewModels/Tools/LogViewModel.cs
- WolvenKit/Views/Tools/LogView.xaml
- WolvenKit/Views/Tools/LogView.xaml.cs
- Toggles filter by level.
- Ensures at least one level is on.
- Uses `WolvenKitGreen` color resource (ready for #1954).
Closes #1974
> Added buttons to filter logs by level

- WolvenKit.Modkit/RED4/Uncook.cs
**Fixed:**
- Prevent trying to save materials if there aren't any
> fix(MeshExport): Prevent trying to save materials if there aren't any

- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.CLI/Program.cs
- WolvenKit.Core/CommonFunctions.cs
- WolvenKit.Core/NativeMethods.cs
**Fixed:**
- Fixes problems introduced with df0a03d . Fixes #1989 
**Notes:**
Should be the same bahviour as `RtlAreLongPathsEnabled` does internally
> Linux: Remove call to ntdll completely

- WolvenKit/Views/Templates/RedChunkMaskEditor.xaml.cs
- cleans unused directive
**Fixed:**
- returns an empty string when value is null
Closes #1980
> Fixed exception when ChunkMask value is null

- WolvenKit/Views/Documents/RDTWidgetView.xaml
Canvas will always show widgets content, when loaded. Toggling snap grid option will only affect the visibility of the snap grid pattern.
**Fixed:**
Closes #1999
I'll write another PR to implement snap grid feature:
- pan shall move the grid
- zoom shall scale the grid
- grid pattern should fit the parent's size
> fix(RDTWidgetView): visibility of widgets in canvas

- WolvenKit.App/ViewModels/Documents/RDTWidgetViewModel.cs
- WolvenKit/Views/Documents/RDTWidgetView.xaml
- WolvenKit/Views/Documents/RDTWidgetView.xaml.cs
- Fill parent element with grid pattern.
- Translate grid on pan event.
- Scale grid on wheel event.
- Zoom based on mouse's position.
- Limit zoom between 10% and 400%.
**Work in progress:**
- ~~add 'level scale' on grid itself, maybe with bigger/smaller rules.~~
**Preview:**
> Add snap grid feature in RDTWidgetView

- WolvenKit.Common/WolvenKit.Common.csproj
- WolvenKit.Core/WolvenKit.Core.csproj
- WolvenKit.Modkit/WolvenKit.Modkit.csproj
Could also use `<PackagePath>lib\net8.0</PackagePath>` for dlls placed in the main dir, but won't work for other files (json, so, ...)
Also included `;content`. Only used in (really) old csprojects (before nuget 3.3 was introduced). Not sure if we need to keep it. (Also duplicates these files in the nuget)
`<NoWarn>NU5104</NoWarn>` can be removed as soon as the nuget update is done. Thats just for the prerelease version of SharpGltf we currently use.
Also bumped version so we can release them.
> Fixed nugets not including required files

- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
**Fixed:**
- "Open in new tab" checking wrong property for already opened files
Did check the full path before. Now checks the relative path.
> fix: "Open in new tab" checking wrong property for already opened files

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.Descriptor.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.ExpansionStates.cs
- when updating `CMeshMaterialEntry`'s `name`, the entry node's descriptor will update correctly
- when expanding a `CMaterialinstance`, the `values` array will also expand
> material name: will now update parent display node

- WolvenKit.Modkit/RED4/Tools/Animation/AnimSIMD.cs
**Fixed:**
- Fixed wrong array size for SIMD alligned buffers. Fixes #1137
> fix(AnimExport): Fixed wrong array size for SIMD alligned buffers.

- WolvenKit.Modkit/RED4/Uncook.cs
**Fixed:**
- Due to the updated SharpGLTF behaviour, this is not needed anymore
> Removed tmp extension

- WolvenKit.App/Factories/ChunkViewmodelFactory.cs
- WolvenKit.App/Helpers/ArchiveXlHelper.cs
- WolvenKit.App/Services/ModifierViewStateService.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.ContextMenu.cs
- WolvenKit.Modkit/Resources/ArchiveXlHelper.cs
- WolvenKit/Views/Dialogs/Windows/SearchAndReplaceDialogView.xaml.cs
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
**Fixed:**
- hopefully fixes #2006 - CVM's context menu is now much faster
- dynamic path validation will no longer throw an exception for {material} wildcards in depot paths
> exception fixes and CVM context menu performance

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.ContextMenu.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
by default, duplicating multiple items will now duplicate them right next to the original. Hold SHIFT to append them at the end of selection.
> fixed chunk duplication behaviour in groups (shift key)

- WolvenKit.App/ViewModels/Documents/RedDocumentViewToolbarModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.ContextMenu.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml
- WolvenKit/Views/Tools/RedTreeView.xaml
There will no longer be multiple entries with contextual actions, they will now replace each other
> context menu: show/hide entries based on modifiers

- WolvenKit.App/ViewModels/Documents/RDTDataViewModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.ContextMenu.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit/Views/Dialogs/Windows/ChangeComponentChunkMaskDialog.xaml
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
- WolvenKit/Views/Templates/RedChunkMaskEditor.xaml
- WolvenKit/Views/Templates/RedChunkMaskEditor.xaml.cs
- WolvenKit/Views/Tools/ProjectExplorerView.xaml.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
- chunk mask replacement in app: dialogue will now be easier to navigate
- ctrl+w: Will also close active document if project browser has focus
- fixed "overwrite with selection" not working if a single item had been copied
- duplicate: fixed tooltips
- duplicate: if non-consecutive items are selected, duplication will happen in-place rather than after the last node
> various small UX changes

- WolvenKit.App/ViewModels/Documents/RedDocumentViewToolbarModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml
can now also generate missing chunk materials, thus stopping all those annoying warnings.
> renamed "delete empty submeshes"

- WolvenKit.App/Helpers/UIHelper.cs
- WolvenKit.App/Models/ProjectManagement/Project/Cp77Project.cs
- WolvenKit.App/ViewModels/Dialogs/DeleteOrMoveFilesListDialogViewModel.cs
- WolvenKit.App/ViewModels/Dialogs/ShowBrokenReferences.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.UserInteractionStates.cs
- WolvenKit/Views/Dialogs/Windows/DeleteOrMoveFilesListDialogView.xaml
- WolvenKit/Views/Dialogs/Windows/DeleteOrMoveFilesListDialogView.xaml.cs
- WolvenKit/Views/Dialogs/Windows/ShowBrokenReferencesDialogView.xaml
- WolvenKit/Views/Dialogs/Windows/ShowBrokenReferencesDialogView.xaml.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
- WolvenKit/Views/Shell/MenuBarView.xaml
- WolvenKit/Views/Shell/MenuBarView.xaml.cs
- WolvenKit/Views/Tools/ProjectExplorerView.xaml.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
- Project: Delete empty folders
- Project explorer: Don't save node expansion states while a search is active
- CVM search: supports depot paths for references and type names
- dialogues: should now be clamped to 90% of screen height (e.g. "find unused files")
> Project and appfile actions

- WolvenKit/Views/Tools/ProjectExplorerView.xaml.cs
WKit will ask for a new file name.
- if file name is empty (dialogue cancelled), operation aborts
- if file name is identical, it will create a _copy
> convenience when copying/moving file on itself

- WolvenKit.Modkit/RED4/Tools/MorphTargetImportTools.cs
**Fixed:**
- `POSITION` / `TANGENT` using Vec4 instead of Vec3. Needed due to #2076
Fixes #2094
> Changed morphTarget normal / tangent to Vec3 instead of Vec4.

- WolvenKit.Modkit/RED4/Tools/Animation/Shared.cs
- WolvenKit.Modkit/RED4/Tools/AnimationTools.cs
- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
- WolvenKit.Modkit/RED4/Tools/MorphTargetTools.cs
Needed due to the changed JSON handling in SharpGLTF
> Use CamelCase for JSON data in GLBs

- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit/Themes/App.Styles.xaml
- WolvenKit/Views/Templates/CurveEditorWindow.xaml
- WolvenKit/Views/Templates/CurveEditorWindow.xaml.cs
- remove point's outline
- increase curve's line width, change to white color
- add color resources with `WolvenKitGraph...` name
**Fixed:**
- see [feedback](https://github.com/WolvenKit/WolvenKit/issues/1957#issuecomment-2566686742). Issue in itself is related to the same view but for others, bigger changes (so not closing here).
**Demo:**
Screenshot at 100%. Currently line width (grid + axis + curve) are not responsive, but point's size is. Can a 4K user try it and let me know if it would benefit UI scaling?
> feat(CurveEditor): improve contrast ratio

- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
- WolvenKit/Helpers/LogCodeHelper.cs
> meshtools: better error message for missing bones

- WolvenKit/Views/Templates/RedTypeView.xaml
- WolvenKit/Views/Tools/RedTreeView.xaml
- remove labels of buttons, keep tooltip.
- stick buttons on the right, on top of the row.
- `Open tab` + `Add to project` buttons in `RedTreeView`.
- `Create handle` + `Delete` buttons in `RedTypeView`.
Closes #1991
**Demo:**
> feat(RedTree/RedType): stick buttons on the right

- Directory.Packages.props
- WolvenKit/Initializations.cs
- bump CommunityToolkit.Mvvm to 8.4.0 (was 8.3.2).
- bump Nodify to 6.6.0 (was 6.5.0). v7 introduces breaking changes, ignoring it for now.
- bump Syncfusion to 28.1.37 (was 27.2.2).
**Fixed:**
- UI when opening a ComboBox.
Unless other features are expected, fixing ComboBox was a blocking point to release a new stable version.
> build: bump NuGet packages

- WolvenKit/Views/Tools/ProjectExplorerView.xaml
- add margin to the right to prevent missclick between delete button and scrollbar.
- improve drawing of quick access buttons to be the same on all rows.
**Demo:**
> fix(ProjectExplorer): scrollbar no longer showing ontop of buttons

- WolvenKit.App/Scripting/AppScriptFunctions.cs
- sleep functionality to wscripts
**Fixed:**
- none
not 100% sure that 0x2000 is the correct exception variable but from testing it works fine and the other methods in that same class use it as well
> Added sleep functionality to wscripts

- WolvenKit/Views/Documents/RDTDataView.xaml
- WolvenKit/Views/Templates/RedChunkMaskEditor.xaml
- WolvenKit/Views/Templates/RedRefEditor.xaml
- WolvenKit/Views/Templates/RedRefEditor.xaml.cs
- feat(RedRefEditor): show type name next to flags
**Fixed:**
- fix(RedChunkMaskEditor): revert UI breaking changes
- fix(RDTDataView): horizontal splitter can be moved again
Closes #2124
**Demo:**
> feat: improve UI/UX in RDTDataView and descendants

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit/Converters/TreeViewItemTemplateSelector.cs
- WolvenKit/Views/Templates/RedCurveEditor.xaml
- WolvenKit/Views/Templates/RedCurveEditor.xaml.cs
- WolvenKit/Views/Templates/RedTypeView.xaml
- WolvenKit/Views/Tools/RedTreeView.xaml
[feat(RedTypeView): show quick access button to open curve editor](https://github.com/WolvenKit/WolvenKit/commit/00cb03c6826a98d5512710cd1940d2399784d55c)
- reuse RedCurveEditor in "info top" of RedTypeView when type is a IRedLegacySingleChannelCurve.
- add property ShowQuickAccess in RedCurveEditor to either show current button (default) or quick access button.
[feat(RedTreeView): add quick access to open curve editor](https://github.com/WolvenKit/WolvenKit/commit/57af0afe0eb9d6e8043ef50a3166597bdd1e842a)
- add CurveTemplate selector.
- add icon button next to "curveData" rows to open in curve editor.
Closes #2081
**Demo:**
> feat: add quick access to open curve editor

- WolvenKit.App/Helpers/ImportExportHelper.cs
- WolvenKit.App/Scripting/AppScriptFunctions.cs
- WolvenKit.App/ViewModels/Exporters/ExportViewModel.cs
- WolvenKit.Common/Interfaces/IModTools.cs
- WolvenKit.Modkit/RED4/Uncook.cs
**Fixed:**
- Due to caching of already exported file (Depot only) which was implemented so CLI doesn't export the same files over and over again, it wasn't possible to export the same file (or files which gets placed in the depot) in the GUI multiples times without restarting. This should be fixed now.
**Notes:**
Also added that to wscript as separate function (`wkit.ClearExportFileLookup()`), so the script author can decide if its wanted or not.
> Clear exported file lookup after export operation

- WolvenKit.App/Helpers/ProjectResourceTools.cs
- WolvenKit.sln.DotSettings
Replace in project files will now filter for files that don't need to be checked for replacements (should speed things up)
> replace in project files: better exclusion criteria

- WolvenKit.App/Scripting/AppScriptFunctions.cs
- WolvenKit.App/Services/AppScriptService.cs
- wscripts can now retrieve wolvenkit version via `wkit.Version() -> string`
**Fixed:**
- none
> added function to AppScriptFunctions to allow for wkit version retrieval

- WolvenKit.App/Scripting/AppScriptFunctions.cs
- none
**Fixed:**
- unclear function name
related to pr 2156
> renamed function Version to ProgramVerson in AppScriptFunctions

- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.MeshFunctions.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
- can convert dynamic mesh materials into regular materials
before:
after:
> un-dynamify mesh materials

- WolvenKit/Views/Tools/RedTreeView.xaml.cs
fixes exception when trying to right-click in tweak browser
also fixes the copy commands for single nodes not working (guess our CVM fixes broke that)
> tweak browser: context menu null proofing

- WolvenKit.App/Services/IPluginService.cs
fix plugin manager installing wrong RHT file
**Fixed:**
- fix plugin manager installing wrong RHT file
closes #1479
> fix plugin manager installing wrong RHT file

- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit/Themes/App.Sizes.xaml
- WolvenKit/Views/Tools/LogView.xaml
- WolvenKit/Views/Tools/LogView.xaml.cs
- move "filter by level" buttons in the right panel, vertically, when width is to small to fit filters and script buttons.
- add a minimum width to render the LogView.
- refactor LogView_ event callbacks to be grouped together.
- scaling at 150% is good enough as-is.
Closes #2199
**Demo:**
Scale at 100%
> fix(LogView): improve responsiveness

- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
... as discussed with psi, these aren't needed for CCXL addition apps, so we should be able to ditch them all at once
> Delete partsvalues and overrides

- WolvenKit/Themes/App.Styles.xaml
- WolvenKit/Views/Tools/ProjectExplorerView.xaml
Copy relative path button added in treegridbuttons next to "open in explorer, open file, and delete" buttons as a QoL addition.
Screenshot:
> feat: add copy relative path button in treegrid

- WolvenKit.App/Helpers/ProjectResourceTools.cs
- WolvenKit.App/Scripting/AppScriptFunctions.cs
- Allows iterating over all files under `resources` in wscript (will need this for .xl parsing)
- Allows deleting of files (this will permit cleanup of resources that were added by scripts)
> appscriptfunctions: get resource files

- WolvenKit.App/ViewModels/Documents/RDTDataViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.UserInteractionStates.cs
- Added default count limit parameter to `CalculatePropertiesRecursive`
- Increased limit count for cvm
**Fixed:**
- Broken search within graph trees
Tested against huge scenes such as `base\quest\minor_quests\mq055\scenes\mq055_04_heywood.scene`. Its working kinda of OK.
Id like to add a notification dialog window about unresponsive UI when using search with a "Shift" key held on large files
Before:
After:
> fix: quest and scenes RDTDataViewModel search

- WolvenKit.App/Services/AppScriptService.Hook.cs
- WolvenKit.Common/Services/HookService.cs
- WolvenKit.Common/Services/IHookService.cs
- WolvenKit.Modkit/RED4/RedConverter.cs
- WolvenKit.Modkit/Scripting/ScriptFile.cs
- WolvenKit.Modkit/Scripting/ScriptService.cs
- Added `// @hook_type` (see below)
- Added `// @hook_priority` (see below)
- Changed `// @hook_extension` (see below)
- Allow multiple onSave hooks
**Allowed/Added/Changed WScript metadata:**
- `@hook_type`: `None,Save,Export,PreImport,ImportJson,ParseError` (case-insensitive, no blanks allowed)
- `@hook_extension`: RedEngine file formats for `Save,Export,ImportJson` or import formats for `PreImport` (case-insensitive, no blanks allowed)
- `@hook_priority`: if multiple hook script affect the same action. Higher priority executes first. (default prio is 100)
Closes #2174
> WScript improvements

- WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
**Fixed:**
- incorrect collision shape rotation in sector preview
closes #2238
> fix incorrect collision shape rotation in sector preview

- WolvenKit.App/Helpers/ProjectResourceTools.cs
- WolvenKit.Common/Tools/FileHelper.cs
**Fixed:**
- folder content deletion if the only change was case
- exceptions thrown when renaming due to folders being created twice
- temp folders not being removed when renaming
- skips popup asking for overwrite if source path is new path (to handle only the case changing, as that is a safe operation and doesn't overwrite anything due to temp folders)
- added logging when a single file is renamed to be consistent with folder renaming
- fix folders being incorrectly treated as empty if it only had nested files and none directly in the folder 
closes #2268
> fix incorrect renaming behavior leading to exceptions and data loss

- WolvenKit.App/Interaction/Interactions.cs
- WolvenKit.App/Scripting/AppScriptFunctions.cs
- WolvenKit.App/Scripting/ScriptSettingsDictionary.cs
- WolvenKit/Views/Dialogs/Windows/ScriptSettingsWindow.xaml
- WolvenKit/Views/Dialogs/Windows/ScriptSettingsWindow.xaml.cs
- WolvenKit/Views/Shell/MainView.xaml.cs
- WScript settings
**Notes:**
Currently supports the following types: `int`, `double`, `string`, `bool `, `BigInteger`+ array `[]` variants
**Example:**
```js
import * as Logger from 'Logger.wscript';
var config = {
"myIntVar": 5,
"myIntArrayVar": [6,7,8],
"myDoubleVar": 3.141,
"myDoubleArrayVar": [1.0,2.5,5.9],
"myStringVar": "test",
"myStringArrayVar": ["abc","def","123"],
"myBoolVar": false,
"myBoolArrayVar": [true,false,true,true],
"myBigIntVar": BigInt(5),
"myBigIntArrayVar": [BigInt(5), BigInt(4), BigInt(3)]
}
wkit.ShowSettings(config);
Logger.Info(config)
```
> Added settings to wscript, attempt no. 3

- Tests/WolvenKit.Utility/DumpInfo.cs
- WolvenKit.Common/Services/HashService.cs
- WolvenKit.Common/Services/TweakDBService.cs
- WolvenKit.Core/Helpers/LookupTable.cs
- WolvenKit.RED4/Types/Pools/BasePool.cs
- WolvenKit.RED4/Types/Pools/CNamePool.cs
- WolvenKit.RED4/Types/Pools/NodeRefPool.cs
- WolvenKit.RED4/Types/Pools/ResourcePathPool.cs
- WolvenKit.RED4/Types/Pools/TweakDBIDPool.cs
- WolvenKit.RED4/Types/Primitives/Simples/CName.cs
- WolvenKit.RED4/Types/Primitives/Simples/NodeRef.cs
- WolvenKit.RED4/Types/Primitives/Simples/TweakDBID.cs
**Notes:**
- Replaced native dictionaries with custom SortedList
- Removed forward lookup tables
- Saves round about 550MB RAM in total
> Refactored all (CName, NodeRef, ResourcePath, TweakDBID) pools

- WolvenKit.Common/Model/Arguments/ImportArgs.cs
- WolvenKit.Modkit/RED4/Tools/MeshImportTools.cs
- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
- Import option to disable UV parameter generation. Fixes an engine bug creating a seam
**Fixed:**
- Fixed UV parameter imported with flipped V
- Fixed an issue where GS wasn't exported if only `garmentMeshParamGarment` was present
> GarmentSupport fixes

- Directory.Packages.props
- Tests/WolvenKit.UnitTests/App/Models/ProjectManagement/Project/Cp77ProjectTest.cs
- Tests/WolvenKit.Utility/WolvenKit.Utility.csproj
- WolvenKit.App/Models/ProjectManagement/Project/Cp77Project.cs
- WolvenKit.CLI/Program.cs
- WolvenKit.CLI/Services/MicrosoftLoggerService.cs
- WolvenKit.CLI/WolvenKit.CLI.csproj
- WolvenKit.Core/Enums.cs
- WolvenKit.Core/Interfaces/ILoggerService.cs
- WolvenKit.Core/Services/SerilogWrapper.cs
- WolvenKit.Core/WolvenKit.Core.csproj
- WolvenKit/WolvenKit.csproj
- Custom `LoggerVerbosity` to remove the need of referencing `Microsoft.Build.Framework`
- Replaced `EFCore.BulkExtensions` with `EFCore.BulkExtensions.Sqlite` (Upgrade to EFCore 9.0) 
- Replaced deprecated `ReactiveUI.Events.WPF` with `ReactiveMarbles.ObservableEvents.SourceGenerator`
**Fixed:**
- Build issue introduced with #2098 / 886f03e
Can be squashed
> Nuget update

- WolvenKit.CLI/Commands/ExportCommand.cs
- WolvenKit.CLI/Commands/UncookCommand.cs
- WolvenKit.Modkit/RED4/Tools/Common/MaterialExtractor.cs
- Requiring `--gamepath` for cli export if meshExportArgs.withMaterials is set
**Fixed:**
- StackOverflow while using the material extractor and no archives (or wrong) are loaded
Fixes #2279
> Export fixes

- WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
- Just added some more string replace's, to handle some more cases
> Fix secor preview not working due to illegal characters in node name

- WolvenKit.Modkit/RED4/Tools/RigTools.cs
> mesh tools: unparented bones don't throw an exception anymore

- WolvenKit/Layout/DockStateExtensions.cs
hidden / autohidden would cause an endless refresh loop where the dockState would jump between these two values. Way safer this way.
> prevent endless loop during startup

- WolvenKit.Modkit/RED4/Tools/MorphTargetTools.cs
it's not as if we were using it for anything anyway
> preventing exception for morphtarget export without texture

- WolvenKit.App/ViewModels/Tools/EditorDifficultyLevel/EditorDifficultyLevelFieldFactory.cs
> fixed non-empty default paths (no hiding via editor mode!)

- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
as discussed in wkit-dev last week :)
> cybersearch will no longer insist on spaces before > operator

- WolvenKit/Views/Shell/DockingAdapter.xaml.cs
Occasionally, resetting the project layout will reset in the view being covered in... a lot of windows. We know the bug, it's still there (although rarely). 
This is another attempt at preventing it. We'll see if it works, at least things haven't gotten worse.
> Trying to prevent "reset layout" bug

- WolvenKit.App/ViewModels/GraphEditor/Nodes/Scene/scnSectionNodeWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/RedGraph.Scene.cs
- WolvenKit/Views/GraphEditor/GraphEditorView.xaml.cs
Exposes more useful metadata for events in `scnSectionNode` within the Graph Editor
Section nodes orchestrate animations, dialogue events, VFX, attachments, and other events within a scene so they can get quite complicated. Previously, it was difficult to understand the purpose of a `scnSectionNode` by just looking at it in the graph editor, as it only displayed the raw event type names. This means it takes a lot of time to figure out a scene's flow, especially for larger scenes.
This PR changes `scnSectionNodeWrapper` to extract and display more meaningful metadata for commonly used event types directly within the node's details in the Graph Editor view to improves the usability and readability of scene graphs
Specifically, the following event types now display richer information:
- …
> feat: improve scene graph readability by detailing scnSectionNode events

- WolvenKit.RED4/Archive/IO/CR2WReader.File.cs
- WolvenKit.RED4/Archive/IO/Enums.cs
Without the length check, line 98 will run into an out-of-bounds exception (which results in no cr2w file being returned)
> preventing uncaught index out of bound exception

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.ContextMenu.cs
**Fixed**
- When using "Move to index" command for material entries, the index offset will now correctly be considered
- "Adjust submesh count" will no longer throw an OutOfBounds-exception
> cvm: fixed an exception and an index offset

- WolvenKit.App/Extensions/MeasureExtensions.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit/Views/Exporters/ExportView.xaml
- improve UI of placeholder message when no items are detected in Export Tool
**Fixed:**
- round all dynamic values used to scale UI, all items in Export Tool are now visible even when using Scale UI at 111%
This should likely prevent other weird issues like this one in the future/other parts of the UI when it is scaled.
Closes #2405
**Screenshots:**
> Fix invisible items in Import/Export tools when scaling UI

- WolvenKit.App/ViewModels/Shell/AppViewModel.WScript.cs
Currently File > Import > Import object spawner .json won't reload modified sector files that might be affected by the import script. This change adds the file change detection check after import to prompt users to reload any modified files that are currently open
> fix(AppViewModel): fix refresh behavior for object spawner JSON imports

- WolvenKit.Modkit/RED4/Tools/Common/Structs.cs
- WolvenKit.Modkit/RED4/Tools/MeshImportTools.cs
- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
**Fixed:**
- Importing a glb with ShapeKeys now checks if it is named "GarmentSupport" before importing it as GarmentSupport
> Fixed importing meshes with ShapeKeys/MorphTargets

- WolvenKit.App/Helpers/InkatlasImageGenerator.cs
- WolvenKit.App/Models/ProjectManagement/Project/Cp77Project.cs
- WolvenKit.App/ViewModels/Dialogs/AddInkatlasDialogViewModel.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewToolbarModel.cs
- WolvenKit.Core/Extensions/StringExtensions.cs
- WolvenKit/Views/Dialogs/Windows/AddInkatlasDialog.xaml
- WolvenKit/Views/Dialogs/Windows/AddInkatlasDialog.xaml.cs
- WolvenKit/Views/Templates/FilterableDropdownMenu.xaml
- WolvenKit/Views/Templates/FilterableDropdownMenu.xaml.cs
- Some UI improvements (inkatlas folder path doesn't look like two different fields anymore)
- everything will be forced to lowercase in the backend
- if you import a single png, the inkatlas part will always be named `icon`
> inkatlas dialog: more improvements

- WolvenKit.Modkit/RED4/Tools/Common/MaterialExtractor.cs
Will be run on first setup and each time Wolvenkit opens. Warnings will be displayed if depot path folder doesn't exist, or if it's inside appdata.
closes #2391
> Warn if depot path is in appdata

- WolvenKit.RED4/Archive/IO/PreProcessor/entEntityTemplatePreProcessor.cs
Fixes #2448 
Adds a null check to safely handle uninitialized `Components` , allowing new `.ent` files to be created
> fix: prevent crash when creating new .ent files

- WolvenKit.App/Helpers/CollectionViewHelper.cs
- WolvenKit.App/ViewModels/Documents/QuestPhaseGraphViewModel.cs
- WolvenKit.App/ViewModels/Documents/QuestPhaseTabDefinition.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewModel.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/Internal/BaseQuestViewModel.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/Internal/QuestConnectionViewModel.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questPhaseNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/RedGraph.Quest.cs
- WolvenKit.App/ViewModels/GraphEditor/RedGraph.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit/Converters/RedTypeToChunkViewModelCollectionConverter.cs
- WolvenKit/Views/Documents/QuestPhaseGraphView.xaml
- WolvenKit/Views/Documents/QuestPhaseGraphView.xaml.cs
- WolvenKit/Views/Documents/RedDocumentView.xaml
- WolvenKit/Views/GraphEditor/GraphEditorView.xaml.cs
Follow on from #2444 - this PR adds a similar interface for editing .questphase files
I'm using most of the same converters, helpers, and overall architecture I used for the Scene Editor so the realtime sync, tabs, node styling work out of the box. The questphase resource is also a bit simpler so there are only two tabs: Node Properties and Phase Resources
One additional thing that had to be accounted is nested graphs via Phase node: I've rearranged the existing breadcrumb view but all existing functionality is mostly drop in (double click to open Phase node etc). But double clicking a Scene node will now show a popup redirecting you to the Scene Editor (and will no longer open the scene graph in the Quest Editor)
I've also worked on the node selection logic a bit to ensure we clear a …
> feat: add quest editor

- WolvenKit.App/Helpers/CvmDropdownHelper.cs
- WolvenKit.App/Helpers/DocumentTools.cs
- WolvenKit/Views/Templates/FilterableDropdownRedstringMenu.xaml
- WolvenKit/Views/Templates/FilterableDropdownRedstringMenu.xaml.cs
- Refactored DocumentTools to only process and cache journal entries IDs when a filter is provided, removing unnecessary logic for unfiltered cases.
- Improved FilterableDropdownRedstringMenu to provide more responsive filtering for journal entries.
- Updated CvmDropdownHelper to support the new filtering behavior.
> updated dropdown for journal entries

- WolvenKit.App/Helpers/CollectionViewHelper.cs
- WolvenKit.App/ViewModels/Documents/QuestPhaseGraphViewModel.cs
- WolvenKit.App/ViewModels/Documents/QuestPhaseTabDefinition.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewModel.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/Internal/BaseQuestViewModel.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/Internal/QuestConnectionViewModel.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questPhaseNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/RedGraph.Quest.cs
- WolvenKit.App/ViewModels/GraphEditor/RedGraph.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit/Converters/RedTypeToChunkViewModelCollectionConverter.cs
- WolvenKit/Views/Documents/QuestPhaseGraphView.xaml
- WolvenKit/Views/Documents/QuestPhaseGraphView.xaml.cs
- WolvenKit/Views/Documents/RedDocumentView.xaml
- WolvenKit/Views/GraphEditor/GraphEditorView.xaml.cs
Follow on from #2444 - this PR adds a similar interface for editing .questphase files
I'm using most of the same converters, helpers, and overall architecture I used for the Scene Editor so the realtime sync, tabs, node styling work out of the box. The questphase resource is also a bit simpler so there are only two tabs: Node Properties and Phase Resources
One additional thing that had to be accounted is nested graphs via Phase node: I've rearranged the existing breadcrumb view but all existing functionality is mostly drop in (double click to open Phase node etc). But double clicking a Scene node will now show a popup redirecting you to the Scene Editor (and will no longer open the scene graph in the Quest Editor)
I've also worked on the node selection logic a bit to ensure we clear a …
> feat: improve quest editor

- WolvenKit.App/ViewModels/Dialogs/NewFileViewModel.cs
Fixed: remove redundant "archive" in extension of ArchiveXL files
> fix: remove redundant archive extension

- WolvenKit.Modkit/Resources/ArchiveXlHelper.cs
- WolvenKit.sln.DotSettings
- WolvenKit/Views/Templates/RedRefEditor.xaml
- WolvenKit/Views/Templates/RedRefEditor.xaml.cs
- WolvenKit/Views/Templates/TrimmingTextBox.xaml
- WolvenKit/Views/Templates/TrimmingTextBox.xaml.cs
Context menu entry will display based on conditional check if the string could support it (check when opening context menu)
> ResourceRef context menu: Add/Remove dynamic substitution

- WolvenKit.App/Helpers/DocumentTools.cs
CVM dropdown for material propertie names will now be correctly be populated, even if there are a bunch of .mi files in the way
> CVM material properties: follow mi chain

- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/Internal/BaseQuestViewModel.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Scene/Internal/BaseSceneViewModel.cs
**Fixed:**
Removed unnecessary Data property change notifications from both RefreshFromData() methods for scene and quest nodes which was causing the whole node property tree to lose its expansion states while editing a node property
This is unnecessary because individual ChunkViewModels already handle their own property changes through data binding so sync between the panel <> graph is unaffected
> fix: prevent quest/scene node tree collapse when editing properties

- WolvenKit.App/Controllers/RED4Controller.cs
- WolvenKit.CLI/Commands/BuildCommand.cs
- WolvenKit.CLI/Program.cs
- WolvenKit.Common/Interfaces/IModTools.cs
- WolvenKit.Modkit/RED4/Build.cs
- WolvenKit.Modkit/RED4/ModTools.cs
- WolvenKit.Modkit/RED4/Tasks/BuildTask.cs
- WolvenKit.Modkit/RED4/Tasks/IConsoleFunctions.cs
- `build <path1> <pathN>` command in `WolvenKit.CLI`. It builds a WKit project like the button "Build Project" of the application.
- implementation is derived from [RED4Controller](https://github.com/WolvenKit/WolvenKit/blob/e81cbad020ddf085bd0b50a844aabd1a4ffcc2e8/WolvenKit.App/Controllers/RED4Controller.cs#L467).
- it doesn't support REDmod content: can be implemented later when requested by a user.
- it doesn't create a `.zip` file: can be implemented later with an option like `--zip`.
> feat(CLI): add build command

- WolvenKit.App/ViewModels/GraphEditor/Nodes/NodeProperties.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/Internal/QuestConditionHelper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questConditionNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questPauseConditionNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Scene/scnQuestNodeWrapper.cs
Clean up and improved on the stuff I slightly broke for node details (that resulted in duplicate details and not very readable) for nodes that have a condition type like PauseCondition 
Condition types will now have semantic description, few examples:
Tried to cover all the most common condition types, but not all - they will fallback to the default list detail
> feat: add semantic details for condition types for quest/scene nodes

- WolvenKit.App/Services/NodePropertiesSelectionService.cs
- WolvenKit.App/Services/NodeSelectionService.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit/Converters/RedTypeToChunkViewModelCollectionConverter.cs
**Fixed:**
Successive duplication of array items in a node in scene/quest editor breaks NodeSelectionService, causing property panel to get stuck displaying the selected node
This was because of stale CVM cache in RedTypeToChunkViewModelCollectionConverter. Fixed by adding cache invalidation in ChunkViewModel.DuplicateChunk() for graph editor contexts only
> fix: add cache invalidation to prevent node selection from breaking

- WolvenKit.App/ViewModels/GraphEditor/Nodes/NodeProperties.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/Internal/QuestConditionHelper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questCheckpointNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questConditionNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questOutputNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questPauseConditionNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questPhaseNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questRandomizerNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questSceneNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questSwitchNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Scene/scnEndNodeWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Scene/scnQuestNodeWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Scene/scnRandomizerNodeWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Scene/scnSectionNodeWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Scene/scnStartNodeWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/RedGraph.Scene.cs
- WolvenKit.App/ViewModels/GraphEditor/RedGraph.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit/Views/GraphEditor/GraphEditorView.xaml
- WolvenKit/Views/GraphEditor/GraphEditorView.xaml.cs
- Fixed randomizer node sync (for both questphase and scene) - adding sockets and changing weights should now sync up properly in the graph in realtime
- Adding new start and end nodes in a scene should now properly sync up in the 'Logic & Flow' tab including editing the names from the graph
- Fixed an issue where adding new choice node in larger scenes took a lot of time
- Fixed a bug where dragging a connection to a scnSectionNode with an unspecified socket would create an empty events output socket
- Fixed a bug where semantic details for condition node types in questphase were getting polluted after editing
- Fixed a bug that prevented scnSectionNode from getting the notable point label in graph view
- Added TimePeriod to semantic details for condition 
- Added a "Add Case" …
> scene and questphase QoL fixes

- WolvenKit.App/Services/AppScriptService.cs
- WolvenKit.App/ViewModels/Tools/PropertiesViewModel.cs
- WolvenKit.CLI/Program.cs
- WolvenKit.Common/Services/CRUIDService.cs
- WolvenKit.Common/Services/HashService.cs
- WolvenKit.Core/Services/IHashService.cs
- WolvenKit/App.xaml.cs
- asynchronously load hashes (saves ~5 000 ms)
- asynchronously load CRUIDs (saves ~500 ms)
- asynchronously refresh UI scripts (saves ~500 ms)
Tool: dotTrace with timeline profile (+ profile build).
Scenario: timing from the launch to [First Contentful Paint](https://web.dev/articles/fcp) (when Main View is rendered and user can interact).
Elapsed time before: ~20 000 ms
Elapsed time after: ~10 000 ms
Overall improvement: ~50 %
A major remaining bottle neck is during `WolvenKit.Views.Shell.DockingAdapter.PART_DockingManager_Loaded` which calls `LoadDockState` of Syncfusion's `DockingManager`. It takes ~5 000 ms to process and layout the dock. So far I couldn't find an easy fix, while still rendering the dock when no project is open.
FileIcon …
> perf: improve loading time at startup

- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
Path was treated as rooted due to leading slash
> fixed "find unused files" in .app

- WolvenKit.App/Controllers/RED4Controller.cs
- WolvenKit.App/Models/ProjectManagement/Project/Cp77Project.cs
Reduces clutter in wkit projects
> Run "DeleteEmptyFolders" on project before packing

- WolvenKit.App/Models/ProjectManagement/Project/Cp77Project.cs
- WolvenKit.sln.DotSettings
```c#
private static readonly List<string> s_allowedDeadReferencePartials =
[
// in psiberx we trust
@"archive_xl\characters\common",
@"archive_xl\characters\head\player_base_heads",
@"archive_xl\common\null.morphtarget",
// xbae's photo mode anims - will do nothing if not present
@"base\animations\xbaebsae\pm_facials",
// CDPR originals - they have them in all of their NPCS, surely it'll be fine to just ignore them
@"base\fx\characters\npc\kerenzikov",
@"base\animations\anim_motion_database\cover_action.csv",
@"ep1\animations\npc\gameplay\woman_average\gang\unarmed\wa_gang_unarmed_reaction_death.anims",
];
```
> Find broken references: ignore cdpr and axl files

- WolvenKit/App.xaml
**Fixed:**
- keep black text color (default) to provide an accessible contrast ratio.
Regression introduced after upgrading Syncfusion to v30+ (see #2565).
Before:
After:
> fix: text contrast ratio of MenuItem.ToolTip

- WolvenKit.App/ViewModels/Importers/ImportViewModel.cs
**Fixed:**
- importing a batch of .gltf / .glb files with meshes and morphtargets would fail. Process uses parallelism which lead to concurrent access of files due to dependency between mesh/morphtarget.
Implementation can be easily updated in the future to account for new conflicts / order of processing based on file's extension and data type.
Closes #2343
> fix(ImportViewModel): prevent concurrent file access errors when importing meshes/morphtargets

- WolvenKit.App/ViewModels/HomePage/HomePageViewModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit/Converters/LessThanConverter.cs
- WolvenKit/Themes/App.Sizes.xaml
- WolvenKit/Views/HomePage/HomePageView.xaml
- WolvenKit/Views/HomePage/Pages/WelcomePageView.xaml
- docs/CONTRIBUTING.md
- add `LessThanConverter` to be used as breakpoint
- move filter/dropdown in a 2nd row when left column (Projects) reach a threshold
- add minimum width on left column (Projects)
- add vertical scrollbar on the entire view
- uniformize view's margin, with static sizes
**Fixed:**
- fix layout to fit version number in the left panel (for nightly releases)
Closes #2627
**Screenshot:**
> feat(WelcomePageView): improve layout and responsiveness

- WolvenKit/Views/Tools/ProjectExplorerView.xaml
Small QoL: show 'Open in MlSetupBuilder' option only for mlsetup files. It currently shows for all files on right click (but greyed out). PR just adds a Visibilty binding for the menu item so it shows up only for supported files
> add Visibility binding for Mlsetup item

- WolvenKit.Modkit/RED4/Tools/MeshImportTools.cs
**Fixed:**
- fixes lodLevelInfo being reset to default values when importing 
closes #2587 
Only thing I am unsure of is whether to use scaling like in the pr (2x the previous stage, like it is for many meshes) or whether to use the fixed step (+3).
For the default values (lod 1 = 3) it ends up with a very similar result (0 3 6 12) instead of (0 3 6 9) when using scaling, but provides a far more intuitive UX when the mesh had custom values (e.g. 0 15 30) and then you add a new one it'll be 60 with scaling instead of 33.
> Fix incorrect lodlevelinfo on import

- WolvenKit.App/Helpers/CvmDropdownHelper.cs
- WolvenKit.App/Interaction/Interactions.cs
- WolvenKit.App/ViewModels/Dialogs/SceneInputDialogViewModel.cs
- WolvenKit.App/ViewModels/Documents/SceneGraphViewModel.cs
- WolvenKit.RED4/Types/ClassesExt/scnSceneResource.cs
- WolvenKit/Views/Dialogs/SceneInputDialogView.xaml
- WolvenKit/Views/Dialogs/SceneInputDialogView.xaml.cs
- WolvenKit/Views/Documents/SceneGraphView.xaml
- WolvenKit/Views/Tools/ProjectExplorerView.xaml.cs
PR adds a button bar to the Scene Editor that will allow users to create commonly used scene properties easily.
Currently adding new entries for scene properties like an actor or dialogue requires:
- Knowing how the ids for each type of property is calculated. For eg actors have performer ids that are 256 increments, but a prop's performer id is in 256+2 increments. This gets really annoying as a scene grows beyond the first couple of entries and having to note and remember the formulas without mistakes
- Tasks that are mentally atomic in nature like "create an actor" actually mean adding entries in multiple places (for actors, this means appending in `actors` and in `debugSymbols` for example) so again error prone
Note that - there are no workflow changes for editing and …
> feat: add scene editor button bar

- WolvenKit.App/ViewModels/GraphEditor/Nodes/NodeProperties.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questTeleportPuppetNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questUseWorkspotNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Scene/scnInterruptManagerNodeWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Scene/scnQuestNodeWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Scene/scnSectionNodeWrapper.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.Descriptor.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.Value.cs
- WolvenKit.RED4/Types/ClassesExt/scnSceneResource.cs
Add better node details for Section events and Workspot nodes
- Add details for more Section event details (VFX duration, look at advanced, camera param, pose correction)
- Add proper details for workspot nodes
- Modify details shown in the "Dialogue" tab for .scene > screeplayStore -> lines/options to show itemId instead of animation names
- Add details for interrupt manager node
> feat: more quest/scene node details

- WolvenKit.RED4/Types/ClassesExt/questQuestPhaseResource.cs
**Fixed:**
Ensure graph is initialized on creation of a new questphase file (following the same pattern of scene files)
> fix: initialize graph for questphase on creation

- WolvenKit.App/ViewModels/GraphEditor/Nodes/Scene/scnSectionNodeWrapper.cs
**Fixed:**
prefer en-us locale for dialogLine event detail in scene graph
> fix: prefer en-us for dialogLine event detail

- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.Value.cs
**Fixed:**
Handle null graph connection references. Fixes #2686
> fix: handle null graph connection references

- WolvenKit/Views/Dialogs/SceneInputDialogView.xaml
- WolvenKit/Views/Documents/SceneGraphView.xaml
- add UI scaling for the toolbar of the SceneGraph view
- improve layout of SceneInputDialog and UI scaling
Follow up to #2667
**Screenshots:**
At 100%:
At 150%:
> feat: improve UI of Scene Graph and its dialog

- WolvenKit/Views/Tools/ProjectExplorerView.xaml
**Fixed:**
- font was not scaling in hierarchical tree and flat tree
At 100%:
At 150%:
> fix(ProjectExplorer): font scaling in hierarchical tree and flat tree

- WolvenKit.App/Helpers/CvmDropdownHelper.cs
- WolvenKit/Views/Documents/QuestPhaseGraphView.xaml.cs
**Fixed:**
Fixes a bug where itemId is not editable in screenplay store for dialogue and options
I overlooked this in commit `72faa9e` which added dropdown support for dialogues/options. Refactored `IsInDefinitionContext` to accept parent type as a parameter, so it can specifically identify when we're checking scnscreenplayItemId (make it editable in definition context) vs scnActorId (keep dropdowns working for speaker/addressee fields) in the same place - as it used to be before
> fix: make itemId editable in Dialogue tab 
