WolvenKit/WolvenKit

- W3Edit/frmMain.cs
Pushed to the wrong branch :unamused:
> Fix embededfiles showing when it shouldnt

- .gitignore
- W3Edit/frmStringsGui.Designer.cs
- W3Edit/frmStringsGui.cs
- W3Edit/frmStringsGui.resx
Added proper generation of nested group names.
> Strings encoder gui

- WolvenKit.Render/WolvenKit.Render.csproj
- WolvenKit.Render/frmRender.cs
- WolvenKit/frmMain.cs
Extracted textures should be in the same folder as w2mesh.
> Renderer now supports textures!

- WolvenKit/frmAssetBrowser.cs
Repro for the bug this PR closes:
1. Open asset browser
2. Right click on any folder, select Mark all files of folder
3. Press Add marked files to mod
4. NullReferenceException
Remaining problems after this commit:
- No ImageKey defined for files marked using "Mark all files of folder".
I'd recommend refactoring it to the WitcherListViewItem constructor.
- Duplicates in the ViewList still can happen
You can contact me on discord Jicksaw#2630 or the w3 modding channel.
> Fix NullReferenceException in get_ExplorerPath()

- WolvenKit.CR2W/CR2WReaderExtensions.cs
- WolvenKit.CR2W/Types/CR2WTypeManager.cs
- WolvenKit.CR2W/Types/CSectorData.cs
- WolvenKit.CR2W/WolvenKit.CR2W.csproj
CSectorData bytes are now read properly, which allows for very basic editing.
> Added CSectorData support.

- WolvenKit.CR2W/Editors/IdTagEditor.Designer.cs
- WolvenKit.CR2W/Editors/IdTagEditor.cs
- WolvenKit.CR2W/Editors/IdTagEditor.resx
- WolvenKit.CR2W/Types/CR2WTypeManager.cs
- WolvenKit.CR2W/Types/IdTag.cs
- WolvenKit.CR2W/WolvenKit.CR2W.csproj
IdTag is now read properly as a byte and guid and has a new editor.
> Added IdTag Variable Support

- CONTRIBUTING.md
Implemented:
Fixed:
- <Fixes>
<Aditional notes>
> Expanded contributing guidelines.

- PULL_REQUEST_TEMPLATE.md
- README.md
Implemented:
- None
Fixed:
- Typos in README
- Typo in PR template
> Fixed some typos #70

- WolvenKit.CR2W/Types/CDateTime.cs
- WolvenKit/Forms/frmMain.cs
- WolvenKit/MainController.cs
> -4 warnings

- CONTRIBUTING.md
- README.md
- WolvenKit.Render/TargaImage.cs
- WolvenKit/Forms/frmInstallPackage.cs
- WolvenKit/Forms/frmLoading.cs
- WolvenKit/Forms/frmMain.cs
- WolvenKit/Forms/frmSettings.cs
Implemented:
- Reviewed exception messages, MessageBox method calls, and .md files for typos.
Fixed:
- Updated typos
> Fix typos in Exceptions, MessageBox, and *.md files

- WolvenKit/Forms/frmMain.Designer.cs
- WolvenKit/Forms/frmMain.cs
Implemented:
- Added new startup option to just pack and run the game.
- Fixed typo in second row
Fixed:
#110
> Add new startup option to just pack and run the game.

- WolvenKit.Cache/CollisionCache/CollisionCacheItem.cs
- WolvenKit.Cache/CollisionCache/Collision_Cache.cs
Fixed:
- fixed multiple bugs with collision cache parsing and extraction
> Collision Cache bugfix

- WolvenKit.Common/Services/ILoggerService.cs
- WolvenKit.Common/Services/LoggerService.cs
- WolvenKit.Common/Services/LoggerTypes.cs
- WolvenKit.Common/Wcc/wcc_commands.cs
- WolvenKit.Common/Wcc/wcc_task.cs
- WolvenKit/Forms/frmAssetBrowser.cs
- WolvenKit/Forms/frmCreateInstaller.cs
- WolvenKit/Forms/frmMain.cs
- WolvenKit/Forms/frmOutput.cs
- WolvenKit/MainController.cs
Implemented:
- added clourful log messages to wcc
Fixed:
- fixed a bug where buildcache command would not work
- fixed wcc async task calls
> Hotfix and tasks

- WolvenKit.CR2W/CR2W/CR2WReaderExtensions.cs
- WolvenKit.CR2W/Types/Basic/CVector3.cs
- WolvenKit.CR2W/Types/W3/ISerializable/IScriptable/CObject/CResource/ITexture/CBitmapTexture.cs
- WolvenKit.CR2W/WolvenKit.CR2W.csproj
- WolvenKit.Cache/DDS/DDSUtils.cs
- WolvenKit.Cache/ImageUtility.cs
- WolvenKit/Forms/frmCR2WDocument.cs
- WolvenKit/Forms/frmChunkList.cs
- WolvenKit/Forms/frmImagePreview.cs
- WolvenKit/Forms/frmMain.cs
- WolvenKit/Forms/frmTextureFile.Designer.cs
- WolvenKit/Forms/frmTextureFile.cs
DDS writing bugfix
Fixed:
- fixed a bug where non-cubic dds would get written incorrectly
> DDS writing bugfix

- WolvenKit.Render/frmRender.cs
Fix to texture path in render
Fixed:
texture path could wrongly point to non existing dir
> Fixed texture path bug.

- WolvenKit.CR2W/CR2W/CR2WExport.cs
- WolvenKit.CR2W/CR2W/CR2WFile.cs
- WolvenKit/Forms/frmImportUtility.cs
Fixed:
- fixed a bug where the import utility would truncate filenames ending with t,g or a... lol
- fixed a critical bug where class types wouldn't be updated on file write
> bugfixes for import and cr2w

- WolvenKit.CR2W/CR2W/CR2WExport.cs
- WolvenKit.CR2W/Types/Utils/CR2WTypeManager.cs
- WolvenKit.CR2W/Types/W3/ISerializable/IScriptable/CObject/CNode/CEntity.cs
- WolvenKit/Forms/frmChunkList.cs
- WolvenKit/Forms/frmChunkProperties.Designer.cs
- WolvenKit/Forms/frmMain.cs
- WolvenKit/Forms/frmScriptEditor.cs
Implemented:
- added custom class cr2w support
- added a cancel option to exiting the mainform
Fixed:
- fixed a bug with CEntity Buffer writing
> Feature custom classes

- .github/workflows/Nightly.yml
> Fixed nightly-build, dependency was bugged.

- WolvenKit.App/ViewModels/MainViewModel.cs
- WolvenKit.App/ViewModels/ModExplorerViewModel.cs
- WolvenKit.Common/Model/W3Mod.cs
- WolvenKit/Forms/MVVM/frmMain.cs
- WolvenKit/Forms/MVVM/frmModExplorer.cs
- WolvenKit/Forms/UserControl/frmPackSettings.Designer.cs
- WolvenKit/Forms/UserControl/frmPackSettings.cs
- WolvenKit/Forms/frmScriptEditor.Designer.cs
- WolvenKit/Forms/frmScriptEditor.cs
- WolvenKit/Forms/frmScriptEditor.resx
Fixed:
- fixed a critical bug where text files would be encoded wrongly
- additional checks for mod packing
- better pack settings check
- some QoL UI changes
> Bugfix 0.6.2 

- Wolvekit.Nvidia/Properties/AssemblyInfo.cs
- WolvenKit.Bundles/BundleManager.cs
- WolvenKit.Bundles/Properties/AssemblyInfo.cs
- WolvenKit.CR2W/Properties/AssemblyInfo.cs
- WolvenKit.Cache/Properties/AssemblyInfo.cs
- WolvenKit.Common/Properties/AssemblyInfo.cs
- WolvenKit.Net/Properties/AssemblyInfo.cs
- WolvenKit.Scaleform/Properties/AssemblyInfo.cs
- WolvenKit.W3Speech/Properties/AssemblyInfo.cs
- WolvenKit.W3Strings/Properties/AssemblyInfo.cs
- WolvenKit.Wwise/Properties/AssemblyInfo.cs
- WolvenKit/Forms/MVVM/frmMain.cs
- WolvenKit/Properties/AssemblyInfo.cs
version update and critical bug
Implemented:
- updated version 0.6.1 --> 0.7
Fixed:
- fixed a bug where the bundle manager would expect a file path instead of a directory path
> version update and critical bug

- .github/workflows/Nightly.yml
replace choco + 7zip with powershell built-in
the bin dir changed with latest target fix (full x64), mb
> nightly hotfix

- .github/workflows/Nightly.yml
> nightly hotfix v2

- WolvenKit.App/Controllers/MainController.cs
- WolvenKit.Common/Model/Cr2wResourceManager.cs
- WolvenKit.Wwise/SoundCache/SoundManager.cs
- WolvenKit.Wwise/SoundCache/Sound_Cache.cs
- WolvenKit/Forms/MVVM/frmMain.cs
- WolvenKit/Program.cs
Implemented:
- open cr2w files with WolvenKit in Explorer
#235
> open cr2w files with WolvenKit in Explorer

- WolvenKit/Forms/MVVM/frmMain.cs
Please squash and delete commit messages :octopus:
> Zemmfmistery

- WolvenKit.App/Model/Arguments/RequestEmbeddedFileOpenArgs.cs
- WolvenKit.App/ViewModels/Documents/CR2WDocumentViewModel.cs
- WolvenKit.App/ViewModels/MainViewModel.cs
- WolvenKit/Forms/Editors/ByteArrayEditor.cs
- WolvenKit/Forms/MVVM/frmCR2WDocument.cs
- WolvenKit/Forms/frmAssetBrowser.cs
- WolvenKit/Forms/frmChunkProperties.cs
- WolvenKit/UIController.cs
- WolvenKit/Utility/EditorHandler.cs
Implemented:
- subsumed opening byte arrays under a cr2w document
Fixed:
- fixed a bug where saving all documents would not work
> nested bytearray windows

- WolvenKit.App/ViewModels/ImportViewModel.cs
- WolvenKit.CR2W/CR2W/CR2WExport.cs
- WolvenKit.CR2W/Types/Generic/CHandle.cs
- WolvenKit/Forms/MVVM/frmMain_FileSystemWatcher.cs
- WolvenKit/Forms/MVVM/frmModExplorer.Designer.cs
- WolvenKit/Forms/MVVM/frmModExplorer.cs
Implemented:
- some minor refactoring: using IChunkPtrAccessor instead of CVariable
Fixed:
- fixed a bug where the project explorer would not update after copying a file
#246
> Project explorer bugfix

- WolvenKit.CR2W/CR2W/CR2WCopyAction.cs
- WolvenKit.CR2W/CR2W/CR2WFile.cs
- WolvenKit/Forms/frmChunkProperties.cs
Note that Ding's work on anims needs to adapt, I did not handle it.
Chunk creation likely to be broken there, check `CR2WFile.CreateChunk`.
> addnewchunkfor minor fix

- WolvenKit.CR2W/CR2W/CR2WExport.cs
- WolvenKit.CR2W/Types/Generic/Arrays/CArrayBase.cs
- WolvenKit.CR2W/Types/Generic/CHandle.cs
- WolvenKit.CR2W/Types/Generic/CPtr.cs
- WolvenKit.CR2W/Types/Utils/CVariable.cs
- WolvenKit.CR2W/Types/Utils/CVariantSizeNameType.cs
- WolvenKit/Forms/frmChunkProperties.cs
> minor chandle virtual parent soft mount fix (w2w...)

- WolvenKit.CR2W/CR2W/CR2WFile.cs
- WolvenKit.CR2W/CR2W/CR2WFileHelpers.cs
Fixed:
- fixed a bug where creating a new cr2w file would crash
> new cr2w file fix

- WolvenKit.Irrlicht/source/COBJMeshWriter.cpp
- WolvenKit.Irrlicht/source/CSceneManagerWolvenKit.cpp
- WolvenKit.Irrlicht/source/CTerrainSceneNodeWolvenKit.cpp
- WolvenKit.Irrlicht/source/CW3EntLoader.cpp
- WolvenKit.Irrlicht/source/CW3EntLoader.h
- WolvenKit.Render/frmLevelScene.Designer.cs
- WolvenKit.Render/frmLevelScene.cs
> speed improvements and export fixes

- WolvenKit.Common/Model/WitcherArchiveManager.cs
- WolvenKit/Forms/MVVM/frmCR2WDocument.cs
- WolvenKit/Forms/MVVM/frmMain.cs
Fixed:
- fixed a bug where pngs and jpgs would get extracted to Uncooked instead of Cooked folder
- fixed a bug where selecting chunks woudld not update the texture preview
- fixed a bug where the managers would not display correct Root Node
> Image fixes

- WolvenKit.CR2W/Types/Utils/CVariable.cs
- WolvenKit/Forms/MVVM/frmMain.Designer.cs
- WolvenKit/Forms/MVVM/frmMain.cs
Implemented:
- added some preview overrides for the chunk property view
Fixed:
- fixed a bug where disabling the welcome form would prevent themeing
- disable script editor placeholder menu
> Preview fixes

- WolvenKit.App/ViewModels/Documents/CR2WDocumentViewModel.cs
- WolvenKit.CR2W/CR2W/CR2WCopyAction.cs
- WolvenKit.CR2W/CR2W/CR2WFile.cs
- WolvenKit/Forms/frmChunkProperties.cs
Various fixes : copy-in-place and copy-insert now updates components, copy-in-place works :)
> Chunk ops : copy in-place fix

- WolvenKit.App/ViewModels/Documents/CR2WDocumentViewModel.cs
- WolvenKit.App/ViewModels/Documents/CommonDocumentViewModel.cs
- WolvenKit.CR2W/Types/Primitive/NetPrimitive/CByteArray2.cs
- WolvenKit.Common/Services/IWindowFactory.cs
- WolvenKit.Common/WolvenKit.Common.csproj
- WolvenKit/Forms/MVVM/frmCR2WDocument.cs
- WolvenKit/Forms/MVVM/frmMain.cs
- WolvenKit/Forms/frmChunkList.Designer.cs
- WolvenKit/Forms/frmChunkList.cs
- WolvenKit/Forms/frmChunkProperties.cs
- WolvenKit/Utility/ProductionWindowFactory.cs
- WolvenKit/WolvenKit.csproj
Implemented:
- added high-level chunk adding to the chunk list view
Fixed:
- fixed a bug where updating properties would reset the chunk list view
> visual chunk adding

- WolvenKit.App/Controllers/MainController.cs
- WolvenKit.App/ViewModels/Documents/CR2WDocumentViewModel.cs
- WolvenKit.App/ViewModels/Documents/ScriptDocumentViewModel.cs
- WolvenKit.App/ViewModels/MainViewModel.cs
- WolvenKit.CR2W/CR2W/CR2WFile.cs
- WolvenKit.CR2W/CR2WManager.cs
- WolvenKit.CR2W/Reflection/AssemblyDictionary.cs
- WolvenKit.CR2W/Types/BufferedTypes/Complex/CQuestScriptBlock.cs
- WolvenKit.CR2W/Types/Interfaces.cs
- WolvenKit.CR2W/Types/Primitive/CVariant.cs
- WolvenKit.CR2W/Types/Primitive/NetPrimitive/CFloat.cs
- WolvenKit.CR2W/Types/Utils/CVariable.cs
- WolvenKit.CR2W/Types/Utils/CVariantSizeNameType.cs
- WolvenKit.CR2W/Types/Utils/CVariantSizeType.cs
- WolvenKit.CR2W/Types/Utils/CVariantSizeTypeName.cs
- WolvenKit.Common/Services/IWindowFactory.cs
- WolvenKit.Common/Tools/CSharpCompilerTools.cs
- WolvenKit/Forms/Dialog/frmExtractAmbigious.cs
- WolvenKit/Forms/MVVM/frmCR2WDocument.cs
- WolvenKit/Forms/MVVM/frmMain.cs
- WolvenKit/Forms/MVVM/frmModExplorer.cs
- WolvenKit/Forms/UserControl/frmPackSettings.cs
- WolvenKit/Forms/frmChunkList.cs
- WolvenKit/Forms/frmChunkProperties.cs
- WolvenKit/Utility/ProductionWindowFactory.cs
Implemented:
Fixed:
- fixed a bug where Cvariants were not editable
- fixed a bug where dds files in texturecache would go into Cooked instead of Uncooked
- fixed a bug where mod asset browser wouldn't update when installing new mods
- fixed a bug where custom classes were not deteceted properly
- fixed a bug where uncooking mods wouldn't work
- fixed a bug where the pack settings were weird
> Cvariable fixes

- .github/workflows/Nightly.yml
- .github/workflows/main.yml
Fixed the CI depleting the lfs quota
> Fix CI lfs quota depletion

- CP77.CR2W/Archive/Archive.cs
- CP77.CR2W/Archive/ArchiveManager.cs
- CP77.CR2W/Archive/FileEntry.cs
- CP77.CR2W/Archive/Header.cs
- CP77.CR2W/Archive/Index.cs
- CP77.CR2W/CR2W/CR2WFile.cs
- CP77.CR2W/Modkit/Pack.cs
- CP77.CR2W/Modkit/Unbundle.cs
- CP77.CR2W/Modkit/Uncook.cs
- CP77.CR2W/Types/CVariable.cs
- CP77.CR2W/Types/Generic/Arrays/CArrayBase.cs
- CP77.CR2W/Types/IEditableVariable.cs
- CP77.MSTests/Cr2wUnitTest.cs
- CP77.MSTests/GameUnitTest.cs
Implemented:
- rename archive entries to reflect the official name
> rename archive entries to reflect the official name

- CP77.CR2W/WolvenKit.Cyberformats.csproj
> adding sharpgltf package required for uncookmesh

- CP77.CR2W/Modkit/UncookMesh.cs
> class to export .mesh files to .glb

- CP77.CR2W/CR2W/CR2WFile.cs
- CP77.CR2W/CR2WTypeManager.cs
- CP77.CR2W/Types/Generic/curveData.cs
- CP77.CR2W/Types/Interfaces.cs
- CP77.CR2W/Types/cp77/CBitmapTexture.cs
- CP77.CR2W/Types/cp77/STextureGroupSetup.cs
- CP77.CR2W/Types/cp77/inkGameSettingsResource.cs
- CP77.CR2W/Types/cp77/physicsMaterialLibraryResource.cs
- CP77.MSTests/Cr2wReadTest.cs
- CP77.MSTests/Cr2wUnitTest.cs
- CP77.MSTests/Cr2wWriteTest.cs
- CP77.MSTests/TestResult.cs
- CP77Tools/Commands/VerifyCommand.cs
- CP77Tools/Program.cs
- CP77Tools/Tasks/VerifyTask.cs
- WolvenKit.Common/DDS/TexconvWrapper.cs
Implemented:
- parallel unit tests
- more verbose read unit test
- implemented write unit tests
Fixed:
- default uncook extension dds
- fixed a bug with logging unit test results
> Better unit tests

- CP77Tools.sln
- CP77Tools/Program.cs
Implemented:
- add cp77tools solution
> Merge CP77Tools Solution

- WolvenKit/App.xaml.cs
- WolvenKit/Commands/ApplicationCreateNewProjectCommandContainer.cs
- WolvenKit/Commands/SettingsGeneralCommandContainer.cs
- WolvenKit/Constants.cs
- WolvenKit/Views/DocumentView.xaml
- WolvenKit/Views/HomePage/HomePageView.xaml
- WolvenKit/Views/HomePage/HomePageView.xaml.cs
- WolvenKit/Views/HomePage/Pages/AboutPageView.xaml
- WolvenKit/Views/HomePage/Pages/AboutPageView.xaml.cs
- WolvenKit/Views/HomePage/Pages/GithubPageView.xaml
- WolvenKit/Views/HomePage/Pages/IntegratedToolsPageView.xaml
- WolvenKit/Views/HomePage/Pages/RecentProjectView.xaml
- WolvenKit/Views/HomePage/Pages/SettingsPageView.xaml
- WolvenKit/Views/HomePage/Pages/WebsitePageView.xaml
- WolvenKit/Views/HomePage/Pages/WelcomePageView.xaml
- WolvenKit/Views/HomePage/Pages/WikiPageView.xaml
- WolvenKit/Views/ImportView.xaml
- WolvenKit/Views/ProjectExplorerView.xaml
- WolvenKit/Views/PropertiesView.xaml
- WolvenKit/Views/RibbonView.xaml.cs
Just more stuff , Some1 please get that update dialog outta here it has the possibility of crashing the app ;p
> Home page progression

- .editorconfig
- WolvenKit/Controllers/Cp77Controller.cs
- WolvenKit/ViewModels/Tools/AssetBrowser/AssetBrowserViewModel.cs
- WolvenKit/Views/Tools/AssetBrowser/AssetBrowserView.xaml
- WolvenKit/Views/Tools/AssetBrowser/AssetBrowserView.xaml.cs
- Working directory browser
- Preview panel (once the renderer works we can add stuff here etc)
- Async import
- Bugfixes
Ps.: I also added the editorconfig
> Asset browser qol

- CP77.CR2W/Types/Custom/CMesh.cs
- CP77.CR2W/Types/Primitive/CColor.cs
- CP77.CR2W/Types/Primitive/Matrix.cs
- CP77.CR2W/Types/cp77/CColor_.cs
- CP77.CR2W/Types/cp77/CMatrix_.cs
- CP77.CR2W/Types/cp77/CMesh_.cs
- CP77.CR2W/Types/cp77/CParticleInitializerSpawnCircle.cs
- CP77.CR2W/Types/cp77/MorphTargetMeshEntry.cs
- CP77.CR2W/Types/cp77/SmartBulletDeflectedEvent.cs
- CP77.CR2W/Types/cp77/gameHitShapeBase.cs
- CP77.CR2W/Types/cp77/gameprojectileShootEvent.cs
- CP77.CR2W/Types/cp77/meshMeshImportedSnapPoint.cs
- CP77.CR2W/Types/cp77/meshMeshParamWorkspotOffsets.cs
- CP77.CR2W/Types/cp77/physicsSystemJoint.cs
- CP77.CR2W/Types/cp77/vgBaseVectorGraphicShape.cs
- CP77.CR2W/Types/cp77/worldBendedMeshNode.cs
The following changes occured:
* "Color" should be mapped to "CColor"
* CMatrix should be mapped to "CMatrix"
> Fix some RTTIs

- CP77.CR2W/Reflection/REDReflection.cs
Before the ordinals could start from `0` even in a child class, now with the new RTTI dump they will continue from base class thus not having duplicate ordinals. The old code still  tried to order them based on parents, now this should now be needed anymore.
> Fix the return ordering of RED members

- README.md
> Typos and whatnot

- README.md
- WolvenKit.Console/DumpDDSInfo.cs
- WolvenKit.Console/Options.cs
Fixed:
- Fixes typos
@DerinHalil
> Fixes typos

- WolvenKit.App/WolvenKit.App.csproj
- WolvenKit/App.xaml.cs
- WolvenKit/Functionality/Helpers/AppHelper.cs
- WolvenKit/Views/HomePage/Pages/WelcomePageView.xaml
- WolvenKit/WolvenKit.UI.csproj
Hi
Some WelcomePage changes and Catel Namingconventions k thnx bai
> Feature offline nightly

- WolvenKit.App/Functionality/Services/SettingsManager.cs
- WolvenKit.App/Models/Wizards/FirstSetupWizardModel.cs
- WolvenKit.App/ViewModels/Wizards/FirstSetupWizard/FinalizeSetupViewModel.cs
- WolvenKit.App/ViewModels/Wizards/FirstSetupWizard/SetInitialPreferencesViewModel.cs
- WolvenKit/Views/Wizards/FirstSetupWizard/FinalizeSetupView.xaml
- WolvenKit/Views/Wizards/FirstSetupWizard/SetInitialPreferencesView.xaml
Implemented:
- Implemented guided tour option in first time setup for SettingsManager.
Fixed:
- Removed update channel.
> First time setup guided tour option

- WolvenKit.Modkit/Modkit/Helper/Common/StructFunctions.cs
- WolvenKit.Modkit/Modkit/Helper/Common/Structs.cs
- WolvenKit.Modkit/Modkit/Helper/Functions/MeshFunctions.cs
- WolvenKit.Modkit/Modkit/Helper/Functions/RigFunctions.cs
- WolvenKit.Modkit/Modkit/Helper/Functions/TargetFunctions.cs
- WolvenKit.Modkit/WolvenKit.Modkit.csproj
> skinned mesh,morphtarget to gltf support

- WolvenKit/App.xaml
- WolvenKit/App.xaml.cs
- WolvenKit/Views/Editor/Basic/AssetBrowserView.xaml
- WolvenKit/Views/Editor/Basic/AssetBrowserView.xaml.cs
- WolvenKit/Views/Editor/Basic/LogView.xaml
- WolvenKit/Views/Editor/Basic/PropertiesView.xaml
- WolvenKit/WolvenKit.UI.csproj
> Feature fastfixes

- WolvenKit.Modkit/Modkit/Helper/Common/MaterialTypes.cs
- WolvenKit.Modkit/Modkit/Helper/Common/StructFunctions.cs
- WolvenKit.Modkit/Modkit/Helper/Common/Structs.cs
- WolvenKit.Modkit/Modkit/Helper/Functions/MaterialFunctions.cs
- WolvenKit.Modkit/Modkit/Helper/Functions/MeshFunctions.cs
> low level material parsing for mesh files

- WolvenKit.App/Functionality/Constants.cs
- WolvenKit.App/Functionality/Controllers/Tw3Controller.cs
- WolvenKit.App/Functionality/ProjectManagement/Project/Cp77Project.cs
- WolvenKit.App/Functionality/ProjectManagement/Project/EditorProject.cs
- WolvenKit.App/Functionality/ProjectManagement/Project/Tw3Project.cs
- WolvenKit.App/Functionality/Services/ApplicationInitializationService.cs
- WolvenKit.App/Models/Wizards/PublishWizardModel.cs
- WolvenKit.App/ViewModels/Shell/WorkSpaceViewModel.cs
- WolvenKit.App/ViewModels/Wizards/ProjectWizard/FinalizeSetupViewModel.cs
- WolvenKit.App/ViewModels/Wizards/ProjectWizard/ProjectConfigurationViewModel.cs
- WolvenKit.App/ViewModels/Wizards/PublishWizard/FinalizeSetupViewModel.cs
- WolvenKit.App/ViewModels/Wizards/PublishWizard/OptionalSettingsViewModel.cs
- WolvenKit.App/ViewModels/Wizards/PublishWizard/RequiredSettingsViewModel.cs
- WolvenKit.App/ViewModels/Wizards/PublishWizard/W3PackSettingsViewModel.cs
- WolvenKit.Common/Model/WitcherPackSettings.cs
- WolvenKit/Functionality/Commands/ApplicationPublishProjectCommandContainer.cs
- WolvenKit/Functionality/Helpers/AppHelper.cs
- WolvenKit/Views/Shell/RibbonView.xaml
- WolvenKit/Views/Wizards/FirstSetupWizardView.xaml.cs
- WolvenKit/Views/Wizards/ProjectWizard/ProjectConfigurationView.xaml
- WolvenKit/Views/Wizards/ProjectWizard/ProjectConfigurationView.xaml.cs
- WolvenKit/Views/Wizards/ProjectWizardView.xaml.cs
- WolvenKit/Views/Wizards/PublishWizard/FinalizeSetupView.xaml
- WolvenKit/Views/Wizards/PublishWizard/FinalizeSetupView.xaml.cs
- WolvenKit/Views/Wizards/PublishWizard/OptionalSettingsView.xaml
- WolvenKit/Views/Wizards/PublishWizard/RequiredSettingsView.xaml
- WolvenKit/Views/Wizards/PublishWizard/RequiredSettingsView.xaml.cs
- WolvenKit/Views/Wizards/PublishWizard/W3PackSettingsView.xaml
- WolvenKit/Views/Wizards/PublishWizardView.xaml.cs
Implemented:
- Publish wizard
Only works for TW3.
Runs PackAndInstallProject with WitcherPackSettings when someone publishes a project.
> V0.8 fixes

- Installer/Installer.wixproj
- Installer/Product.wxs
- WolvenKit.sln
- WolvenKit/WolvenKit.UI.csproj
Implemented:
- Create basic WIX installer with simple UI
x64 is preferred, installation folder permissions are modified to be usable by "Users" and "Everyone" users.
> Create basic WIX installer

- WolvenKit.Modkit/Modkit/Helper/Common/MaterialTypes.cs
- WolvenKit.Modkit/Modkit/Helper/Functions/MaterialFunctions.cs
- WolvenKit.Modkit/Modkit/UncookMLmask.cs
> mlmask uncook fix, adding material parsing using gamedir

- WolvenKit.App/Functionality/Controllers/Configuration.cs
- WolvenKit.App/Functionality/Services/ISettingsManager.cs
- WolvenKit.App/Functionality/Services/SettingsManager.cs
- WolvenKit.App/ViewModels/HomePage/Pages/CompatibilitySubSettingsViewModel.cs
- WolvenKit.Modkit/Modkit/Helper/Common/MaterialSetup.cs
- WolvenKit.Modkit/Modkit/Helper/Common/MaterialTypes.cs
- WolvenKit.Modkit/Modkit/Helper/Common/Structs.cs
- WolvenKit.Modkit/Modkit/Helper/Functions/MaterialFunctions.cs
- WolvenKit.Modkit/Modkit/Helper/Functions/MeshFunctions.cs
- WolvenKit.Modkit/Modkit/UncookMLmask.cs
- WolvenKit/App.xaml.cs
- WolvenKit/Functionality/ImageDecoder.cs
- WolvenKit/Views/Dialogs/MaterialsRepositoryDialog.xaml
- WolvenKit/Views/Dialogs/MaterialsRepositoryDialog.xaml.cs
- WolvenKit/Views/Dialogs/SimpleMeshExporterDialog.xaml
- WolvenKit/Views/Dialogs/SimpleMeshExporterDialog.xaml.cs
- WolvenKit/Views/HomePage/Pages/CompatibilitySubSettingsView.xaml
- WolvenKit/Views/HomePage/Pages/CompatibilitySubSettingsView.xaml.cs
- WolvenKit/Views/Others/MaterialRepositoryDrawer.xaml
- WolvenKit/Views/Others/MaterialRepositoryDrawer.xaml.cs
- WolvenKit/Views/Others/StartupViewer.xaml
- WolvenKit/Views/Others/StartupViewer.xaml.cs
- WolvenKit/Views/Shell/MainView.xaml
- WolvenKit/Views/Shell/RibbonView.xaml
- WolvenKit/Views/Shell/RibbonView.xaml.cs
- WolvenKit/WolvenKit.UI.csproj
- WolvenKit/WolvenKit.UI_aghngqu3_wpftmp.csproj
Mesh Exporter
Material Repo
Some other stuff /shrug
> Feature offline merge

- WolvenKit.App/ViewModels/Editor/Basic/AssetBrowserViewModel.cs
- WolvenKit/App.xaml.cs
- WolvenKit/Views/Dialogs/SimpleMeshExporterDialog.xaml.cs
- WolvenKit/Views/Editor/Basic/AssetBrowserView.xaml
- WolvenKit/Views/Editor/Basic/AssetBrowserView.xaml.cs
- WolvenKit/WolvenKit.UI.csproj
> 🚀 Ready to test bois?🚀 

- WolvenKit.Modkit/Modkit/Helper/Functions/MaterialFunctions.cs
Implemented:
Fixed:
- <Fixes>
switched to back ground thread for generating material repository, to avoid crash/freeze of UI
> material repo generate in bg thread

- WolvenKit.Modkit/Modkit/Helper/Functions/TargetFunctions.cs
> some target export exception fixes

- README.md
Readme.md: added missing steps to build successfully
Fixed:
- Adds missing requirements to build the project successfully to the readme
> Readme.md: added missing steps to build successfully

- WolvenKit.CLI.MSTests/ArchiveTests.cs
- WolvenKit.CLI.MSTests/Cr2wReadTest.cs
- WolvenKit.CLI.MSTests/Cr2wWriteTest.cs
- WolvenKit.CLI.MSTests/GameUnitTest.cs
- WolvenKit.CLI.MSTests/TestResult.cs
- WolvenKit.CLI.MSTests/WolvenKit.CLI.MSTests.csproj
- WolvenKit.CLI/Commands/UnbundleCommand.cs
- WolvenKit.CLI/Tasks/UnbundleTask.cs
- WolvenKit.Modkit/Modkit/Pack.cs
- WolvenKit.Modkit/Modkit/Unbundle.cs
- WolvenKit.Modkit/Modkit/Uncook.cs
Implemented:
- unit test for unbundling
- unsafe unbundling with decompression 
Fixed:
- remove "basegame_" from packing
> Feature cli unit tests

- .github/workflows/draft_console.yml
Implemented:
- add a release console action
> Feature ci

- WolvenKit.Modkit/Modkit/Helper/Common/MaterialTypes.cs
- WolvenKit.Modkit/Modkit/Helper/Common/StructFunctions.cs
- WolvenKit.Modkit/Modkit/Helper/Common/Structs.cs
- WolvenKit.Modkit/Modkit/Helper/Functions/MaterialFunctions.cs
- WolvenKit.Modkit/Modkit/Helper/Functions/MeshFunctions.cs
- WolvenKit.Modkit/Modkit/Helper/Functions/MeshImportFunctions.cs
- WolvenKit.Modkit/Modkit/Helper/Functions/RigFunctions.cs
- WolvenKit.Modkit/Modkit/Helper/Functions/TargetFunctions.cs
Implemented:
importing meshes, as in taking a gltf file and importing the geometries to a selected mesh file, also feature to unpack/pack local material buffer, exporting meshes with place holder world space rig
Fixed:
- <Fixes>
changes regarding the orientation/ handness of meshes, LHS to RHS handness conversion including targets, some stream dispose and close to avoid windows file permission issues, changed way to getting mesh and material internal buffer for better optimization.
> some mesh importing support

- README.md
Updated documentation:
- Expanded build instructions in README.md to be more concise.
> Updated README.md to provide clearer instructions.

- README.md
Slightly Refactored Readme
Implemented:
- Added links
Fixed:
- Minor typos
- Messy capitalizations 
- Incorrect/Unpleasant English
The readme had some minor typos. As well as some writing issues like sentences that trailed and an over-use of passive speech. Edited it to make it more appealing to a new-comer to read. Along with making it easier to edit by inserting line-breaks in markdown that don't affect the rendered page.
> Updated Discord invite. Made Readme more pleasant.

- WolvenKit.RED4.CR2W/Types/CustomEnums.cs
- WolvenKit.RED4.CR2W/Types/cp77/DataTermControllerPS.cs
- WolvenKit.RED4.CR2W/Types/cp77/FastTravelSystem.cs
- WolvenKit.RED4.CR2W/Types/cp77enums.cs
- Update types for 1.22
- Seperated cp77enums and custom enums
> Red4 type update for 1.22

- WolvenKit.CLI/Commands/UnbundleCommand.cs
- WolvenKit.CLI/WolvenKit.CLI.csproj
- WolvenKit.Common/RED4/Archive/LxrsFooter.cs
- WolvenKit.Common/Services/HashService.cs
- WolvenKit.Common/Services/IHashService.cs
- WolvenKit.Common/Services/Red4ParserService.cs
- WolvenKit.Common/Tools/Oodle/OodleHelper.cs
- WolvenKit.Modkit/RED4/ModToolExtensions.cs
- WolvenKit.Modkit/RED4/Pack.cs
Implemented:
- added minimal custom path support
Fixed:
- fixed a bug where unbundling would not detect file patterns
- fixed a bug where oodle compression would not fall back to the uncompressed input in case of errors
> Feature path support + bug fixes

- WolvenKit.App/Functionality/Controllers/Tw3Controller.cs
- WolvenKit.Modkit/Managers/WolvenKitArchiveManager.cs
- WolvenKit.Witcher3Formats/SoundCache/Sound_Cache.cs
- WolvenKit.Witcher3Formats/W3Speech/SpeechManager.cs
- fixed a bug where tw3 managers would not load
> tw3 manager fixes

- WolvenKit.App/Functionality/Controllers/Cp77Controller.cs
- WolvenKit.App/Functionality/Services/ISettingsManager.cs
- WolvenKit.App/Functionality/Services/SettingsManager.cs
- WolvenKit.Modkit/RED4/Helper/Functions/MaterialFunctions.cs
- WolvenKit/Views/HomePage/Pages/WelcomePageView.xaml
Fixed:
- remove basedir paths
- link fix
> 497 installer qol last minute

- WolvenKit.Modkit/RED4/Helper/Functions/MeshFunctions.cs
Implemented:
Fixed:
- <Fixes>
fixed random crash while previewing certain meshes
> Mesh preview fix

- WolvenKit.App/Models/FileModel.cs
- WolvenKit.App/ViewModels/Editor/Basic/PropertiesViewModel.cs
- WolvenKit.App/ViewModels/Editor/Tools/ImportExportItemViewModel.cs
- WolvenKit.App/ViewModels/Editor/Tools/ImportExportViewModel.cs
- WolvenKit.App/WolvenKit.App.csproj
- WolvenKit.Common/Model/Arguments/ImportExportArguments.cs
- WolvenKit.Core/Enums.cs
- WolvenKit.Modkit/RED4/Helper/Functions/MeshFunctions.cs
- WolvenKit.Modkit/RED4/Uncook.cs
- WolvenKit/Functionality/Commands/SyncFusion/SFDataGridSelectionControllerExt.cs
- WolvenKit/Functionality/Initialization/Initializations.cs
- WolvenKit/Views/Editor/Basic/AssetBrowserView.xaml
- WolvenKit/Views/Editor/Basic/AssetBrowserView.xaml.cs
- WolvenKit/Views/Editor/Basic/ProjectExplorerView.xaml
- WolvenKit/Views/Editor/Basic/ProjectExplorerView.xaml.cs
- WolvenKit/Views/Editor/Basic/PropertiesView.xaml
- WolvenKit/Views/Editor/Tools/ImportExportView.xaml
- WolvenKit/Views/Editor/Tools/ImportExportView.xaml.cs
added converter tool for GLB > Various formats.
Various formats can be previewed in mesh previewer too 👍 
It is not perfectly threaded so it does block with many items.
Also includes : 
- Video preview fix.
- Audio Play fix
- Automatically show the relevant tab if previewing items.
- Removed Export BK2 option from AB.
- Fixes uncook (In release files)
- Fixes Init for new users (In release files)
closes #505
> Feature 505 import export tool converter

- WolvenKit.App/Functionality/Helpers/Debug_Helpers.cs
- WolvenKit.App/Models/Commonfunctions.cs
- WolvenKit.App/ViewModels/Shared/RecentlyUsedItemsViewModel.cs
- WolvenKit.App/ViewModels/Shell/WorkSpaceViewModel.cs
- WolvenKit.Core/CommonFunctions.cs
- WolvenKit.Core/WolvenKit.Core.csproj
- WolvenKit.sln
- WolvenKit/App.xaml.cs
- WolvenKit/Functionality/Helpers/Static_Helpers.cs
- WolvenKit/Functionality/Initialization/Initializations.cs
- WolvenKit/Views/HomePage/Pages/GithubPageView.xaml
- WolvenKit/Views/HomePage/Pages/GithubPageView.xaml.cs
- WolvenKit/Views/HomePage/Pages/WebsitePageView.xaml
- WolvenKit/Views/HomePage/Pages/WebsitePageView.xaml.cs
- WolvenKit/Views/HomePage/Pages/WelcomePageView.xaml
- WolvenKit/Views/HomePage/Pages/WelcomePageView.xaml.cs
- WolvenKit/Views/HomePage/Pages/WikiPageView.xaml.cs
- WolvenManager.Installer/Services/UpdateService.cs
Fixed:
- fixed a bug where the updateservice would crash when offline
- disabled webview2 when offline
- check if webview2 is installed on app startup
- fixed a bug where the recently used items would crash
closes #526
> fix offline mode

- WolvenKit.Common/Tools/DDS/DDSUtils.cs
- WolvenKit.Modkit/RED4/UncookMLmask.cs
Fixed:
- <Fixes>
mlmask layers weren't uncooking after directxtex wrapper implementation, now they do
> mlmask uncook fix

- WolvenKit.App/ViewModels/Editor/Tools/ImportExportItemViewModel.cs
- WolvenKit.Common/Model/Arguments/ImportExportArguments.cs
- WolvenKit.Common/Tools/DDS/DDSUtils.cs
- WolvenKit.Core/Enums.cs
- WolvenKit.Modkit/RED4/Helper/Functions/MLMaskFunctions.cs
- WolvenKit.Modkit/RED4/Import.cs
Implemented:
- ability to create new mlmask files from masklist (txt file specifying mask image paths)
> mlmask cook

- WolvenKit.App/ViewModels/Tools/PropertiesViewModel.cs
Fixed:
- Bug: Clicking the play button on an audio track wouldnt play the track again if it had previously been played
> Fixed audio replay bug

- WolvenKit.App/ViewModels/Documents/RedDocumentViewModel.cs
- WolvenKit.App/ViewModels/Documents/TweakDocumentViewModel.cs
- WolvenKit.App/ViewModels/Documents/TweakEntryViewModel.cs
- WolvenKit.Modkit/RED4/Serialization/yaml/TweakTypeConverter.cs
- WolvenKit/Views/Documents/DocumentView.xaml
- WolvenKit/Views/Documents/TweakDocumentView.xaml
- WolvenKit/Views/Documents/TweakDocumentView.xaml.cs
- WolvenKit/Views/Templates/RedDocumentTemplateSelector.cs
Fixed:
- fixed the display for array tweak editing
> array tweak editing

- README.md
> Fix CONTRIBUTING.md link in the README

- README.md
- Centered introduction
- Added full logotype at the top instead of text title
- Removed the redundant mention of the wiki and instead linked it once in the usage section and once on the WK logo at the top
> Make README a bit more eye-catching

- README.md
- WolvenKit/Views/Shell/RibbonView.xaml
- WolvenKit/Views/Shell/RibbonView.xaml.cs
Ribbon view updated with:
- Save As button
- Pack & Install button
> Update ribbon view for tools

- WolvenKit.Common/Model/Arguments/ImportExportArguments.cs
- WolvenKit.Modkit/RED4/Tools/MorphTargetTools.cs
Changed:
- Texture Import: Default value for "keep file" changed from true to false
Fixed:
- Morphtarget export
> 8.5.0 bug fixes

- WolvenKit.CLI/WolvenKit.CLI.csproj
- WolvenKit.Core/Compression/Oodle.cs
Fixed:
- fix a bug where Oodle would crash on load
linus
> fix a bug where Oodle would crash on load

- .github/workflows/check-build.yml
- .github/workflows/draft-release.yml
Also I got rid of workflow dispatch for checks. Feel free to add it back.
> Check build only on branch pushes and not tags

- WolvenKit.Core/Compression/OozNative.cs
> Fix Linux Ooz library paths

- .github/workflows/codeql.yml
For security checks and whatnot.
> Add CodeQL analysis

- WolvenKit.RED4.Types/Classes/worldPrefabNode.cs
- WolvenKit.RED4.Types/ClassesExt/Properties/cpGameplayLightComponent.cs
- WolvenKit.RED4.Types/Primitives/CArrayBase.cs
- WolvenKit.RED4.Types/Primitives/CHandle.cs
- WolvenKit.RED4.Types/Primitives/CWeakHandle.cs
tbh no clue what I'm doing but I looked at the compiler warnings and did what they said to do to fix them because they were an eyesore.
also for some reason rider did some weird stuff with whitespace but it seems to look ok.
> Fix warnings on publish

- docs/DEVELOPER GUIDE.md
Should figure out how to get this synced directly to the wiki.
Relating to #717
> Add Barebones Dev Guide

- WolvenKit.Core/WolvenKit.Core.csproj
- WolvenKit/WolvenKit.csproj
> Fix kraken.dll name

- .github/FUNDING.yml
> Update funding details and add Open Collective

- README.md
> Fix refs after branch name change

- WolvenKit.Modkit/RED4/Rebuild.cs
Please merge shortly before nightly build :P 
Fixes:
- Buffer rebuilding
> Daily fix branch

- WolvenKit/Converters/RedEditorTemplateSelector.cs
- WolvenKit/Views/Editors/RedTypeView.xaml
- WolvenKit/Views/Templates/RedChunkMaskEditor.xaml
- WolvenKit/Views/Templates/RedChunkMaskEditor.xaml.cs
- WolvenKit/WolvenKit.csproj
* Implements a basic Chunkmask editor for the `chunkmask` variable of a MeshComponent
> Adds Basic Chunkmask Editor

- WolvenKit.CLI/GenericHost.cs
- WolvenKit.CLI/WolvenKit.CLI.csproj
- WolvenKit.Modkit/RED4/Import.cs
- WolvenKit.Modkit/RED4/Tools/MlmaskTools.cs
- WolvenKit.RED4.Types/Primitives/CArray.cs
- WolvenKit.RED4.Types/Primitives/CArrayBase.cs
- WolvenKit.RED4.Types/Primitives/CArrayFixedSize.cs
- WolvenKit.RED4.Types/Primitives/CStatic.cs
- WolvenKit.RED4.Types/Primitives/Simples/CString.cs
- WolvenKit/Views/Dialogs/MaterialsRepositoryDialog.xaml.cs
- WolvenKit/Views/Shell/DockingAdapter.xaml
- WolvenKit/Views/Shell/DockingAdapter.xaml.cs
General fixes
Fixed:
- Copying of red Arrays (#739)
- Extracting the same red file multiple times (#749)
- Fixed floating windows always stays on top of all applications (#752)
- Wrong format and compression set, while creating a new xbm (#756)
- Unable to locate HashService in WolvenKit.CLI (#762)
- Changed mlmask export folder name to avoid conflicts
- Some compiler warnings
> General fixes

- WolvenKit.App/ViewModels/Tools/PropertiesViewModel.cs
- WolvenKit.Modkit/RED4/Tools/MeshImportTools.cs
- WolvenKit.RED4.Types/IO/Red4Writer.cs
- WolvenKit.RED4.Types/Primitives/CBitField.cs
- WolvenKit.RED4.Types/Primitives/CEnum.cs
- WolvenKit.RED4.Types/Reflection/RedReflection.cs
Daily fixes
Fixed:
- Catched some NullReferenceExceptions
- Properly read enums with custom RedNames
> Daily fixes

- README.md
The checks always said pending so I just had it use the workflow for build checks.
> Update Shields.io workflow badges in README.md

- WolvenKit.Modkit/RED4/RedConverter.cs
- WolvenKit.RED4.Archive/IO/CR2WListWriter.cs
- WolvenKit.RED4.Archive/IO/CR2WWriter.File.cs
- WolvenKit.RED4.Archive/IO/CR2WWriter.cs
- WolvenKit.RED4.Archive/IO/PackageWriter.File.cs
- WolvenKit.RED4.Archive/IO/PackageWriter.cs
- WolvenKit.RED4.Types/IO/Red4Writer.cs
Implemented:
- Log successful JSON imports
Fixed:
- Writing of nested DataBuffers
> Fix Buffer writing

- WolvenKit.App/Controllers/GameControllerBase.cs
- WolvenKit.App/Controllers/RED4Controller.cs
- WolvenKit.App/ViewModels/Dialogs/SelectRedTypeDialogViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
- WolvenKit.Modkit/RED4/Tools/Animation/AnimSIMD.cs
- WolvenKit.RED4.Archive/IO/CR2WReader.File.cs
- WolvenKit.RED4.Archive/IO/CR2WReader.cs
- WolvenKit.RED4.Types/Interfaces/IRedInteger.cs
- WolvenKit.RED4.Types/Primitives/Fundamentals/CDouble.cs
- WolvenKit.RED4.Types/Primitives/Fundamentals/CFloat.cs
- WolvenKit.RED4.Types/Primitives/Internal/BaseStringType.cs
- WolvenKit.RED4.Types/Primitives/Simples/CRUID.cs
- WolvenKit.RED4.Types/Primitives/Simples/CString.cs
- WolvenKit/Views/Dialogs/SelectRedTypeDialog.xaml
- WolvenKit/Views/Dialogs/SelectRedTypeDialog.xaml.cs
- WolvenKit/Views/Shell/MainView.xaml
- WolvenKit/Views/Templates/RedBaseTypeEditor.xaml.cs
- WolvenKit/Views/Templates/RedIntegerEditor.xaml.cs
Implemented:
- Type chooser for CKeyValuePair creation
Fixed:
- Crash on creating CKeyValuePair
- Possible crash while exporting anims
- Wrongly displayed values in the files TreeView
Other notes:
- Replaced exception on unused buffers with a warning
- The CR2W reader now throws an error if a file is missing a buffer
- Changed the behaviour how files are added to the project from the AssetBrowser. It now takes the one from the selected archive if possible.
> General fixes and improvements

- WolvenKit.App/Controllers/RED4Controller.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit/Views/Shell/RibbonView.xaml
- WolvenKit/Views/Shell/RibbonView.xaml.cs
Implemented:
- dropdown menu with game launch options instead of buttons
> dropdown game launch options

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit/Converters/PropertyGridEditors.cs
- WolvenKit/Converters/RedEditorTemplateSelector.cs
- WolvenKit/Views/Templates/RedBaseTypeEditor.xaml.cs
- WolvenKit/Views/Templates/RedCurvePointEditor.xaml.cs
- WolvenKit/Views/Templates/RedFixedPointEditor.xaml.cs
- WolvenKit/Views/Templates/RedFloatEditor.xaml.cs
- WolvenKit/Views/Templates/RedQuaternionEditor.xaml.cs
- WolvenKit/Views/Templates/RedVector2Editor.xaml.cs
- WolvenKit/Views/Templates/RedVector3Editor.xaml.cs
- WolvenKit/Views/Templates/RedVector4Editor.xaml.cs
- WolvenKit/Views/Templates/RedWorldPositionEditor.xaml.cs
Fixed:
- Fixed using wrong editor for float values 
Changed format string for floats from "R" to "G9"
> Fixed using wrong editor for float values

- README.md
Avoid having to change this for every minor update (but we should probably also have a way to recommend specific version updates since I don't think these go through Windows Update..)
Closes #793
> README: Updated .NET Runtime Download Instructions

- WolvenKit.Modkit/RED4/Tools/MaterialTools.cs
- WolvenKit.Modkit/RED4/Tools/MeshImportTools.cs
Fixed:
- Mesh import with materials
Could be related to #770
> Mesh import fixes

- README.md
- WolvenKit.Common/Model/Arguments/ImportExportArguments.cs
Mesh default tweaks + Readme update
Implemented:
- Improved default mesh I/O settings
- Cleaned up some I/E tooltips
- Updated Readme screenshots and format slightly
> Mesh default tweaks + Readme update

- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
If you want to search for everything, `.*?` should work but you
probably shouldn't do that. Search for something. Anything.
> ✨🐛 Empty search string clears AB search results

- WolvenKit.Common/Services/GeometryCacheService.cs
Fixed:
- Replaced magic hash value with known path string in GeometryCacheService
> Removed magic hash from GeometryCacheService

- WolvenKit.App/Helpers/Utils.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
Fixed:
- a bug in DeleteSelection, it should now be able to delete in any buffer array not just worldNodeDataBuffers
> Fixed broken DeleteSelection

- .github/workflows/nightly.yml
Update ref for the nightly workflow which generates nightly release artifacts
> Update nightly workflow

- WolvenKit.Common/RED4/CR2W/JSON/PrimitiveConverter.cs
- WolvenKit.RED4.Archive/Buffer/RedPackage.cs
- WolvenKit.RED4.Archive/IO/CR2WWriter.File.cs
- WolvenKit.RED4.Archive/IO/RedPackageReader.File.cs
- WolvenKit.RED4.Archive/IO/RedPackageWriter.File.cs
Fixed:
- Fixed a bug where buffers weren't imported correctly
> JSON import fix

- WolvenKit.App/Services/SettingsManager.cs
File preview is now set true by default aiming to help new users.
> Turn file preview on by default

- WolvenKit.App/Models/FileModel.cs
- WolvenKit.App/ViewModels/Documents/RDTDataViewModel.cs
- WolvenKit.App/ViewModels/Documents/RDTInkTextureAtlasViewModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit.App/WolvenKit.App.csproj
Fixed:
- add missing ObservesProperty to DelegateCommands
I'm sorry
> fix a bug where certain ui commands would not work

- WolvenKit/Views/HomePage/Pages/GithubPageView.xaml
- WolvenKit/Views/HomePage/Pages/SettingsPageView.xaml
- WolvenKit/Views/HomePage/Pages/WebsitePageView.xaml
- WolvenKit/Views/HomePage/Pages/WikiPageView.xaml
- WolvenKit/Views/Tools/AssetBrowserView.xaml
- WolvenKit/Views/Tools/PropertiesView.xaml
- WolvenKit/Views/Tools/PropertiesView.xaml.cs
- Commented out several animated icons causing a GPU leak
- Small improvement to Properties mesh preview:
Adjusted lighting
Added reset camera context button
> Fix GPU leak

- Tests/WolvenKit.UnitTests/WolvenKit.UnitTests.csproj
- Tests/WolvenKit.UnitTests/WwiseTests.cs
> Add unit tests for Wwise WEM to OGG

- README.md
> docs: update GPL v3.0 to GPL-3.0

- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
Moved the new regex and verbatim logic into refinements so that we don't need to deal with it inline.
> ♻️ Use types instead of inline conditionals in AB search

- WolvenKit/Views/Shell/RibbonView.xaml
Fix ribbon merge issues
- Added Tools menu category to menu bar
- Added Sound Modding Tool to Tools menu
- Added Mod Manager to Extensions menu
> Fix ribbon merge issues

- WolvenKit.App/Helpers/Utils.cs
- WolvenKit.App/Models/ProjectManagement/Project/Cp77Project.cs
- WolvenKit.App/Services/ISettingsManager.cs
- WolvenKit.App/Services/ProjectManager.cs
- WolvenKit.App/Services/SettingsManager.cs
- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
- WolvenKit.Common/Interfaces/IArchiveManager.cs
- WolvenKit.Common/Model/SAsciiString.cs
- WolvenKit.Common/RED4/CR2W/JSON/ParseableBuffers.cs
- WolvenKit.Common/RED4/CR2W/JSON/PrimitiveConverter.cs
- WolvenKit.Common/RED4/CR2W/JSON/RedFileDtoConverter.cs
- WolvenKit.Common/RED4/CR2W/JSON/RedJsonSerializer.cs
- WolvenKit.Common/RED4/CR2W/JSON/Simples.cs
- WolvenKit.Common/Services/HashService.cs
- WolvenKit.Modkit/Managers/ArchiveManager.cs
- WolvenKit.Modkit/Managers/WolvenKitArchiveManager.cs
- WolvenKit.RED4.Archive/IO/RedPackageWriter.File.cs
- WolvenKit.RED4.Types/Helper/ImportHandler.cs
Implemented:
- Save hash-only paths in the project
Fixed:
- Some serializations errors
> fixes and improvements

- WolvenKit.Common/Model/Arguments/ImportArgs.cs
- WolvenKit/Views/Shell/MainView.xaml
Fixed:
- Re-add title bar text
- Cleanup import/export arguments
> Misc fixes

- WolvenKit.App/Helpers/ImageDecoder.cs
- WolvenKit.App/Helpers/MeshHelpers.cs
- WolvenKit.App/ViewModels/Documents/RDTTextureViewModel.cs
- WolvenKit.App/ViewModels/Documents/RDTWidgetViewModel.cs
- WolvenKit.App/ViewModels/Tools/PropertiesViewModel.cs
- WolvenKit.App/WolvenKit.App.csproj
- WolvenKit.Common/Extensions/EnumerableExtensions.cs
- WolvenKit.Common/RED4/RedImage.cs
- WolvenKit/Views/Others/MaterialRepositoryDrawer.xaml.cs
Remove Pfim
Implemented:
- Nothing
Fixed:
- Nothing
Removed:
- Pfim
Maybe I removed Pfim
> Remove Pfim

- WolvenKit.App/Helpers/Utils.cs
- WolvenKit.App/Models/FileSystemArchive.cs
- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
- WolvenKit.App/ViewModels/Tools/RedDirectoryViewModel.cs
- WolvenKit.App/ViewModels/Tools/RedFileViewModel.cs
- WolvenKit.Common/Interfaces/IArchiveManager.cs
- WolvenKit.Common/Model/RedFileSystemModel.cs
- WolvenKit.Core/Interfaces/IGameArchive.cs
- WolvenKit.Modkit/Managers/ArchiveManager.cs
- WolvenKit.Modkit/Managers/WolvenKitArchiveManager.cs
- WolvenKit.RED4.Archive/Base/Archive.cs
- WolvenKit/Views/Tools/AssetBrowserView.xaml.cs
Implemented:
- Archives are now sorted by load order
- Property info showing relative archive path for modded archives
Fixed:
- Always showing the first found file in the file selection instead of the current selected archive
> mod asset browser improvements

- WolvenKit.App/Helpers/MeshHelpers.cs
- WolvenKit.App/ViewModels/Dialogs/FirstSetupViewModel.cs
- WolvenKit.App/ViewModels/Dialogs/MaterialsRepositoryDialogViewModel.cs
- WolvenKit/Views/Dialogs/ProjectSettingsDialog.xaml
- WolvenKit/Views/Dialogs/Windows/MaterialsRepositoryDialog.xaml
- WolvenKit/Views/Documents/RDTMeshView.xaml
- WolvenKit/Views/HomePage/HomePageView.xaml
- WolvenKit/Views/Shell/MenuBarView.xaml
- WolvenKit/Views/Shell/MenuBarView.xaml.cs
- WolvenKit/Views/Tools/AssetBrowserView.xaml
UI Fixes
Fixed:
- Improved, cleaned up, and rearranged various UI elements
- Fixed some awkward UI behaviors in some cases
- Fixed menu bar "Show File Preview" button
> UI Paper Cuts

- WolvenKit.Common/RED4/CR2W/JSON/RedJsonSerializer.cs
- WolvenKit.RED4.Archive/IO/RedPackageWriter.File.cs
- WolvenKit.RED4.Save/Helper/InventoryHelper.cs
- WolvenKit.RED4.Save/IO/CyberpunkSaveReader.cs
- WolvenKit.RED4.Save/IO/CyberpunkSaveWriter.cs
- WolvenKit.RED4.Save/Parser/ArcadeSystemParser.cs
- WolvenKit.RED4.Save/Parser/CharacterCustomizationAppearancesParser.cs
- WolvenKit.RED4.Save/Parser/InventoryParser.cs
- WolvenKit.RED4.Save/Parser/ItemDropStorageParser.cs
- WolvenKit.RED4.Save/Parser/WardrobeSystemParser.cs
Save related fixes and improvements
Implemented:
- Replaced custom CharacterCustomization class with gameuiCharacterCustomizationPreset
- Replaced "HeaderThing" with gameItemId
Fixed:
- RedPackageWriter writing the wrong class hash
- Missing assignment in the ArcadeSystem
> Save related fixes and improvements

- WolvenKit.App/Services/ExtendedScriptService.cs
- WolvenKit.App/Services/IScriptableControl.cs
- WolvenKit.App/ViewModels/Documents/WScriptDocumentViewModel.cs
- WolvenKit.Modkit/Scripting/ScriptService.cs
- WolvenKit/App.xaml.cs
- WolvenKit/GenericHost.cs
- WolvenKit/Initializations.cs
- WolvenKit/Resources/SyntaxHighlighting/JavaScript-DarkMode.xshd
- WolvenKit/Views/Documents/WScriptDocumentView.xaml
- WolvenKit/Views/Others/ScriptableMenu.cs
- WolvenKit/Views/Others/ScriptableMenuItem.cs
- WolvenKit/Views/Shell/MenuBarView.xaml
- WolvenKit/WolvenKit.csproj
Scriptable UI
Implemented:
- Scriptable UI
- Dark mode for script editor
> Scriptable UI

- .github/workflows/draft-release.yml
- .github/workflows/nightly.yml
- .github/workflows/testing.yml
Implemented:
-  skip cli publish when no CI commits have been made
- no nested folders on stable ci
> feat: skip cli publish when no CI commits have been made

- WolvenKit.App/ViewModels/Documents/MeshPreviewBlock.cs
- WolvenKit.App/ViewModels/Documents/MeshPreviewEntity.cs
- WolvenKit.App/ViewModels/Documents/MeshPreviewSector.cs
- WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
- WolvenKit/Views/Documents/RDTMeshView.xaml
2 Small changes to improve coordinate search.
- #1037 
https://user-images.githubusercontent.com/4053748/208457591-0b89417e-867a-4efd-b401-624022ac5743.mp4
- Display Search Coordinate only at Sector Previews view
Mesh preview
Sector Previews
> Sector Previews improvements

- WolvenKit.App/Helpers/MeshHelpers.cs
- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
Fixed:
- https://github.com/WolvenKit/WolvenKit/issues/1035
Doesn't write back yet, but at least it renders?
> issue 1035: prevent exception (does not write back yet)

- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit/Views/Tools/ProjectExplorerView.xaml.cs
closes #977
Add condition to add KeyUp event
> Fixed multiply assignment KeyUp event

- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
- WolvenKit.Modkit/RED4/Uncook.cs
Implemented mesh name to MultiMesh missing bone error message
Closes #902
Implemented:
- Multimesh file name in error message if rig is missing bones
> Implemented mesh name to MultiMesh missing bone error message

- WolvenKit.Common/Model/Arguments/ImportArgs.cs
- WolvenKit.Modkit/RED4/Import.cs
- WolvenKit.Modkit/RED4/Tools/MeshImportTools.cs
- WolvenKit.Modkit/RED4/Tools/MorphTargetImportTools.cs
Implemented general material import toggle into the Mesh importer settings
Closes https://github.com/WolvenKit/WolvenKit/issues/1041
> Added material import toggle to Importer (Issue #1041)

- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
Fixed:
- Material.json files will now be filtered out of bulk json import
closes #1026
> Implemented filter to .json import to exclude material json files

- WolvenKit.RED4.Archive/IO/RedPackageWriter.File.cs
- WolvenKit.RED4.Archive/IO/RedPackageWriter.cs
RedPackage fix
Fixed:
- Writing of CName `None` for RedPackages
> RedPackage fix

- WolvenKit.RED4.Archive/IO/RedPackageWriter.File.cs
- WolvenKit.RED4.Archive/IO/entEntityTemplatePreProcessor.cs
CR2W fixes
Fixed:
- Changed numSections based on import count
- Carry over entEntityTemplate compiledData flags while writing
> CR2W fixes

- Tests/WolvenKit.Utility/DumpInfo.cs
> Some new dumpers

- Tests/WolvenKit.FunctionalTests/GameUnitTest.cs
- Tests/WolvenKit.UnitTests/CompressionTests.cs
- Tests/WolvenKit.Utility/GameUnitTest.cs
- WolvenKit.App/Helpers/WKitUIScripting.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.Core/Compression/Oodle.cs
- WolvenKit.Core/Compression/OodleLZNative.cs
- WolvenKit.Modkit/RED4/Import.cs
- WolvenKit.Modkit/RED4/Pack.cs
- WolvenKit.Modkit/RED4/Rebuild.cs
- WolvenKit.Modkit/RED4/RedConverter.cs
- WolvenKit.Modkit/RED4/Tools/AnimationTools.cs
- WolvenKit.Modkit/RED4/Tools/MaterialTools.cs
- WolvenKit.Modkit/RED4/Tools/MeshImportTools.cs
- WolvenKit.Modkit/RED4/Tools/MlmaskImportTools.cs
- WolvenKit.RED4/Archive/IO/ArchiveWriter.cs
- WolvenKit.RED4/Archive/IO/CR2WListWriter.cs
- WolvenKit.RED4/Archive/IO/CR2WWriter.File.cs
- WolvenKit.RED4/Archive/IO/CR2WWriter.cs
- WolvenKit/App.xaml.cs
Oodle fixes
Implemented:
- Loading oodle from settings path for GUI
- Added logging to CR2W and Archive writers
- Show warning if kraken is used for compression
> Oodle fixes

- WolvenKit.App/ViewModels/Documents/RDTTextViewModel.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewModel.cs
- WolvenKit.App/ViewModels/Documents/ScriptDocumentViewModel.cs
- WolvenKit.App/ViewModels/Documents/WScriptDocumentViewModel.cs
- WolvenKit.App/WolvenKit.App.csproj
- WolvenKit/GenericHost.cs
- WolvenKit/Views/Documents/RDTTextView.xaml.cs
- WolvenKit/Views/Documents/ScriptDocumentView.xaml
- WolvenKit/Views/Documents/WScriptDocumentView.xaml
- WolvenKit/Views/Documents/WScriptDocumentView.xaml.cs
- WolvenKit/WolvenKit.csproj
> Moved AvalonEdit to WolvenKit

- WolvenKit.App/Models/TweakXL.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/TweakBrowserViewModel.cs
- WolvenKit.Common/Services/TweakDBService.cs
Implemented:
- tweak and yaml opening in default editor
Fixed:
- a bug where the lockey browser would crash
closes #1136
> fix: lockey exceptions, tweak files not openeing

- WolvenKit.App/Services/WatcherService.cs
- WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
- WolvenKit.Modkit/RED4/Tools/RigTools.cs
- WolvenKit.RED4/Archive/Buffer/RedPackage.cs
- WolvenKit.RED4/Archive/IO/CR2WReader.File.cs
- WolvenKit.RED4/Archive/IO/CR2WReader.cs
- WolvenKit.RED4/Archive/IO/RedPackageReader.File.cs
- WolvenKit.RED4/Archive/IO/RedPackageReader.cs
- WolvenKit.RED4/Types/IO/Red4Reader.cs
- WolvenKit/Views/Tools/ProjectExplorerView.xaml
Some fixes
Fixed:
- Slow refresh of project explorer
- CHandle/CWeakHandle reading
- Mesh preview showing "NO DATA"
- JSON import/export
- NullRef in Sector preview
- NullRef while exporting certain meshes
> Some fixes

- WolvenKit.App/Controllers/RED4Controller.cs
- WolvenKit.App/ViewModels/Documents/ConnectionViewModel.cs
- WolvenKit.App/ViewModels/Documents/NodeViewModel.cs
- WolvenKit.App/ViewModels/Documents/RDTGraphViewModel.cs
- WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.Modkit/RED4/Tools/MaterialTools.cs
- WolvenKit.Modkit/RED4/Tools/MeshImportTools.cs
- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
- WolvenKit.Modkit/RED4/Tools/MorphTargetTools.cs
- WolvenKit.RED4/Archive/IO/RedPackageReader.cs
- WolvenKit.RED4/Save/Parser/PersistencySystem2Parser.cs
- WolvenKit.RED4/Types/IO/Red4Reader.cs
- WolvenKit.RED4/Types/Primitives/CHandle.cs
- WolvenKit.RED4/Types/Primitives/CWeakHandle.cs
Fixed:
- Make handles nullable again
> Make handles nullable again

- WolvenKit.App/Models/FileSystemArchive.cs
- WolvenKit.App/Models/ProjectManagement/Project/Cp77Project.cs
- WolvenKit.App/Services/ProjectManager.cs
- WolvenKit.App/ViewModels/Exporters/TextureExportViewModel.cs
- WolvenKit.App/ViewModels/Importers/TextureImportViewModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.Modkit/RED4/Export.cs
- WolvenKit.Modkit/RED4/Import.cs
- WolvenKit.Modkit/RED4/Tools/MorphTargetTools.cs
- WolvenKit.RED4/Archive/Base/FileEntry.cs
🐞 .morphtarget export/import work and roundtrip, because...
🐞 `FileSystemArchive` fixed so that it can be used to access current project assets
✨ `Cp77Project.AsArchive()` can be used to directly get an archive of the currently loaded project
📣 Try to produce some easier-to-read output from failed exports
Addresses #1167
> ⚓ Import/Export Bimsnes

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/TweakBrowserViewModel.cs
- WolvenKit/Views/Dialogs/Windows/ChooseCollectionView.xaml
- WolvenKit/Views/Exporters/TextureExportView.xaml
- WolvenKit/Views/Importers/TextureImportView.xaml
- WolvenKit/Views/Shell/DockingAdapter.xaml.cs
General stuff
Implemented:
- Added a filter row to file import
- Changed default filter for filter rows to "Contains" instead of "Begins with"
Fixed:
- Tweak records not showing
- Copying multiple array items didn't work
- Copying multiple non-continues array items copied wrong values
- Deleting multiple array items deleted the wrong items
- Floating windows couldn't be reopned after close
> General stuff

- WolvenKit.RED4/Archive/IO/PreProcessor/CMeshPreProcessor.cs
Contains a bunch of dirty shit that I have only stubbed in for now, but I hope the comments make it clear
> mesh validation implementation, WIP

- WolvenKit/App.xaml.cs
- WolvenKit/Views/Shell/DockingAdapter.xaml.cs
Dunno, completely resistant to debugging.
And also life is gray and boring.
> Fix: Simplify Project UI Layout Loading, Which May Avoid File Lock?

- WolvenKit.App/ViewModels/Exporters/TextureExportViewModel.cs
- WolvenKit.App/ViewModels/Importers/TextureImportViewModel.cs
- WolvenKit.App/ViewModels/Tools/ImportExportViewModel.cs
- WolvenKit.App/ViewModels/Tools/ImportableItemViewModel.cs
- WolvenKit/Views/Shell/DockingAdapter.xaml.cs
Implemented:
- [made import and export tool load files async](https://github.com/WolvenKit/WolvenKit/commit/f190e711e0c848acbd40646c581347454000f244)
closes #1106
> feat: made import and export tool load files async

- WolvenKit.App/ViewModels/Documents/RedDocumentViewModel.cs
- WolvenKit.Common/Conversion/JsonHeader.cs
- WolvenKit.Common/RED4/CR2W/JSON/Simples.cs
- WolvenKit.RED4/Types/Interfaces/IRedBuffer.cs
- WolvenKit.RED4/Types/Pools/NodeRefPool.cs
- WolvenKit/Views/Tools/LocKeyBrowserView.xaml
**!!! This bumps JSON to v0.0.4 !!!**
Implemented:
- Switch LocKey Browser Primaray column from Text to Numeric. Partially fixes #1207 
- Buffer serialization for `SerializationDeferredDataBuffer` and `SharedDataBuffer`. Fixes #1206 
Fixed:
- NodeRef hash calculation for paths with aliases
Disabled unused graph viewer for scene files. See #1208
> General fixes and stuff

- WolvenKit.App/Models/SmartElement3DCollection.cs
- WolvenKit/Views/Documents/RDTMeshView.xaml.cs
Fixed:
- Mesh preview not updating after switching tabs. Thanks @manavortex for the help
> fix: Mesh preview not updating after switching tabs

- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
- WolvenKit.Common/Interfaces/IArchiveManager.cs
- WolvenKit.Modkit/Managers/ArchiveManager.cs
- WolvenKit.Modkit/Managers/WolvenKitArchiveManager.cs
- WolvenKit/Views/Shell/DockingAdapter.xaml.cs
- WolvenKit/Views/Shell/MenuBarView.xaml.cs
- WolvenKit/Views/Tools/AssetBrowserView.xaml
DockingManager improvements
Fixed:
- Saving layout to appdata on close even if a project is loaded
- Import/Export window state not saving
Removed custom `DockPanes.txt` and use SyncFusions state file for loading
> DockingManager improvements

- WolvenKit.App/Helpers/WKitUIScripting.cs
- WolvenKit.Modkit/Scripting/WKitScripting.cs
Filled out some of the TODOs in the scripting with basic summaries
> Some basic doxygen comments.

- .gitattributes
Also a small update to include "yaml" along with "yml"
> Update .gitattributes for .wscript

- README.md
> Fix #1282, README.md discord link

- WolvenKit.RED4/Archive/Base/LxrsFooter.cs
Implemented:
Some minor performance improvements to `LxrsFooter.cs` by: 
- Splitting duplicate code
- Use a single encoding instance instead of retrieving it multiple times
Other changes:
- Renamed some variables
- Changed `FileInfos` property to an auto-property for a more idiomatic C# way
Fixed:
- Fixes #1284
> Fixes #1284, LxrsFooter performance improvements and naming scheme enforcing

- WolvenKit.Modkit/RED4/Tools/Animation/AnimSIMD.cs
- WolvenKit.Modkit/RED4/Tools/Animation/AnimSpline.cs
- WolvenKit.Modkit/RED4/Tools/AnimationTools.cs
- WolvenKit.Modkit/RED4/Tools/Common/StructFunctions.cs
- WolvenKit.Modkit/RED4/Tools/EntityTools.cs
- WolvenKit.Modkit/RED4/Tools/MaterialTools.cs
- WolvenKit.Modkit/RED4/Tools/MeshImportTools.cs
- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
- WolvenKit.Modkit/RED4/Tools/MlmaskImportTools.cs
- WolvenKit.Modkit/RED4/Tools/MlmaskTools.cs
- WolvenKit.Modkit/RED4/Tools/MorphTargetImportTools.cs
- WolvenKit.Modkit/RED4/Tools/MorphTargetTools.cs
- WolvenKit.Modkit/RED4/Tools/OpusInfo.cs
- WolvenKit.Modkit/RED4/Tools/OpusTools.cs
- WolvenKit.Modkit/RED4/Tools/RigTools.cs
Implemented:
- see issue for more details...
Fixed:
- Fixes #1291
> Fix #1291, Quality of Life improvements to ModKit RED4 Tools

- WolvenKit/Resources/Scripts/Wolvenkit/Wolvenkit_FileValidation.wscript
Fixed a validation error when trying to save a root entity file
> Fixed a validation error

- WolvenKit.App/Services/ExtendedScriptService.cs
- directory check can't be file check
> fixed dir existence check

- WolvenKit/Resources/Scripts/Wolvenkit/Wolvenkit_FileValidation.wscript
- WolvenKit/Resources/Scripts/onSave_anims.wscript
- WolvenKit/Resources/Scripts/onSave_app.wscript
- WolvenKit/Resources/Scripts/onSave_ent.wscript
- WolvenKit/Resources/Scripts/onSave_workspot.wscript
… since according to Seb it truncates uint64 and fucks up everything for everyone. And this is why we can't have nice things.
> removed save action's fix-and-overwrite feature

- WolvenKit.RED4/Types/Classes/ExpansionBannerController.cs
- WolvenKit.RED4/Types/Classes/ExpansionPopupData.cs
- WolvenKit.RED4/Types/Classes/ExpansionPopupGameController.cs
- WolvenKit.RED4/Types/Classes/OpenExpansionPopupEvent.cs
- WolvenKit.RED4/Types/Classes/PatchNotesCheckData.cs
- WolvenKit.RED4/Types/Classes/PlayerDevelopmentSystem.cs
- WolvenKit.RED4/Types/Classes/PreOrderPopupController.cs
- WolvenKit.RED4/Types/Classes/SaveGameMenuGameController.cs
- WolvenKit.RED4/Types/Classes/SingleplayerMenuData.cs
- WolvenKit.RED4/Types/Classes/SingleplayerMenuGameController.cs
- WolvenKit.RED4/Types/Classes/gameuiPopupsManager.cs
- WolvenKit.RED4/Types/Classes/gameuiWorldMapMenuGameController.cs
- WolvenKit.RED4/Types/Classes/gsmBaseRequestsHandler.cs
- WolvenKit.RED4/Types/Classes/inkAdditionalContentPurchaseCallback.cs
- WolvenKit.RED4/Types/Classes/inkAdditionalContentStatusUpdateCallback.cs
- WolvenKit.RED4/Types/Classes/inkCursorInfo.cs
- WolvenKit.RED4/Types/Classes/inkISystemRequestsHandler.cs
- WolvenKit.RED4/Types/Classes/inkLanguageSpecificImagData.cs
- WolvenKit.RED4/Types/Classes/inkLanguageSpecificImageController.cs
- WolvenKit.RED4/Types/Classes/questInjectLoot_NodeType.cs
- WolvenKit.RED4/Types/Classes/questInjectLoot_NodeTypeParams.cs
- WolvenKit.RED4/Types/Classes/questInjectLoot_NodeTypeParams_OperationData.cs
- WolvenKit.RED4/Types/Classes/saveMetadata.cs
- WolvenKit.RED4/Types/Classes/saveMetadataContainer.cs
- WolvenKit.RED4/Types/Enums/cp77enums.cs
> Updated RTTI classes for 1.63

- WolvenKit/Resources/Scripts/Wolvenkit_FileValidation.wscript
> typo fixes, more workaround application

- WolvenKit/Resources/Scripts/Wolvenkit_FileValidation.wscript
fixed a typo in mesh material validation
> fixed a typo

- WolvenKit/Resources/Scripts/Wolvenkit_FileValidation.wscript
- WolvenKit/Resources/Scripts/hook_settings.wscript
made validation less verbose&more configurable
> made validation less verbose&more configurable

- WolvenKit/Resources/Scripts/Wolvenkit_FileValidation.wscript
- WolvenKit/Resources/Scripts/hook_global.wscript
Changed check for appearance in mesh files
> changed check logic for mesh file appearances

- WolvenKit/Resources/Scripts/Wolvenkit_FileValidation.wscript
- WolvenKit/Resources/Scripts/hook_global.wscript
- WolvenKit/Resources/Scripts/hook_settings.wscript
Added a setting to disable file validation via hooks file and a debug output to tell the user about it
> more file validation

- WolvenKit.Common/RED4/CR2W/JSON/Simples.cs
- WolvenKit.RED4/Archive/Buffer/AnimFacialSetupBakedDataBuffer.cs
- WolvenKit.RED4/Archive/Buffer/AnimFacialSetupCorrectivePosesDataBuffer.cs
- WolvenKit.RED4/Archive/Buffer/AnimFacialSetupMainPosesDataBuffer.cs
- WolvenKit.RED4/Archive/Buffer/AnimFacialSetupPosesDataBuffer.cs
- WolvenKit.RED4/Archive/Buffer/FoliageBuffer.cs
- WolvenKit.RED4/Archive/Helper/BufferHelper.cs
- WolvenKit.RED4/Archive/IO/AnimFacialSetupBakedDataReader.cs
- WolvenKit.RED4/Archive/IO/AnimFacialSetupBakedDataWriter.cs
- WolvenKit.RED4/Archive/IO/AnimFacialSetupCorrectivePosesDataReader.cs
- WolvenKit.RED4/Archive/IO/AnimFacialSetupCorrectivePosesDataWriter.cs
- WolvenKit.RED4/Archive/IO/AnimFacialSetupMainPosesDataReader.cs
- WolvenKit.RED4/Archive/IO/AnimFacialSetupMainPosesDataWriter.cs
- WolvenKit.RED4/Archive/IO/CR2WWriter.File.cs
- WolvenKit.RED4/Archive/IO/FoliageReader.cs
- WolvenKit.RED4/Archive/IO/FoliageWriter.cs
More buffers
Implemented:
- Reading/Writing of `worldFoliageCompiledResource` buffers (could be wrong)
- Reading/Writing of `animFacialSetup` buffers based on Loomys research
> More buffers

- WolvenKit/Resources/Scripts/Wolvenkit_FileValidation.wscript
- WolvenKit/Resources/Scripts/hook_global.wscript
- WolvenKit/Resources/Scripts/hook_settings.wscript
file validation will yell about inplaceResources in .ent files now, since these will cause crashes
> File validation changes

- WolvenKit/Views/Tools/RedTreeView.xaml.cs
implemented drag&drop for multiple nodes. Tested and works in json and mesh, would expect it to work in other file types
> drag&drop for multiple nodes

- WolvenKit/Resources/Scripts/Wolvenkit_FileValidation.wscript
- WolvenKit/Resources/Scripts/hook_global.wscript
- WolvenKit/Resources/Scripts/hook_settings.wscript
learned a new thing about mesh materials: they need to start with a lowercase letter (no _ or number) or they won't load
> material name validation

- WolvenKit/Resources/Scripts/Wolvenkit_FileValidation.wscript
- WolvenKit/Resources/Scripts/hook_settings.wscript
mesh file: validating external material paths on save
> file validation for external material paths

- WolvenKit/Resources/Scripts/Wolvenkit_FileValidation.wscript
- WolvenKit/Resources/Scripts/hook_global.wscript
- WolvenKit/Resources/Scripts/hook_settings.wscript
better warning for "appearance not found" in root entity file 
better warning for "appearance not found" in mesh entity file
> allow spaces in component names without meshes in root ent

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
partsValues will now show depot path
> partsValues will now show depot path

- WolvenKit/Resources/Scripts/Export_Ent.wscript
Implemented:
- Fixed a stupid bug. forgot a wkit. on a call
- 
Fixed:
- Entity export script not working
> Fix the Entity export script (Missing wkit. on a call)

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
Implemented:
- copy tweakxl to clipboard menu option
> feat: copy tweakxl to clipboard

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
please check if that's a problem
Fixed:
- do not clear pasted chunk clipboard
closes #1286
> fix: do not clear pasted chunk clipboard

- WolvenKit/Resources/Scripts/Wolvenkit_FileValidation.wscript
- WolvenKit/Resources/Scripts/hook_settings.wscript
See https://discord.com/channels/717692382849663036/786891742829215745/1168640169914675272 for context
> component IDs: check if they're unique and even

- WolvenKit/Resources/Scripts/Export_Mesh.wscript
- WolvenKit/Resources/Scripts/Export_Sector.wscript
> export_mesh and export_sector

- WolvenKit.App/ViewModels/Importers/ImportViewModel.cs
> Filtering masklist pngs from import tool view

- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
Could maybe someone who knows how to do that hook up the GUI so that the descriptor changes? It's currently too much for my brane.
Otherwise, I'm fine with having an un-documented feature :D
> holding shift: copy absolute instead of relative path

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
two more display properties for workspot items
> two more display properties for workspot items

- Tests/WolvenKit.FunctionalTests/ModKitTests.cs
- Tests/WolvenKit.UnitTests/TexconvTests.cs
- WolvenKit.App/Helpers/ImageDecoder.cs
- WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
- WolvenKit.App/ViewModels/Documents/RDTTextureViewModel.cs
- WolvenKit.App/ViewModels/Documents/RDTWidgetViewModel.cs
- WolvenKit.CLI/Commands/ExportCommand.cs
- WolvenKit.CLI/Commands/UncookCommand.cs
- WolvenKit.CLI/appsettings.json
- WolvenKit.Common/DDS/DDSUtils.cs
- WolvenKit.Common/DDS/Texconv.cs
- WolvenKit.Common/Interfaces/IModTools.cs
- WolvenKit.Common/Model/Arguments/ExportArgs.cs
- WolvenKit.Common/Model/Arguments/ImportArgs.cs
- WolvenKit.Common/RED4/RedImage.cs
- WolvenKit.Modkit/RED4/Import.cs
- WolvenKit.Modkit/RED4/Tasks/ExportTask.cs
- WolvenKit.Modkit/RED4/Tasks/IConsoleFunctions.cs
- WolvenKit.Modkit/RED4/Tasks/UncookTask.cs
- WolvenKit.Modkit/RED4/Tools/MlmaskTools.cs
- WolvenKit.Modkit/RED4/Uncook.cs
remove flip args
Fixed:
- always flip xbms on export
- remove manual flip options
> always flip xbms on export

- WolvenKit.App/Controllers/RED4Controller.cs
- WolvenKit.App/Models/FancyProjectObject.cs
- WolvenKit.App/Models/ProjectManagement/CP77Mod.cs
- WolvenKit.App/Models/ProjectManagement/IRecentlyUsedItemsService.cs
- WolvenKit.App/Models/ProjectManagement/Project/Cp77Project.cs
- WolvenKit.App/Models/ProjectManagement/RecentlyUsedItemModel.cs
- WolvenKit.App/Models/ProjectManagement/RecentlyUsedItemsService.cs
- WolvenKit.App/Services/ISettingsDto.cs
- WolvenKit.App/Services/ProjectManager.cs
- WolvenKit.App/Services/SettingsDto.cs
- WolvenKit.App/Services/SettingsManager.cs
- WolvenKit.App/ViewModels/Dialogs/NewFileViewModel.cs
- WolvenKit.App/ViewModels/Dialogs/ProjectWizardViewModel.cs
- WolvenKit.App/ViewModels/HomePage/Pages/WelcomePageViewModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit/Views/Dialogs/ProjectSettingsDialog.xaml
- WolvenKit/Views/Dialogs/ProjectSettingsDialog.xaml.cs
- WolvenKit/Views/Dialogs/ProjectWizardView.xaml
- WolvenKit/Views/Dialogs/ProjectWizardView.xaml.cs
- WolvenKit/Views/HomePage/Pages/WelcomePageView.xaml
- WolvenKit/Views/HomePage/Pages/WelcomePageView.xaml.cs
Project refactor
Implemented:
- Pinning of projects at the Welcome screen
- Sorting of projects at the Welcome screen
- Filtering by project name
- New project field (`ModName`) which affects RedMod/Archive name and is changeable
> Project refactor

- WolvenKit.App/ViewModels/Importers/ImportViewModel.cs
> import tool: hiding filter logic

- WolvenKit.App/ViewModels/Tools/ImportableItemViewModel.cs
- WolvenKit.Common/RED4/CommonFunctions.cs
Minor refactoring for better guessing of default texture import settings from file name
> better guessing of default import settings from xbm's filename

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
fixed bug in mesh where updating a chunkName in an appearance would collapse the array
> show values for .csv and .json, fix bug in .mesh

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
> ChunkViewModel: more Value/Descriptor display

- WolvenKit.App/ViewModels/Tools/ChunkViewModel.ExpansionStates.cs
> Chunkviewmodel: recursive unfolding of tags

- WolvenKit.App/ViewModels/Documents/RDTTextureViewModel.cs
- WolvenKit.App/ViewModels/Tools/ImportableItemViewModel.cs
- WolvenKit.Common/DDS/Texconv.cs
- WolvenKit.Common/DDS/TexconvNative.cs
- WolvenKit.Common/RED4/RedImage.Lut.cs
- WolvenKit.Common/RED4/RedImage.cs
- WolvenKit.Core/Enums.cs
- WolvenKit.Modkit/RED4/Import.cs
- WolvenKit.Modkit/RED4/Uncook.cs
- WolvenKit/Views/Documents/RDTTextureView.xaml
- LUT preview / PNG export now generates a Hald8 image
- Added import/export for LUT cube files
**Fixed:**
- 3D Textures generating wrong XBM metadata
> LUT improvements

- WolvenKit.Common/RED4/CommonFunctions.cs
- Added "overlay" and "alpha" to file name partials that should default to transparency on
> guess premultiplyAlpha from filename: consider overlay/alpha

- WolvenKit.App/ViewModels/Tools/ChunkViewModel.ExpansionStates.cs
- WolvenKit.App/ViewModels/Tools/ImportExportItemViewModel.cs
- WolvenKit.Common/Model/Arguments/ImportArgs.cs
- WolvenKit/Views/Exporters/ExportView.xaml
- WolvenKit/Views/Importers/TextureImportView.xaml
> Import export tooltip

- WolvenKit.Modkit/RED4/Tools/Animation/AnimSIMD.cs
> fix(anims/simd): Don't Try to Export Alignment Padding..

- WolvenKit/Views/Tools/PropertiesView.xaml
#image preview zoom to extent by default
closes #1552
> #1552 image preview zoom to extent by default

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
This has been requested and tested by sketchcritic - there were no exceptions that they reported :)
> Animgraph ragdoll nodenames

- WolvenKit.App/ViewModels/Documents/RedDocumentTabViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit/App.xaml
- WolvenKit/Views/Tools/RedTreeView.xaml
> #1540 overwrite array/buffer with selection

- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit/Views/Tools/ProjectExplorerView.xaml
> #1557 overwrite with gamefile

- WolvenKit/Views/Templates/RedRefEditor.xaml
- WolvenKit/Views/Templates/RedTypeView.xaml
- WolvenKit/Views/Templates/RedVector2Editor.xaml
- WolvenKit/Views/Templates/RedVector3Editor.xaml
- WolvenKit/Views/Templates/RedVector4Editor.xaml
Tried to make tabbing between different fields in the property editor more comfortable.
I have existential questions now
> some tabbing behaviour changes

- WolvenKit.Modkit/RED4/Tools/MeshImportTools.cs
- preserving mesh chunk render flags from source mesh
> Mesh fixes

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.ExpansionStates.cs
> expansion states and descriptors for effect stuff

- WolvenKit.App/ViewModels/Documents/RDTDataViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.ExpansionStates.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
Updating NodeIndexInParent doesn't seem to work reliably, and synchronizing the selection between the tab and ChunkView doesn't seem to work properly either...?
> Duplicate/Delete: Node selection shenanigans

- WolvenKit.App/ViewModels/Tools/ImportableItemViewModel.cs
Setting default compression mode for normal map
resolved a few todos
> Setting default compression mode for normal map

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
> added copy array content command

- WolvenKit.Modkit/RED4/Import.cs
This is the #1 import error that makes people ask on Discord, and it's so easy to circumvent :D
> mesh import: better error message

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.Descriptor.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.Value.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
> Added node descriptor fallback for worldNodes

- WolvenKit.App/ViewModels/Tools/ChunkViewModel.Value.cs
- WolvenKit/Converters/RedEditorTemplateSelector.cs
- WolvenKit/Views/Templates/RedTypeView.xaml
- WolvenKit/Views/Templates/RedVectorColorEditor.xaml
- WolvenKit/Views/Templates/RedVectorColorEditor.xaml.cs
> RGB colour picker for BaseColorScale

- WolvenKit.App/ViewModels/Dialogs/SearchAndReplaceDialogViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.Descriptor.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.SearchAndReplace.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.Value.cs
- WolvenKit/GenericHost.cs
- WolvenKit/Layout/TextBoxBehavior.cs
- WolvenKit/Views/Dialogs/Windows/SearchAndReplaceDialogView.xaml
- WolvenKit/Views/Dialogs/Windows/SearchAndReplaceDialogView.xaml.cs
- WolvenKit/Views/Documents/RedDocumentView.xaml
- WolvenKit/Views/Tools/AssetBrowserView.xaml.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
Fixed an exception on startup by null-checking, while I was at it
> implemented "search and replace" in editor view. seems to work???

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
> brought chunk view model type back

- WolvenKit.App/ViewModels/Tools/ChunkViewModel.SearchAndReplace.cs
- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
> fixed export error for appearances without chunks

- WolvenKit.App/ViewModels/Dialogs/TypeSelectorDialogViewModel.cs
- WolvenKit.Common/RED4/CR2W/JSON/PrimitiveConverter.cs
- WolvenKit.RED4/Types/Primitives/CHandle.cs
- WolvenKit.RED4/Types/Primitives/CWeakHandle.cs
- WolvenKit.RED4/Types/RedBaseClass.cs
- WolvenKit.RED4/Types/Reflection/ExtendedPropertyInfo.cs
- WolvenKit/Views/Dialogs/TypeSelectorDialog.xaml
- WolvenKit/Views/Dialogs/TypeSelectorDialog.xaml.cs
- Better handling of dynamic classes in handles/weakhandled
**Fixed:**
- Small issues with creating custom types in the Type Selector
> Dynamic class improvements

- WolvenKit.App/Helpers/StringHelper.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.Descriptor.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.Value.cs
> Descriptors+Values in ChunkViewModel

- WolvenKit.App/Interaction/Interactions.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.SearchAndReplace.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit/Views/Dialogs/InputDialogView.xaml
- WolvenKit/Views/Dialogs/InputDialogView.xaml.cs
- WolvenKit/Views/Dialogs/Windows/SearchAndReplaceDialogView.xaml
- WolvenKit/Views/Dialogs/Windows/SearchAndReplaceDialogView.xaml.cs
- WolvenKit/Views/Tools/ProjectExplorerView.xaml
- WolvenKit/Views/Tools/ProjectExplorerView.xaml.cs
minor refactoring & code style
> ProjectExplorer: added "Create new folder" to context menu

- WolvenKit.App/Helpers/StringHelper.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.Descriptor.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.Value.cs
> descriptor+value for gameBinkVideoRecord

- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.SearchAndReplace.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
> ChunkViewModel: Delete unused materials

- WolvenKit.App/Services/AppScriptService.Hook.cs
- WolvenKit.RED4/Archive/IO/CR2WReader.cs
- WolvenKit.RED4/Archive/IO/RedPackageReader.cs
- WolvenKit.RED4/Types/ClassesExt/CustomData/worldCompiledEffectInfo.cs
- WolvenKit.RED4/Types/Exceptions/MissingRTTIException.cs
- WolvenKit.RED4/Types/Helper/ErrorHandling.cs
- WolvenKit.RED4/Types/Interfaces/IRedCompiledPropertyData.cs
- WolvenKit.RED4/Types/TypeGlobal.cs
> Improved CR2W handling

- WolvenKit.App/ViewModels/Tools/ChunkViewModel.Value.cs
> fixed value being overwritten

- WolvenKit.App/ViewModels/Tools/ChunkViewModel.SearchAndReplace.cs
> fixed a premature return in array search&replace

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
fixed a bug when duplicating the last chunk in an array
> fixed duplication index flip

- WolvenKit.App/Helpers/StringHelper.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.ExpansionStates.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.SearchAndReplace.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.UserInteractionStates.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.Value.cs
> hiding nodes in .app and .ent

- WolvenKit.Core/Enums.cs
- As of now there is no way to access Ukrainian localization. This change adds a way for Ukrainian to be set in the settings for LocKey.
> Add Ukrainian to the LocKey settings

- WolvenKit.App/Services/ISettingsManager.cs
- WolvenKit.Core/Constants.cs
- WolvenKit.Core/Exceptions/WolvenKitException.cs
- WolvenKit.Core/Interfaces/ILoggerService.cs
- WolvenKit.Core/Services/SerilogWrapper.cs
- WolvenKit/App.xaml.cs
- WolvenKit/Converters/NullVisibilityConverter.cs
- WolvenKit/Helpers/LogCodeHelper.cs
- WolvenKit/Views/Tools/LogView.xaml
- WolvenKit/Views/Tools/LogView.xaml.cs
- Faster logging for GUI
- Added info codes to log messages & linking them to URLs (GUI only)
- Added a button to the log view to enable/disable autoscroll
- Added a button to the log view to open the logs folder
- Added a button to the log lines to copy the specific line to the Clipboard (including MarkDown for CodeBlocks. Should be fine for GH & Discord)
- Moved Logs to its own subfolder under AppData
Due to changing the output to TextBlocks for faster rendering, it isn't possible anymore to select and copy text from the view anymore
> refactor(LogView): Improved performance & usability?

- WolvenKit.App/Helpers/StringHelper.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.ExpansionStates.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.UserInteractionStates.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.Value.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
> fixed "copy absolute path to raw"

- WolvenKit.App/ViewModels/GraphEditor/Nodes/NodeProperties.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questAudioNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questConditionNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questEnvironmentManagerNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questEventManagerNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questJournalNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questPauseConditionNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questRenderFxManagerNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questSceneManagerNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questTeleportPuppetNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questTimeManagerNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questUIManagerNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questUseWorkspotNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Scene/Internal/BaseSceneViewModel.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Scene/scnChoiceNodeWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Scene/scnQuestNodeWrapper.cs
Added node properties to graph editor for scenes and quests, currently not all, but some most common
> Graph nodes properties

- WolvenKit/App.xaml
- WolvenKit/Views/Templates/RedRefEditor.xaml
- WolvenKit/Views/Templates/RedRefEditor.xaml.cs
- WolvenKit/Views/Templates/TruncatingTextBox.xaml
- WolvenKit/Views/Templates/TruncatingTextBox.xaml.cs
... for depot paths. 
https://github.com/WolvenKit/WolvenKit/assets/965785/f357dc2e-fb38-4894-8bdf-842db59b1a2c
> Truncating text box for DepotPath

- WolvenKit/Helpers/UIExtensions.cs
- WolvenKit/Views/Templates/RedRefEditor.xaml
- WolvenKit/Views/Templates/TrimmingTextBox.xaml
- WolvenKit/Views/Templates/TrimmingTextBox.xaml.cs
> Alternative TrimmingTextBox

- WolvenKit.App/ViewModels/Tools/ChunkViewModel.UserInteractionStates.cs
Deceptious found out that we can't disable _all_ buffers: 
https://discord.com/channels/717692382849663036/808086068023918603/1232806133496938547
> removed write protection from arrays of buffers

- WolvenKit.App/ViewModels/Documents/RDTDataViewModel.cs
- WolvenKit.App/ViewModels/Documents/RDTInkTextureAtlasViewModel.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.ExpansionStates.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.UserInteractionStates.cs
- WolvenKit/Views/Documents/RDTWidgetView.xaml.cs
https://github.com/WolvenKit/WolvenKit/assets/965785/0f6927f0-40fb-4d03-ad69-966f23f9ace6
> InkAtlasPreview: changing SlotName should update model

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.UserInteractionStates.cs
> 1655 fixed missing refresh after delete

- WolvenKit.App/Controllers/RED4Controller.cs
- WolvenKit.App/Factories/DocumentViewmodelFactory.cs
- WolvenKit.App/Models/FileModel.cs
- WolvenKit.App/Models/FileSystemArchive.cs
- WolvenKit.App/Models/ProjectManagement/Project/Cp77Project.cs
- WolvenKit.App/Services/HashServiceExt.cs
- WolvenKit.App/Services/ProjectManager.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.Value.cs
- WolvenKit.Common/Services/HashService.cs
- WolvenKit.Common/Services/TweakDBService.cs
- WolvenKit.Core/Services/IHashService.cs
- WolvenKit.RED4/Archive/Base/FileEntry.cs
- WolvenKit.RED4/Archive/IO/ArchiveReader.cs
- WolvenKit.RED4/Archive/IO/ArchiveWriter.cs
- WolvenKit.RED4/Archive/IO/RedPackageWriter.File.cs
- WolvenKit.RED4/TweakDB/Helper/TweakDBStringHelper.cs
- WolvenKit.RED4/Types/Helper/ImportHandler.cs
- WolvenKit.RED4/Types/Pools/CNamePool.cs
- WolvenKit.RED4/Types/Pools/NodeRefPool.cs
- WolvenKit.RED4/Types/Pools/ResourcePathPool.cs
- WolvenKit.RED4/Types/Pools/TweakDBIDPool.cs
- WolvenKit.RED4/Types/Primitives/Simples/CName.cs
- WolvenKit.RED4/Types/Primitives/Simples/ResourcePath.cs
- WolvenKit.RED4/Types/Primitives/Simples/TweakDBID.cs
- WolvenKit/GenericHost.cs
- WolvenKit/Views/Shell/MainView.xaml.cs
- WolvenKit/Views/Tools/HashToolView.xaml.cs
refactor(HashService): Redone storing of custom hashes
- Refactored storing of custom resourcePath hashes
- Added support for custom TweakDbIds
> refactor(HashService): Redone storing of custom hashes

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
fix(GUI): Fix crash while removing TreeView items
Fixed:
- Crash while removing TreeView items
> fix(GUI): Fix crash while removing TreeView items

- WolvenKit.App/ViewModels/Tools/ChunkViewModel.SearchAndReplace.cs
> search&replace: don't abort

- WolvenKit/Views/Tools/ProjectExplorerView.xaml.cs
Event used to fire twice; second time around, the expanded properties aren't set, and the tree collapses. Now it doesn't do that anymore.
> fixed project explorer collapse on save

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.Descriptor.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.Value.cs
at least for entMeshComponents
> depot path will update parent value

- WolvenKit.App/Models/SubmeshComponent.cs
- WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
**Fixed:**
The actor bit of the log message wasnt triggering in my testing, added a second test that does. Didn't take the first out as I wasn't sure if there is another case I'm just missing.
> First actor test isnt triggering most of the time, this seems to.

- WolvenKit.App/Scripting/AppScriptFunctions.cs
- WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
- WolvenKit/Helpers/LogCodeHelper.cs
Adds FileExistsInRaw function to wscript so you can check if a file is in the raw folders
closes_issue_number 1676
> Add FileExistsInRaw function to see if a file is in the raw folders.

- WolvenKit.Modkit/Managers/ArchiveManager.cs
- WolvenKit/Views/Tools/AssetBrowserView.xaml
Is it right now? I'm confussed -.-
> fix(ArchiveManager): Load order again?

- WolvenKit.App/ViewModels/Tools/TweakBrowserViewModel.cs
- WolvenKit/Views/Tools/TweakBrowserView.xaml
> Added "Copy Tweak Name" to Tweak Browser

- WolvenKit.RED4/Archive/IO/CR2WReader.cs
- WolvenKit.RED4/Archive/IO/RedPackageReader.cs
Solves an issue introduced with #1620 for files from old game versions.
> fix(CR2W): Try to read the CR2W defined type before the RTTI one

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.ContextMenu.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.Value.cs
> CVM: fixed parent descriptor refresh

- WolvenKit.App/Factories/DocumentTabViewmodelFactory.cs
- WolvenKit.App/Factories/IDocumentTabViewmodelFactory.cs
- WolvenKit.App/ViewModels/Documents/RDTInkTextureAtlasViewModel.cs
- WolvenKit.App/ViewModels/Documents/RDTLayeredPreviewViewModel.cs
- WolvenKit.App/ViewModels/Documents/RDTTextureViewModel.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewModel.cs
- WolvenKit.Common/RED4/RedImage.cs
- WolvenKit/Views/Documents/RDTInkAtlasView.xaml
- WolvenKit/Views/Documents/RDTInkAtlasView.xaml.cs
- WolvenKit/Views/Documents/RDTLayeredTextureView.xaml
- WolvenKit/Views/Documents/RDTLayeredTextureView.xaml.cs
- WolvenKit/Views/Documents/RDTTextureView.xaml
- WolvenKit/Views/Documents/RDTTextureView.xaml.cs
- WolvenKit/Views/Documents/RedDocumentView.xaml
- WolvenKit/Views/Others/ImageCanvas.xaml
- WolvenKit/Views/Others/ImageCanvas.xaml.cs
- WolvenKit/Views/Tools/PropertiesView.xaml
- WolvenKit/Views/Tools/PropertiesView.xaml.cs
Refactored texture preview
- Removed InkAtlas info panel for non InkAtlas files
- InkAtlas: Added Slot selection in preview
- InkAtlas: Cleaned up property grid
- MultiLayer_Mask: Merged image tabs to single Tab
- MultiLayer_Mask, CTextureArray, CReflectionProbeDataResource: Show preview of all layers
> refactor(TexturePreview): Refactored texture preview

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.Descriptor.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.Value.cs
> default values for cvm Multilayer_Layer

- WolvenKit.App/ViewModels/Tools/ChunkViewModel.SearchAndReplace.cs
Fixed search and replace not working for arrays of CNames
> fixed search and replace (again)

- WolvenKit.Modkit/Resources/ArchiveXlHelper.cs
> fixed dynamic material export path -.-

- WolvenKit.Modkit/RED4/Tools/Common/MaterialExtractor.cs
> fixed index bug with material export

- WolvenKit/Views/Tools/RedTreeView.xaml.cs
double click on collapsed element will collapse all of its siblings
> usability: cvm doubleclick behaviour

- WolvenKit.App/ViewModels/Documents/DocumentViewModel.cs
- WolvenKit.App/ViewModels/Documents/IDocumentViewModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.App/ViewModels/Shell/RibbonViewModel.cs
> pop-up: save dirty files before packing/launching

- WolvenKit.App/ViewModels/Documents/RedDocumentTabViewModel.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewModel.cs
- WolvenKit/Views/Documents/RedDocumentView.xaml
Added possibility to extract/save embedded files in the CR2WEditor view.
> feature(CR2WEditor): Added possibility to extract/save embedded files in the CR2WEditor view.

- WolvenKit/Views/Tools/ProjectExplorerView.xaml.cs
Fixes ProjectExplorer refreshing to often
> Fixes ProjectExplorer refreshing to often

- WolvenKit.App/Models/FileModel.cs
- WolvenKit/Views/Tools/ProjectExplorerView.xaml
- WolvenKit/Views/Tools/ProjectExplorerView.xaml.cs
> file size in file explorer's flat view

- WolvenKit/Views/Dialogs/Windows/RenameDialog.xaml.cs
Folder rename wouldn't select the last character. Now it does!
> fix index offset for folder rename

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
CKeyValuePair descriptor will refresh again on update of the name
> CKeyValuePairs will refresh their descriptor again

- WolvenKit.RED4/Archive/Buffer/FoliageBuffer.cs
- WolvenKit.RED4/Archive/IO/FoliageReader.cs
- WolvenKit.RED4/Archive/IO/FoliageWriter.cs
Fixed cfoliage buffer layout
**Fixed:**
- cfoliage buffer layout. Credits to @kmirea
> Fixed cfoliage buffer layout

- WolvenKit.Common/Services/LocKeyService.cs
> Removed storing values by secundary key, since it can be empty.

- WolvenKit.App/ViewModels/Tools/ChunkViewModel.ContextMenu.cs
will now mark parent tab as dirty and replace material name in chunkMaterials
> rename material now works properly

- WolvenKit.App/ViewModels/Tools/ChunkViewModel.Descriptor.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.SearchAndReplace.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.UserInteractionStates.cs
simple mode was hiding non-empty arrays, it'll no longer do that
> fixed simple mode hiding for non-empty arrays

- WolvenKit.App/ViewModels/Tools/ExportableItemViewModel.cs
- WolvenKit.Core/Enums.cs
Add 2wmesh to export 
Added w2mesh to the enum of files that can be exported and the exportArgs switch.
**Fixed:**
fixes 1424
> Add w2mesh to the list of types that can be exported.

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
appearance components: will no longer expand the entire array when depot path is updated
meshMaterialDefinitions: will now update name
> fixed property name calculation for components+appearances

- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
> trying to save without a project will now show an annoying popup

- WolvenKit.App/ViewModels/GraphEditor/RedGraph.cs
- WolvenKit/Views/Documents/RDTGraphView2.xaml.cs
- WolvenKit/Views/GraphEditor/GraphEditorView.xaml
- WolvenKit/Views/GraphEditor/GraphEditorView.xaml.cs
Some features from issue #1737 
Added saving state of graph editor.
Added editor centering on selected node when clicking on "Arrange Items".
> Graph editor save state

- WolvenKit/Views/Tools/ProjectExplorerView.xaml.cs
Fixed sorting in ProjectExplorer
> fix(ProjectExplorer): Fixed sorting

- WolvenKit.RED4/Types/Pools/NodeRefPool.cs
**Fixed:**
- Fixes erroneous handling of non-noderef type strings
> Fixes erroneous handling of non-noderef strings

- WolvenKit.App/Factories/ChunkViewmodelFactory.cs
- WolvenKit.App/ViewModels/Documents/RDTDataViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModel.ExpansionStates.cs
.mi files will now automatically expand their `values` array
first commit only contains automatic refactors
> CVM: default expansion state on first open

- WolvenKit.App/Factories/DocumentTabViewmodelFactory.cs
- WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
- WolvenKit/Views/Documents/RDTMeshView.xaml
- WolvenKit/Views/Documents/RDTMeshView.xaml.cs
Added "copy appearance name" button
"Generate Materials" button will now display a different text when CTRL is pressed
Closes #1785
> MeshView: added copy appearance name button

- WolvenKit.App/Interaction/Interactions.cs
- WolvenKit.App/Services/ISettingsDto.cs
- WolvenKit.App/Services/SettingsDto.cs
- WolvenKit.App/Services/SettingsManager.cs
- WolvenKit.App/ViewModels/Dialogs/RenameDialogViewModel.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit/Views/Dialogs/Windows/RenameDialog.xaml
- WolvenKit/Views/Dialogs/Windows/RenameDialog.xaml.cs
- WolvenKit/Views/Tools/ProjectExplorerView.xaml.cs
> rename dialog will show refactoring checkbox

- WolvenKit.App/ViewModels/Dialogs/CreateMaterialsDialogViewModel.cs
- WolvenKit.App/ViewModels/Dialogs/SearchAndReplaceDialogViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit/GenericHost.cs
- WolvenKit/Views/Dialogs/Windows/CreateMaterialsDialog.xaml
- WolvenKit/Views/Dialogs/Windows/CreateMaterialsDialog.xaml.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
> mesh: generate missing materials (definitions+instances)

- WolvenKit.App/Controllers/IGameController.cs
- WolvenKit.App/Controllers/MockGameController.cs
- WolvenKit.App/Controllers/RED4Controller.cs
- WolvenKit.App/Models/LaunchProfile.cs
- WolvenKit.App/Models/ProjectManagement/Project/Cp77Project.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.Common/Interfaces/IModTools.cs
- WolvenKit.Modkit/RED4/ModTools.Helper.cs
#1723 Can now check a box to remove the `packed` folder after packing:
"Hot Reload" will now install all files, not just the .archive
> Delete packed folder, HotReload packs everything

- WolvenKit.App/Factories/IDialogViewModelFactory.cs
- WolvenKit.App/Scripting/ScriptDocumentWrapper.cs
- WolvenKit.App/Services/SettingsManager.cs
- WolvenKit.App/ViewModels/Documents/IDocumentViewModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
Applied a bunch of autocomplete-suggestions and fixed warnings.
Merge after https://github.com/WolvenKit/WolvenKit/pull/1793
> IntelliJ and OCD

- WolvenKit.App/Resources/launchprofiles.json
- WolvenKit.App/Services/ISettingsDto.cs
- WolvenKit.App/Services/ISettingsManager.cs
- WolvenKit.App/Services/SettingsDto.cs
- WolvenKit.App/Services/SettingsManager.cs
- WolvenKit.App/ViewModels/Dialogs/LaunchProfilesViewModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.App/ViewModels/Shell/RibbonViewModel.cs
- WolvenKit/Views/Shell/MainView.xaml.cs
- WolvenKit/Views/Shell/RibbonView.xaml.cs
Will use settings updater instead of a settings option to append default profiles
> Launchprofiles: Using settings manager

- WolvenKit.App/Controllers/IGameControllerFactory.cs
- WolvenKit.App/Controllers/RED4Controller.cs
- WolvenKit.App/Models/ProjectManagement/Project/Cp77Project.cs
- WolvenKit.App/Services/AppIdleStateService.cs
- WolvenKit.App/Services/SettingsDto.cs
- WolvenKit.App/Services/SettingsManager.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit/GenericHost.cs
- WolvenKit/Views/Shell/MainView.xaml.cs
- WolvenKit/Views/Tools/ProjectExplorerView.xaml
- WolvenKit/Views/Tools/ProjectExplorerView.xaml.cs
ProjectBrowser will remember open tab in the project settings
Added an idle timer with various debounces - project expansion states will be written every minute when WKit is idle
> Remember open tab; write project tree state on idle

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
> CVM: DisplayName property to make chunkMaterials show LODLevels

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
fix calculation of lod material index for chunkmasks
> Visibility fixes

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
Checking on interface types now (so what if there's an update too many)
> fix for cvm value update in parent/child

- WolvenKit.App/ViewModels/Documents/RDTDataViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Shell/GroupedChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.Descriptor.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.Value.cs
- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
Fixed an exception when deleting items
> Fixed an exception when deleting items

- WolvenKit.App/Models/TweakXL.cs
> #1842 fixed exception when exporting tweak override

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
> fixed mlsetup isDefault

- WolvenKit.App/Helpers/TypeHelper.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit/Helpers/LogCodeHelper.cs
The types might have to be fine-tuned at a later point
closes #1840
> 1840: Added type for sector nodes' node data buffers

- WolvenKit.App/Services/AppArchiveManager.cs
- WolvenKit.App/Services/ISettingsDto.cs
- WolvenKit.App/Services/SettingsDto.cs
- WolvenKit.App/Services/SettingsManager.cs
- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
- WolvenKit.Common/Interfaces/IArchiveManager.cs
- WolvenKit.Modkit/Managers/ArchiveManager.cs
- WolvenKit/Views/Tools/AssetBrowserView.xaml.cs
> Settings: exclude archives from scan

- WolvenKit.App/ViewModels/Documents/RDTGraphViewModel.cs
- WolvenKit.App/ViewModels/Documents/RDTInkTextureAtlasViewModel.cs
- WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
- WolvenKit.App/ViewModels/Documents/RDTTextureViewModel.cs
- WolvenKit.App/ViewModels/Documents/RDTWidgetViewModel.cs
- WolvenKit.Modkit/Managers/ArchiveManager.cs
- WolvenKit.sln.DotSettings
- WolvenKit/Views/Documents/RDTDataView.xaml.cs
- WolvenKit/Views/Documents/RDTGraphView.xaml
- WolvenKit/Views/Documents/RDTInkAtlasView.xaml
- WolvenKit/Views/Documents/RDTMeshView.xaml
- WolvenKit/Views/Documents/RDTTextureView.xaml
- WolvenKit/Views/Documents/RDTWidgetView.xaml
- WolvenKit/Views/Others/LoadingTextControl.xaml
- WolvenKit/Views/Others/LoadingTextControl.xaml.cs
I was initially looking into #1836, but couldn't reproduce.
> added 'Is Loading' text to a bunch of editors

- WolvenKit.App/Helpers/StringHelper.cs
- WolvenKit.App/Helpers/StringHelpers/StringHelperWorldNode.cs
- WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewToolbarModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
- WolvenKit/Views/Documents/RedDocumentViewToolbar.xaml
... and fixed asset browser search scope check
> moved menu entry into correct submenu

- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit.RED4/Types/RedBaseClass.Extra.cs
> handled reference replacements inside CKeyValuePairs

- Directory.Packages.props
- WolvenKit.App/Models/ProjectManagement/Project/Cp77Project.cs
- WolvenKit.App/Services/AppScriptService.Hook.cs
- WolvenKit.App/ViewModels/Importers/ImportViewModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit.Common/Tools/FileHelper.cs
- WolvenKit.sln
- WolvenKit/Helpers/ProjectResourceHelper.cs
- WolvenKit/Views/Exporters/ExportView.xaml
- WolvenKit/Views/Importers/TextureImportView.xaml
- WolvenKit/Views/Shell/MenuBarView.xaml
- WolvenKit/Views/Shell/MenuBarView.xaml.cs
- WolvenKit/Views/Templates/RedTypeView.xaml
- Wolvenkit.Test/App/Models/ProjectManagement/Project/Cp77ProjectTest.cs
- Wolvenkit.Test/Wolvenkit.Test.csproj
I also added a test project. Sue me :D
> Feature: run file validation on project

- WolvenKit.App/Helpers/TypeHelper.cs
- WolvenKit.App/Services/AppScriptService.cs
- WolvenKit.App/ViewModels/Dialogs/ScriptManagerViewModel.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
> Suspends file watcher while wscripts are running

- WolvenKit.Common/RED4/RedImage.cs
- WolvenKit.Modkit/RED4/Tools/MlmaskImportTools.cs
- WolvenKit/Helpers/LogCodeHelper.cs
closes #1865 (this was easier than expected)
> better logging for image import

- WolvenKit.App/Services/IWatcherService.cs
- WolvenKit.App/Services/WatcherService.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit/Views/Documents/RedDocumentViewToolbar.xaml.cs
> refactoring of filewatcher to singleton

- WolvenKit.App/ViewModels/Documents/DocumentViewModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.WScript.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit/Views/Shell/MenuBarView.xaml
- WolvenKit/Views/Shell/MenuBarView.xaml.cs
Will open a json file from the entspawners directory, copy it to raw and noodle it through the script. Not sure if all kinks are ironed out, will require testing.
> feature: import entspawner json

- WolvenKit.App/Helpers/ProjectResourceHelper.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit.Modkit/Managers/ArchiveManager.cs
- WolvenKit/Views/Documents/RedDocumentViewToolbar.xaml.cs
- WolvenKit/Views/Shell/DockingAdapter.xaml.cs
Fixed loading of redmods and file warnings - works now
> fixed redmods not showing up in mod browser

- WolvenKit.App/ViewModels/Documents/RedDocumentViewToolbarModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.Value.cs
- WolvenKit/Views/Documents/RedDocumentViewToolbar.xaml
- WolvenKit/Views/Documents/RedDocumentViewToolbar.xaml.cs
> Mesh: clean up (delete empty submeshes)

- WolvenKit.Modkit/Managers/ArchiveManager.cs
- WolvenKit.sln.DotSettings
ArchiveManager will now check for existence of /mods before trying to iterate it
closes #1881
> fixed exception if there's no redmod mod dir in the game folder

- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
> fix: #1878 better exception

- WolvenKit/Views/Dialogs/ScriptManagerView.xaml
fixed the script manager getting narrower each time you open it
> fixed #1892

- WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
using local materials array instead of mesh.materials
> fixed #1860

- WolvenKit.App/ViewModels/Documents/RDTDataViewModel.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
> #1483 partmapping reload on inktexture change

- WolvenKit.App/ViewModels/Dialogs/ChangeComponentChunkMaskDialogViewModel.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewToolbarModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.ContextMenu.cs
- WolvenKit/Themes/App.Styles.xaml
- WolvenKit/Views/Dialogs/Windows/ChangeComponentChunkMaskDialog.xaml
- WolvenKit/Views/Dialogs/Windows/ChangeComponentChunkMaskDialog.xaml.cs
- WolvenKit/Views/Documents/RedDocumentViewToolbar.xaml
- WolvenKit/Views/Documents/RedDocumentViewToolbar.xaml.cs
- WolvenKit/Views/Templates/RedChunkMaskEditor.xaml.cs
I wasn't gonna edit 160+ appearances by hand, and json edit didn't work since another component had to have this appearance
> changing chunkmask by component name

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
> fix #1908 (sector node data index)

- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.Value.cs
> fixed #1918

- WolvenKit.App/Helpers/ProjectResourceHelper.cs
- WolvenKit.App/ViewModels/Exporters/AbstractImportExportViewModel.cs
- WolvenKit/Views/Exporters/ExportView.xaml.cs
- WolvenKit/Views/Importers/ImportView.xaml.cs
> fixed #1917

- WolvenKit.App/Services/WatcherService.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewToolbarModel.cs
- WolvenKit.Common/Tools/FileHelper.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
when trying to rename a folder to something that contained the folder's name
> fixed folder recursion from hell

- WolvenKit.App/ViewModels/GraphEditor/Nodes/Scene/scnChoiceNodeWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/RedGraph.Scene.cs
> SceneEditor: Fixed scnChoiceNode creation and adding new opions

- WolvenKit/Views/Tools/RedTreeView.xaml.cs
> #1819 fixed drag&drop being all over the place

- WolvenKit.App/Services/AppArchiveManager.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
- WolvenKit.Common/Interfaces/IArchiveManager.cs
- WolvenKit.Modkit/Managers/ArchiveManager.cs
- WolvenKit.Modkit/RED4/Tasks/ConflictsTask.cs
- WolvenKit.RED4/Types/ClassesExt/meshMeshMaterialBuffer.cs
- WolvenKit.sln.DotSettings
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
- WolvenKit/Views/Tools/AssetBrowserView.xaml.cs
If you have an .archive file selected, or if you have a search filtering for archive(s), WKit will only scan the corresponding archive file(s)
> mod archive: scanning single item

- WolvenKit.App/Services/GeometryCacheService.cs
- WolvenKit.App/ViewModels/Dialogs/SoundModdingViewModel.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/NodeProperties.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.Core/Compression/Oodle.cs
- WolvenKit.Modkit/RED4/Tasks/UncookTask.cs
- WolvenKit.RED4/Archive/IO/CGIDataReader.cs
- WolvenKit.RED4/Types/Classes/ButtonCursorStateView.cs
- WolvenKit/App.xaml.cs
> if we close these, we can all go home

- WolvenKit.App/Services/ISettingsDto.cs
- WolvenKit.App/Services/SettingsDto.cs
- WolvenKit.App/Services/SettingsManager.cs
- WolvenKit/ViewModels/SettingsPageViewModel.cs
- WolvenKit/Views/HomePage/Pages/SettingsPageView.xaml.cs
Remove unused variables.
Bind SaveClose command from View like other commands, and remove old declaration from ViewModel.
Reorganize settings by region based on groups.
> Clean code related to Settings

- WolvenKit.App/ViewModels/Tools/PropertiesViewModel.cs
> WIP: Trying to enable .inkatlas previews

- WolvenKit.App/ViewModels/Documents/RDTWidgetViewModel.cs
- WolvenKit/Themes/App.Styles.xaml
- WolvenKit/Views/Documents/RDTWidgetView.xaml
- WolvenKit/Views/Documents/RDTWidgetView.xaml.cs
This does not actually overlay any grids yet. Turns out that we talked straight past each other.
> #1965 pixel grid snapping

- WolvenKit/Converters/RedEditorTemplateSelector.cs
- WolvenKit/Views/Templates/RedTypeView.xaml
- WolvenKit/Views/Templates/RedVector2Editor.xaml.cs
- add template selector with type check
- clean unused directive
- clean redundant cast
Closes #1986
> Added support for RedVector2Editor

- WolvenKit.App/Helpers/StringHelper.cs
- WolvenKit.App/ViewModels/Documents/RDTDataViewModel.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentTabViewModel.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewToolbarModel.cs
- WolvenKit.App/ViewModels/Importers/ImportViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.ContextMenu.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.UserInteractionStates.cs
- WolvenKit/Converters/TreeViewItemTemplateSelector.cs
- WolvenKit/Themes/App.Styles.xaml
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
- WolvenKit/Views/Shell/DockingAdapter.xaml.cs
- WolvenKit/Views/Templates/RedTypeView.xaml
- WolvenKit/Views/Tools/AssetBrowserView.xaml
- WolvenKit/Views/Tools/RedTreeView.xaml
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
- WolvenKit/Views/Tools/TweakBrowserView.xaml
> feature/searchbar for CR2W editor

- WolvenKit.App/Helpers/ArchiveXlHelper.cs
- WolvenKit/Views/Templates/RedRefEditor.xaml
- WolvenKit/Views/Templates/RedRefEditor.xaml.cs
> fixed validating editor for dynamic paths

- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.Descriptor.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.Value.cs
> displaying bone names in mesh file arrays

- README.md
**Preview:**
They don't provide an URL to embed based on dark/light theme.
> Update JetBrains logo

- WolvenKit.App/Factories/NodeWrapperFactory.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questPhaseNodeDefinitionWrapper.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/questSceneNodeDefinitionWrapper.cs
- Better error message for missing sub graph files. Fixes #1998
> fix(GraphView): Better error message for missing sub graph files

- WolvenKit.Modkit/RED4/Tasks/ArchiveTask.cs
- WolvenKit.Modkit/RED4/Tasks/UnbundleTask.cs
- WolvenKit.Modkit/RED4/Tasks/UncookTask.cs
fix: Don't analyze archives when loading via cli
> fix: Don't analyze archives when loading via cli

- WolvenKit.App/ViewModels/Documents/RedDocumentViewToolbarModel.cs
> fixing regenerate visual controllers

- WolvenKit.Common/WolvenKit.Common.csproj
- Added nuget infos for WolvenKit.Common
> Added nuget infos for WolvenKit.Common

- WolvenKit.Common/RED4/RedImage.cs
- Prevent threading issue with compressing/decompressing  images. Fixes #2014
> Prevent threading issue with compressing/decompressing  images

- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.Descriptor.cs
> CVM: removed duplicate description for ints

- WolvenKit.Modkit/RED4/Tools/AnimationTools.cs
- WolvenKit.Modkit/RED4/Tools/EntityTools.cs
- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
- WolvenKit.Modkit/RED4/Tools/MorphTargetTools.cs
- WolvenKit.Modkit/RED4/Uncook.cs
- WolvenKit/Views/Dialogs/ProjectWizardView.xaml.cs
**Fixed:**
- Exception in ProjectWizardView
- Mesh export filenames
> Post nuget update fixes

- WolvenKit.Common/RED4/CR2W/JSON/ParseableBuffers.cs
- WolvenKit.Common/RED4/CR2W/JSON/RedJsonSerializer.cs
- WolvenKit.Common/RED4/CR2W/JSON/Simples.cs
- WolvenKit.RED4/Archive/Buffer/RazerChromaAnimationBuffer.cs
- WolvenKit.RED4/Archive/Helper/BufferHelper.cs
- WolvenKit.RED4/Archive/Helper/RazerChromaHelper.cs
- WolvenKit.RED4/Archive/IO/CR2WWriter.File.cs
- WolvenKit.RED4/Archive/IO/RazerChromaAnimationBufferReader.cs
- WolvenKit.RED4/Archive/IO/RazerChromaAnimationBufferWriter.cs
- WolvenKit.RED4/Types/Classes/inkEditorModeState.cs
- WolvenKit.RED4/Types/Enums/cp77enums.cs
- WolvenKit.RED4/Types/EnumsExt/CustomEnums.cs
- Added reader/writer for Razer Chroma animations
**Fixed:**
- Reverted unwanted changes
Could add some kind of helper to CVM to work with this file.
Changing `Device` should also adjust the Frames array.
> Added reader/writer for Razer Chroma animations

- WolvenKit.App/Controllers/RED4Controller.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit/Views/Shell/RibbonView.xaml
**Fixed**
Installing a mod as REDmod will now create an info.json file
Tooltip will now tell user to hold shift for auto-deploy
closes #2026
> fixed redmod deployment and info.json

- WolvenKit.Modkit/RED4/Tools/Animation/Shared.cs
- WolvenKit.Modkit/RED4/Tools/AnimationTools.cs
- WolvenKit.Modkit/RED4/Tools/Common/GLTFHelper.cs
- WolvenKit.Modkit/RED4/Tools/EntityTools.cs
- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
- WolvenKit.Modkit/RED4/Tools/MorphTargetTools.cs
- WolvenKit.Modkit/RED4/Uncook.cs
**Fixed:**
- Filename handling for mesh files
- Some JSON problems introduced with SharpGLTF v1.0
Fixes #2035
> Mesh Export/Import issues

- WolvenKit.App/Constants.cs
- WolvenKit.App/ViewModels/Dialogs/SelectAnimationPathViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.sln.DotSettings
- WolvenKit/Views/Dialogs/Windows/SelectFacialAnimationPathDialog.xaml
- WolvenKit/Views/Dialogs/Windows/SelectFacialAnimationPathDialog.xaml.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
> npv: anim file conversion stuff to/from photomode

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.SearchAndReplace.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
> search and replace: progress bar, regex support

- WolvenKit.App/ViewModels/Dialogs/SearchAndReplaceDialogViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.SearchAndReplace.cs
- WolvenKit/Views/Dialogs/Windows/SearchAndReplaceDialogView.xaml
- WolvenKit/Views/Dialogs/Windows/SearchAndReplaceDialogView.xaml.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
> search&replace: added checkboxes

- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.SearchAndReplace.cs
> search&replace: fixed count in children

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.SearchAndReplace.cs
- WolvenKit/Views/Tools/RedColorPicker.xaml.cs
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
> search&replace: faster, duplication checks, persistent expansion states

- WolvenKit.App/ViewModels/Dialogs/SelectAnimationPathViewModel.cs
- WolvenKit.App/ViewModels/Dialogs/SelectPhotoModeAppViewModel.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewToolbarModel.cs
- WolvenKit/Views/Dialogs/Windows/SelectFacialAnimationPathDialog.xaml
- WolvenKit/Views/Dialogs/Windows/SelectPhotoModeAppDialog.xaml
- WolvenKit/Views/Dialogs/Windows/SelectPhotoModeAppDialog.xaml.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
> Convert to photo mode app

- WolvenKit.App/ViewModels/Documents/RDTDataViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.UserInteractionStates.cs
> fix performance hog in search with too many nodes

- WolvenKit/Views/Tools/RedTreeView.xaml.cs
> ctrl+w closes active editor

- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.SearchAndReplace.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.UserInteractionStates.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
> sarch&replace: more performance fixes

- WolvenKit/Views/Documents/RDTInkAtlasView.xaml
Likely a regression from UI PR.
> fix(RDTInkAtlasView): make editor readonly

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.ContextMenu.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
> fixed "paste selection"

- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
> fixed Home overlay after breaking it yesterday

- WolvenKit.App/Interaction/Interactions.cs
- WolvenKit.App/Models/ProjectManagement/Project/Cp77Project.cs
- WolvenKit.App/ViewModels/Dialogs/ShowBrokenReferences.cs
- WolvenKit/Views/Dialogs/Windows/ShowBrokenReferencesDialogView.xaml.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
- hiding "delete item" when "delete all but selection" is shown
- references in project dictionary will now be ordered by key
> Project and appfile actions

- WolvenKit.App/Models/ProjectManagement/Project/Cp77Project.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentTabViewModel.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewToolbarModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
To make the most of the search, you can now overwrite nodes in multiple parents
> Paste for multiselect

- WolvenKit.App/Interaction/Interactions.cs
- WolvenKit.App/ViewModels/Dialogs/ChangeComponentChunkMaskDialogViewModel.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentTabViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.ContextMenu.cs
- WolvenKit/Converters/RelayCommandToVisibilityConverter.cs
- WolvenKit/Views/Dialogs/Windows/ChangeComponentChunkMaskDialog.xaml
- WolvenKit/Views/Dialogs/Windows/ChangeComponentChunkMaskDialog.xaml.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
- WolvenKit/Views/Shell/MainView.xaml.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
Copy/paste should be triggered in the treeview component, rather than in the CVM itself
> Move copy paste into treeview

- WolvenKit.App/ViewModels/Dialogs/ChangeComponentChunkMaskDialogViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.ContextMenu.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
allow setting chunkmask to 0 again
> allow setting chunkmask to 0 again

- WolvenKit.App/ViewModels/Dialogs/SelectAnimationPathViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.ContextMenu.cs
- WolvenKit/Views/Dialogs/Windows/ChangeComponentChunkMaskDialog.xaml
photo mode app for masc also uses fem anims
> Fix photomode convert

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.SearchAndReplace.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
- made recursive CVM property loading more robust and pulled it out of the accessor functions into calling classes
> fixing animgraph crash

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.Common/RED4/CR2W/JSON/Arrays.cs
- WolvenKit.Common/RED4/CR2W/JSON/PrimitiveConverter.cs
- WolvenKit.Common/RED4/CR2W/JSON/Simples.cs
- WolvenKit.RED4/Types/IO/Red4Writer.cs
- WolvenKit.RED4/Types/Interfaces/IRedLegacySingleChannelCurve.cs
- WolvenKit.RED4/Types/Primitives/CLegacySingleChannelCurve.cs
- Add/Copy/Paste `CurvePoint`
**Fixed:**
- Errors while serializing some JSON data
> Better CurveSet handling

- WolvenKit/Views/Shell/MainView.xaml.cs
**Fixed:**
- Dispose EffectManager on close
Fixes #1569
> Dispose EffectManager on close

- WolvenKit.App/ViewModels/Documents/RDTDataViewModel.cs
- WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.ContextMenu.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
> fix copy/paste check across multiple tabs

- WolvenKit.App/Converters/ListToStringConverter.cs
> #2087 fix broken file ref dialogue not working

- WolvenKit.App/ViewModels/Exporters/ExportViewModel.cs
- WolvenKit.sln.DotSettings
- WolvenKit/Views/Exporters/ExportView.xaml
> export tool: disabling without files

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- Skip class selection for handles when only one type is allowed
Fixes #1978
> Skip class selection for handles when only one type is allowed

- WolvenKit/Views/Templates/BitfieldTemplateView.xaml
- WolvenKit/Views/Templates/BitfieldTemplateView.xaml.cs
**Fixed:**
- Fixed a bug in BitfieldEditor which prevented deselecting all values.
Fixes #1970
> BitfieldEditor fix

- WolvenKit.App/Scripting/AppScriptFunctions.cs
- WolvenKit.Common/RED4/CR2W/JSON/Simples.cs
**Fixed:**
- Fixed ambiguous wscript function definition
- Minor issue with JSON serialization
> Fixed ambiguous wscript function definition

- WolvenKit.App/Helpers/StringHelper.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.Descriptor.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.Value.cs
> #2062 #2002 descriptors and values for cvm

- WolvenKit.Modkit/RED4/Tasks/UncookTask.cs
**Fixed:**
- Removed invalid check, since outpath is always set at this point (see check before)
> fix(CLI): Removed invalid check

- WolvenKit.App/Interaction/Interactions.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit/Views/Shell/MainView.xaml.cs
> #2114 better long path warning

- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
- WolvenKit/Helpers/LogCodeHelper.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
> 2118 try-catch

- WolvenKit.App/ViewModels/GraphEditor/RedGraph.Scene.cs
- Added try catch block
- Added explicit error logging
**Fixed:**
- Scene crash
This is my first contribution. Any review and tips about project structure are appreciated.
> fix: crash scene view on the unexisting connection

- WolvenKit/Views/GraphEditor/GraphEditorView.xaml
- Enabled `IsSelectable` prop in Nodify
- Added `WolvenKitGreen` color for highlighting
**Fixed:**
- QoL fix
> feat: added selected state to connection

- WolvenKit.App/Helpers/DocumentTools.cs
- WolvenKit.App/Interaction/Interactions.cs
- WolvenKit.App/ViewModels/Dialogs/DeleteOrDuplicateComponentDialogViewModel.cs
- WolvenKit.App/ViewModels/Dialogs/SelectAnimationPathViewModel.cs
- WolvenKit/Views/Dialogs/Windows/DeleteOrDuplicateComponentDialog.xaml
- WolvenKit/Views/Dialogs/Windows/DeleteOrDuplicateComponentDialog.xaml.cs
- WolvenKit/Views/Dialogs/Windows/SelectFacialAnimationPathDialog.xaml
- WolvenKit/Views/Dialogs/Windows/SelectFacialAnimationPathDialog.xaml.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
- WolvenKit/Views/Shell/MainView.xaml.cs
- WolvenKit/Views/Templates/FilterableDropdownMenu.xaml
- WolvenKit/Views/Templates/FilterableDropdownMenu.xaml.cs
allows duplicating and deleting components in .app files by name
> dialogue: edit app components

- WolvenKit.App/Helpers/ProjectResourceTools.cs
- WolvenKit.Common/Tools/FileHelper.cs
- WolvenKit/Views/Dialogs/Windows/RenameDialog.xaml
- WolvenKit/Views/Dialogs/Windows/RenameDialog.xaml.cs
> Rename no capital letters

- WolvenKit.App/Helpers/StringHelper.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.Descriptor.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.Value.cs
- WolvenKit.sln.DotSettings
> CVM: descriptors and values for streamingsectors and -blocks

- WolvenKit.App/Helpers/ProjectResourceTools.cs
- WolvenKit.RED4/Types/RedBaseClass.Extra.cs
- will also replace in .csv and .json cr2w files
- will also replace in raw text files under resources
> update project references: replace in entire project

- WolvenKit.App/Helpers/ProjectResourceTools.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit.Common/Tools/FileHelper.cs
- WolvenKit/Views/Dialogs/Windows/RenameDialog.xaml
- WolvenKit/Views/Dialogs/Windows/RenameDialog.xaml.cs
I also disabled capitalization because we hates it, precious
> Rename: no capital letters

- WolvenKit.App/Services/ISettingsManager.cs
- WolvenKit.App/Services/SettingsDto.cs
- WolvenKit.App/Services/SettingsManager.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
> remember and reopen files between launches

- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
> remember open files

- WolvenKit.App/Models/ProjectManagement/Project/Cp77Project.cs
- WolvenKit.App/ViewModels/Documents/DocumentViewModel.cs
- WolvenKit.App/ViewModels/Documents/IDocumentViewModel.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
fixed exceptions, moved paths&properties to project
> remember open files: fixed exception

- WolvenKit.RED4/Types/ClassesExt/meshMeshMaterialBuffer.cs
**Fixed:**
- Changed invalid property assignment
Fixes #2158
> fix(RTTI): Changed invalid property assignment

- WolvenKit.App/WolvenKit.App.csproj
- WolvenKit.CLI/WolvenKit.CLI.csproj
- WolvenKit.Common/WolvenKit.Common.csproj
- WolvenKit.Core/WolvenKit.Core.csproj
- WolvenKit.Modkit/WolvenKit.Modkit.csproj
- WolvenKit.RED4/WolvenKit.RED4.csproj
- WolvenKit/Resources/TemplateFiles/inkatlas/single_item_template.inkatlas.json
- WolvenKit/WolvenKit.csproj
> Bump Nightly to 8.16.1

- WolvenKit.RED4/TweakDB/FlatsPool.cs
**Fixed:**
- Fixed flat lookup for records with != 2 name parts
Fixes #2184
> Fix TweakDB lookup

- WolvenKit.App/ViewModels/Exporters/AbstractImportExportViewModel.cs
- WolvenKit.App/ViewModels/Exporters/ExportViewModel.cs
- WolvenKit.App/ViewModels/Importers/ImportViewModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- import export tools refresh on project load
**Fixed:**
- fixed a bug where GetToolViewModel returned the wrong vm
closes #2144
> import export tools refresh on project load

- WolvenKit.Common/Model/WolvenkitFileModel.cs
- WolvenKit/Views/Dialogs/NewFileView.xaml
> [dev] #2202 new files: better filter

- WolvenKit.Common/Model/WolvenkitFileModel.cs
- WolvenKit/Views/Dialogs/NewFileView.xaml
> #2202 new files: better filter

- WolvenKit.App/Models/ProjectManagement/CP77Mod.cs
- WolvenKit.App/Models/ProjectManagement/Project/Cp77Project.cs
- WolvenKit.App/Services/ISettingsManager.cs
- WolvenKit.App/Services/ProjectManager.cs
- WolvenKit.App/Services/SettingsDto.cs
- WolvenKit.App/Services/SettingsManager.cs
- WolvenKit.App/ViewModels/Documents/DocumentViewModel.cs
- WolvenKit.App/ViewModels/Documents/IDocumentViewModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit.sln.DotSettings
Projects can remember the last X open files and reopen them on project launch
> feature: remember open files

- WolvenKit.App/Helpers/DocumentTools.cs
- WolvenKit/Views/Dialogs/Windows/SelectFacialAnimationPathDialog.xaml
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
After changing the facial animations via dialogue, the changed nodes will refresh in the editor
> #2128 change facial animation: refresh

- WolvenKit.App/Helpers/ProjectResourceTools.cs
- WolvenKit.App/Scripting/AppScriptFunctions.cs
- Allows iterating over all files under `resources` in wscript (will need this for .xl parsing)
- Allows deleting of files (this will permit cleanup of resources that were added by scripts)
> AppScriptFunctions: get resource files

- WolvenKit.Modkit/RED4/Tools/Common/MaterialExtractor.cs
> fix material order (hopefully)

- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.ExpansionStates.cs
- WolvenKit.sln.DotSettings
- WolvenKit/Views/Tools/RedTreeView.xaml
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
**Fixed:**
- CVM: selection/duplication behaviour
closes #2206
> fix: CVM selection/duplication behaviour

- WolvenKit.App/Helpers/ProjectResourceTools.cs
sort of important for ccxl additions :)
> rename/refactor: will now also work in inkcc files

- WolvenKit.RED4/Types/Primitives/Fundamentals/CBool.cs
- WolvenKit.RED4/Types/Primitives/Fundamentals/CDouble.cs
- WolvenKit.RED4/Types/Primitives/Fundamentals/CFloat.cs
- WolvenKit.RED4/Types/Primitives/Fundamentals/CInt16.cs
- WolvenKit.RED4/Types/Primitives/Fundamentals/CInt32.cs
- WolvenKit.RED4/Types/Primitives/Fundamentals/CInt64.cs
- WolvenKit.RED4/Types/Primitives/Fundamentals/CInt8.cs
- WolvenKit.RED4/Types/Primitives/Fundamentals/CUInt16.cs
- WolvenKit.RED4/Types/Primitives/Fundamentals/CUInt32.cs
- WolvenKit.RED4/Types/Primitives/Fundamentals/CUInt64.cs
- WolvenKit.RED4/Types/Primitives/Fundamentals/CUInt8.cs
- Implemented IComparable for Fundamentals
> Implemented IComparable for Fundamentals

- WolvenKit/Views/Tools/RedTreeView.xaml.cs
- Added null check
**Fixed:**
#2228
> fix: graph view crash

- WolvenKit/Views/Tools/RedTreeView.xaml.cs
> fix: exception in entity preview (null check)

- WolvenKit.App/ViewModels/GraphEditor/Nodes/Quest/Internal/DynamicQuestViewModel.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/Scene/Internal/DynamicSceneViewModel.cs
- WolvenKit.App/ViewModels/GraphEditor/RedGraph.Quest.cs
- WolvenKit.App/ViewModels/GraphEditor/RedGraph.Scene.cs
- WolvenKit.RED4/Types/DynamicBaseClass.cs
- Added basic support to view quest/scene graphes with custom/dynamic nodes
> Added basic support to view quest/scene graphes with custom/dynamic nodes

- WolvenKit/Views/Tools/RedTreeView.xaml.cs
Fixes the redtreeview selection beings stuck
closes #2247
closes #2240
closes #2235 
closes #2236
> fix treeview selections

- WolvenKit.RED4/Archive/IO/RedPackageWriter.File.cs
**Fixed:**
- Fixed an issue while trying to write unresolvable paths in RedPackages.
> Fixed an issue while trying to write unresolvable paths in RedPackages.

- WolvenKit.App/Controllers/IGameController.cs
- WolvenKit.App/Controllers/MockGameController.cs
- WolvenKit.App/Controllers/RED4Controller.cs
- WolvenKit.App/Models/ProjectManagement/Project/Cp77Project.cs
- WolvenKit.App/ViewModels/Dialogs/ProjectSettingsDialogViewModel.cs
- WolvenKit.App/ViewModels/Dialogs/ScriptManagerViewModel.cs
- WolvenKit.App/ViewModels/Documents/RDTDataViewModel.cs
- WolvenKit.App/ViewModels/Documents/RDTTextureViewModel.cs
- WolvenKit.App/ViewModels/Exporters/AbstractImportExportViewModel.cs
- WolvenKit.App/ViewModels/Exporters/ExportViewModel.cs
- WolvenKit.App/ViewModels/HomePage/Pages/ModsViewModel.cs
- WolvenKit.App/ViewModels/HomePage/Pages/WelcomePageViewModel.cs
- WolvenKit.App/ViewModels/Importers/ImportViewModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Shell/RibbonViewModel.cs
- WolvenKit.App/ViewModels/Tools/AssetBrowserViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.ContextMenu.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
- made some blocking tasks non-async
- rename some async methods to ..Async
> fix some fake async tasks

- WolvenKit.App/Models/ProjectManagement/Project/Cp77Project.cs
- WolvenKit.App/ViewModels/Dialogs/SelectAnimationPathViewModel.cs
> fix: wrong facial anim gender

- WolvenKit.App/Services/AppScriptService.Hook.cs
- WolvenKit.RED4/Archive/IO/ArchiveWriter.cs
**Fixed:**
- Fixed wrong error message when no onSave hook were executed
- Fixed unrelated bug... Don't look...
Fixes #2259
> Fixed wrong error message when no onSave hook were executed

- WolvenKit.App/Helpers/ProjectResourceTools.cs
- WolvenKit.Common/Tools/FileHelper.cs
**Fixed / Improved:**
- overwriting directories when user explicitly wants to
- overwriting directory has actual cancel option and user can choose between only adding new files or overwriting all in target dir
- fixed absolute path handling
- proper support for relative path navigation
- proper boundaries limiting changes to project directory
- unique temp names 
- proper input sanitation to avoid creating broken files or directories
- fixed files being unable to be moved to a not yet existing directory
- directories can now be moved into their own sub directory
- added method for file path sanitation 
- fixed incorrect error log level
> fixed issues and improved error handling when renaming files

- WolvenKit.App/ViewModels/Shell/AppViewModel.WScript.cs
- WolvenKit/Views/Shell/MenuBarView.xaml
- Just changed some names in the UI, to reflect the more commonly used name
> Change some UI names in entSpawner / object spawner import feature

- WolvenKit.App/ViewModels/HomePage/Pages/WelcomePageViewModel.cs
> welcome page: opening a project clears text filter boxes

- WolvenKit.App/WolvenKit.App.csproj
- WolvenKit.CLI/WolvenKit.CLI.csproj
- WolvenKit.Common/WolvenKit.Common.csproj
- WolvenKit.Core/WolvenKit.Core.csproj
- WolvenKit.Modkit/WolvenKit.Modkit.csproj
- WolvenKit.RED4/WolvenKit.RED4.csproj
- WolvenKit/Resources/TemplateFiles/inkatlas/single_item_template.inkatlas.json
- WolvenKit/WolvenKit.csproj
> Bump version

- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
> fixing exception and invalid file path

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.SearchAndReplace.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
**Fixed:**
- material depencendies replacement will no longer abort after 1st material
> add material dependencies: will no longer abort after first material

- WolvenKit.App/Helpers/ArchiveXlHelper.cs
- WolvenKit.Modkit/Resources/ArchiveXlHelper.cs
> rocket launcher arm substitution: check against right string

- WolvenKit.App/Helpers/DocumentTools.cs
- WolvenKit.App/ViewModels/Dialogs/SelectAnimationPathViewModel.cs
**Fixed:**
- #2261 fixed it for real this time
> fix facial anim for !female

- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.ExpansionStates.cs
> animAnimSetEntry node: shift-click expands "animation" node

- WolvenKit.App/Helpers/AppFileHelper.cs
- WolvenKit.App/Models/ProjectManagement/Project/Cp77Project.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewToolbarModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.Value.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
- WolvenKit/Views/Shell/MenuBarView.xaml
- WolvenKit/Views/Shell/MenuBarView.xaml.cs
Will also try to delete obsolete components while it's at it
> feature: project -> delete empty meshes

- WolvenKit.App/Controllers/RED4Controller.cs
**Fixed:**
- When packing as REDmod it gets all script files from /resources/scripts
- When packing as REDmod it gets all tweak files from /resources/tweaks
- Do not log anything if no custom sounds are in the project
closes #2129
> make redmod scripts and tweaks consistent in the project explorer

- WolvenKit.App/ViewModels/Shell/AppViewModel.WScript.cs
- WolvenKit.Modkit/Scripting/ScriptService.cs
Logger will not print script execution time if you run file validation on the entire project
> File validation on entire project: Made it less spammy

- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.SearchAndReplace.cs
> search&replace for TweakDBId

- .editorconfig
- WolvenKit.App/Factories/ChunkViewmodelFactory.cs
- WolvenKit.App/Models/SaveGame.cs
- WolvenKit.App/Services/AppArchiveManager.cs
- WolvenKit.App/Services/ModifierViewStateService.cs
- WolvenKit.App/ViewModels/Dialogs/FolderPathInputDialogViewModel.cs
- WolvenKit.App/ViewModels/Dialogs/InputDialogViewModel.cs
- WolvenKit.App/ViewModels/Dialogs/OpenFileViewModel.cs
- WolvenKit.App/ViewModels/GraphEditor/Nodes/NodeProperties.cs
- WolvenKit.Core/Exceptions/WolvenKitException.cs
- WolvenKit.Modkit/Exceptions/ExportException.cs
- WolvenKit.Modkit/Managers/ArchiveManager.cs
In trivial cases, I left them alone, but at least there won't be new ones anymore.
closes #2163
> #2163 remove primary constructors

- WolvenKit.App/ViewModels/Dialogs/NewFileViewModel.cs
> .xl default file name => projectname.archive.xl

- WolvenKit.App/Helpers/ArchiveXlHelper.cs
> fixed ArchiveXL substitution check for arms

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
Will now correctly gather material names for dynamic materials
> fixed dynamic material name used/unused detection

- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.Common/Tools/FileHelper.cs
> #2295: fixed locate project prank

- README.md
- WolvenKit.App/ViewModels/HomePage/Pages/WelcomePageViewModel.cs
- WolvenKit.App/ViewModels/Shell/MenuBarViewModel.cs
- docs/DEVELOPER GUIDE.md
**Fixed:**
- Update Discord link in homepage
> fix: update Discord link in homepage

- README.md
- WolvenKit.App/ViewModels/HomePage/Pages/WelcomePageViewModel.cs
- WolvenKit.App/ViewModels/Shell/MenuBarViewModel.cs
- docs/DEVELOPER GUIDE.md
Reverts WolvenKit/WolvenKit#2345
> Revert "fix: update Discord link in homepage"

- WolvenKit.Modkit/RED4/Tools/MeshImportTools.cs
- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
- WolvenKit.Modkit/RED4/Tools/MorphTargetImportTools.cs
- WolvenKit.Modkit/RED4/Uncook.cs
Exception will print a warning for export jobs
> WKit will now export withRig at bone mismatch

- WolvenKit.App/Helpers/TemplateFileTools.cs
... by capitalizing the tweak name
> make photo mode NPVs show up on top of the list

- WolvenKit/Views/Tools/RedTreeView.xaml.cs
> after tab change: refresh modifier status in treeview

- WolvenKit/Layout/DockStateExtensions.cs
> fixed vanishing windows, so far no endless loop

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
> fix "regenerate visual controllers"

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
> hopefully fixed 'paste handle'

- WolvenKit.App/Helpers/StringHelper.cs
- WolvenKit.App/ViewModels/Documents/RDTDataViewModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.ExpansionStates.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.Value.cs
- WolvenKit/Views/Tools/RedTreeView.xaml.cs
- Improved selection behaviour for duplicating single items
- Added descriptor for `gameEntitySpawnerComponent` in CVM
> Cvm selection and descriptor

- WolvenKit.App/Models/FileSystemModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.WScript.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit/Views/Tools/ProjectExplorerView.xaml
only active if corresponding file exists
...will also be available from project browser now. 
If file does not exist: will create file
If file does exist: will ask if the file should be overwritten
> Add contextual json convert to project browser

- WolvenKit.App/Helpers/InkatlasImageGenerator.cs
- WolvenKit.App/Interaction/Interactions.cs
- WolvenKit.App/ViewModels/Dialogs/AddInkatlasDialogViewModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.ComplexFiles.cs
- WolvenKit/Views/Dialogs/Windows/AddInkatklasDialog.xaml
- WolvenKit/Views/Dialogs/Windows/AddInkatklasDialog.xaml.cs
- WolvenKit/Views/Shell/MainView.xaml.cs
- WolvenKit/Views/Shell/MenuBarView.xaml
- WolvenKit/Views/Shell/MenuBarView.xaml.cs
File -> Add... now has an inkatlas dialog, with custom popup and everything
> generate inkatlas. it just works.

- WolvenKit.App/Models/ProjectManagement/CP77Mod.cs
- WolvenKit.App/Services/ProjectManager.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
> fix open project exception

- WolvenKit.App/ViewModels/Tools/EditorDifficultyLevel/EditorDifficultyLevelFieldFactory.cs
> hide partsOverrides conditionally

- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.Descriptor.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.Value.cs
added inline descriptors to partsOverrides in tree view
> partsOverrides: inline descriptors

- WolvenKit.App/Helpers/InkatlasImageGenerator.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
> un-dynamify materials: preserve reference type

- WolvenKit.RED4/Archive/IO/ArchiveWriter.cs
Fixed packing file `base\sound\event\soundbanks.json`
> fixed packing soundbanks.json

- WolvenKit.App/ViewModels/Documents/RDTMeshViewModel.cs
- WolvenKit/Views/Documents/RDTMeshView.xaml
- WolvenKit/Views/Documents/RDTMeshView.xaml.cs
prevent throwing exception for duplicate components
> prevent throwing exception for duplicate components

- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
> #2382 fix command refresh

- WolvenKit.App/Helpers/FilePathHelper.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- on startup (assembly location)
- on project change
Will show an annoying popup, which you can not currently disable.
closes #2380
> #2380 check for OneDrive location

- WolvenKit.App/Helpers/CvmDropdownHelper.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.ExpansionStates.cs
- WolvenKit.RED4/Types/Helper/RedTypeHelper.cs
- WolvenKit/Converters/IRedTypeToCNameConverter.cs
- WolvenKit/Converters/RedEditorTemplateSelector.cs
- WolvenKit/Views/GraphEditor/GraphEditorView.xaml.cs
- WolvenKit/Views/Templates/FilterableDropdownCNameMenu.xaml
- WolvenKit/Views/Templates/FilterableDropdownCNameMenu.xaml.cs
- WolvenKit/Views/Templates/RedCNameEditor.xaml.cs
- WolvenKit/Views/Templates/RedTypeView.xaml
Some fields are CNames, but there's a non-technical limitation of what could/should go there.
> CName dropdown

- WolvenKit.App/Helpers/ProjectResourceTools.cs
- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
It will also no longer work on a per-folder base (false positives), but rather only replace files that actually exist in the project.
closes #2369
> refactor&rename will now replace in cnames (CPUNameU64)

- WolvenKit.App/Helpers/CvmDropdownHelper.cs
**Fixed:**
- Updated CvmDropdownHelper - changed list of paths to static field
> Changed list of paths to static field in CvmDropdownHelper

- WolvenKit.RED4/Types/Primitives/Simples/CName.cs
> fix empty cname hash according to psi

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.Modkit/RED4/RedTypeFactory.cs
- WolvenKit.RED4/Types/Classes/questAddRemoveContact_NodeType.cs
now uses a factory to initialize a bunch of fields in cvm nodes
> Initialize fields in cvm

- WolvenKit.Modkit/RED4/Tools/MeshImportTools.cs
**Fixed:**
- Implemented logic as in #2410
> Refactor GS import code

- WolvenKit.App/Helpers/CvmDropdownHelper.cs
- WolvenKit/Views/Templates/FilterableDropdownResourcePathMenu.xaml.cs
- added dropdown for `phaseResource` and `sceneFile`
- excluded quest and scene resources from autopopulate if there is only one in project
> added dropdown for `phaseResource` and `sceneFile`

- WolvenKit.App/Services/WatcherService.cs
file watcher will no longer try (and fail) to update on .blend@ files
> ignoring temp files in file watcher

- WolvenKit.App/ViewModels/Importers/ImportViewModel.cs
Prevents the following error from softbricking the ImportTool:
```
[Error    ] Message: extension is not ERawFileFormat (Parameter 'fileName')
Source: WolvenKit.App
StackTrace:    at WolvenKit.App.ViewModels.Tools.ImportableItemViewModel.DecideImportOptions(String fileName, IArchiveManager archiveManager, IProjectManager projectManager, Red4ParserService parserService)
at WolvenKit.App.ViewModels.Tools.ImportableItemViewModel..ctor(String fileName, IArchiveManager archiveManager, IProjectManager projectManager, Red4ParserService parserService)
at WolvenKit.App.ViewModels.Importers.ImportViewModel.<>c__DisplayClass13_0.<LoadFilesAsync>b__2()
at System.Threading.Tasks.Task`1.InnerInvoke()
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, …
```
> prevent file import exception

- WolvenKit.Core/Extensions/StringExtensions.cs
in StringExtension's FirstCharToXXX
> stopped throwing exception for empty string

- WolvenKit.App/ViewModels/Tools/ExportableItemViewModel.cs
- WolvenKit.Modkit/RED4/Tools/MeshImportTools.cs
Tested by oranje3 - this allows round trips for files like `v_utility4_thorton_mackinaw_monster__ext01_chassis_01.mesh`, which have a LOD_0 instead of LOD_8. It also has to be named like that on import, because otherwise the deforms will stop working.
closes #2403
> fixing vehicle lod situation with loomy and oranje

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
**Fixed:**
- material expansion (empty chunkmask arrays) will no longer break "fix submesh count"
> fixed an exception for adjust submesh count

- WolvenKit.App/Helpers/CvmDropdownHelper.cs
restored functionality of fileEntryIndex in gameJournalPath
> fixed dropdown assigment for gameJournalPath

- WolvenKit.App/Interaction/Interactions.cs
- WolvenKit.App/ViewModels/Dialogs/SelectDropdownEntryDialogViewModel.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewToolbarModel.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit/Views/Dialogs/Windows/SelectDropdownEntryWindow.xaml
- WolvenKit/Views/Dialogs/Windows/SelectDropdownEntryWindow.xaml.cs
- WolvenKit/Views/Tools/ProjectExplorerView.xaml.cs
When running "Delete unused materials" on an NPV eye mesh
> replace eyelash material name

- WolvenKit.App/ViewModels/Tools/ProjectExplorerViewModel.cs
- WolvenKit/Views/Tools/ProjectExplorerView.xaml
Added shortcut for context menu item
> added f7 shortcut to create new folder

- WolvenKit.App/Helpers/TemplateFileTools.cs
- WolvenKit.App/Interaction/Interactions.cs
- WolvenKit.App/ViewModels/Dialogs/AddQuestDialogViewModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.ComplexFiles.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit/Views/Shell/MenuBarView.xaml
- WolvenKit/Views/Shell/MenuBarView.xaml.cs
feat: automate generation of questphase, journal, and localization files for a new quest mod
- Automate creation of minimal quest, journal, onscreens localization, and ArchiveXL files.
- Added YAML structure to .archive.xl in the project resources folder.
- Fix node connection logic, socket order, and property assignments for questphase graph generation.
- Refactor quest generation logic into helper methods.
- Added UI button under File -> Add files...
> Starter quest generator

- WolvenKit.sln.DotSettings
- WolvenKit/Views/Templates/IconBox.xaml.cs
- WolvenKit/Views/Tools/LogView.xaml
- Added comments with icon gallery urls in .xaml.xl file 
- Updated spellcheck dictionary with a few things that are not typos
> fixed missing 'copy to clipboard' icon in logview

- WolvenKit.RED4/Types/RedBaseClass.Extra.cs
added handle case to top level check
> fix xpath resolution for handles

- WolvenKit.RED4/Types/Classes/worldPrefabNode.cs
- WolvenKit.RED4/Types/ClassesExt/Properties/characterCreationNavigationBtn.cs
- WolvenKit.RED4/Types/ClassesExt/Properties/inkWidget/inkButtonController.cs
> fix "hides inherited member" warnings

- WolvenKit.App/Services/AppArchiveManager.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewToolbarModel.cs
- WolvenKit.Core/Interfaces/IGameFile.cs
- WolvenKit.sln.DotSettings
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
**Fixed:**
- shift status will now be passed at event time rather than in the model
> fixed an exception when adding base game file dependencies

- WolvenKit.App/Helpers/CvmDropdownHelper.cs
- WolvenKit.App/Helpers/DocumentTools.cs
- WolvenKit.App/ViewModels/GraphEditor/RedGraph.Scene.cs
- WolvenKit.RED4/Types/ClassesExt/scnSceneResource.cs
- WolvenKit.RED4/Types/RedBaseClass.Extra.cs
- WolvenKit/Converters/RedEditorTemplateSelector.cs
- WolvenKit/Views/Documents/QuestPhaseGraphView.xaml.cs
- WolvenKit/Views/Templates/FilterableDropdownRedstringMenu.xaml
- WolvenKit/Views/Templates/FilterableDropdownRedstringMenu.xaml.cs
- WolvenKit/Views/Templates/RedStringEditor.xaml
- WolvenKit/Views/Templates/RedStringEditor.xaml.cs
- WolvenKit/Views/Templates/RedTypeView.xaml
- Dropdown editor for CStrings (needs further implementation by Bill)
> added redstringDropdownEditor

- WolvenKit.App/Helpers/DiscordHelper.cs
- WolvenKit.App/Services/ISettingsManager.cs
- WolvenKit.App/Services/SettingsDto.cs
- WolvenKit.App/Services/SettingsManager.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.sln.DotSettings
- WolvenKit/Views/Shell/DockingAdapter.xaml.cs
Discord RPC can now display the current project, and can be turned off in WKit settings
> Discord rpc update

- WolvenKit.App/ViewModels/GraphEditor/RedGraph.Scene.cs
- WolvenKit.RED4/Types/ClassesExt/scnSceneResource.cs
> Fixing error that prevents scene file creation

- WolvenKit.App/Helpers/TemplateFileTools.cs
added missing thread title LocKey in generated journal
> fixed missing thread title for Quest Template in TemplateFileTools.cs

- WolvenKit.App/ViewModels/Documents/RedDocumentViewToolbarModel.cs
- WolvenKit.sln.DotSettings
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
Second commit is codestyle&ocd, maybe review separately :)
> Added menu bar entry: regenerate all cruids

- WolvenKit.App/ViewModels/Dialogs/AddInkatlasDialogViewModel.cs
- WolvenKit/Views/Dialogs/Windows/AddInkatlasDialog.xaml.cs
> AddInkatlasDialog: remember values per default

- WolvenKit.App/Scripting/AppScriptFunctions.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.WScript.cs
- WolvenKit.Modkit/Scripting/ScriptFunctions.cs
File validation will now verify file paths in xl files. Since it can also parse yaml files, perhaps I'll implement that as well!
> supporting changes for file validation (xl and yaml)

- WolvenKit.RED4/Archive/IO/RedPackageReader.cs
**Fixed:**
- Fixed an issue where DataBuffers / SerializationDeferredDataBuffers weren't read
> Fixed an issue where DataBuffers / SerializationDeferredDataBuffers weren't read

- WolvenKit.App/Controllers/RED4Controller.cs
- WolvenKit.App/Helpers/CvmDropdownHelper.cs
- WolvenKit.App/Helpers/DocumentTools.cs
Better exception handling for IO exception when game is running in background
> Dropdownmenu values for cvm value

- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
> fixed 'copy materials' paths starting with 'archive'

- WolvenKit.App/Helpers/DocumentTools.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml
> mesh: move ArchiveXL menu entries to own header

- WolvenKit.App/Models/ProjectManagement/Project/Cp77Project.cs
> show error if file references itself

- WolvenKit.App/Helpers/CvmDropdownHelper.cs
> fix: fileEntryIndex properly editable again

- WolvenKit/Views/GraphEditor/GraphEditorView.xaml.cs
Fixed resetting of graph editor when saved state was present.
> quest graph editor - loading state fix

- Directory.Packages.props
- WolvenKit/App.xaml
- WolvenKit/Initializations.cs
- WolvenKit/Resources/Styles/ExpressionDark.xaml
- bump Syncfusion to 30.2.4 (was 28.2.5), target Service Pack release for stability
- update license
**Fixed:**
- globally use white color explicitly, due to a regression introduced with Syncfusion upgrade
**Style:**
- lint ExpressionDark.xaml
Testing should be done across all views, to be sure Syncfusion upgrade didn't introduce regression(s) I may have missed.
> build: bump Syncfusion

- WolvenKit.App/Helpers/CvmDropdownHelper.cs
- WolvenKit/Views/Templates/FilterableDropdown/FilterableDropdownMenuBase.cs
> CVM dropdown: refresh for meshcomponent properties

- WolvenKit.App/Interaction/Interactions.cs
- WolvenKit.App/ViewModels/Dialogs/ShowChecklistDialogueViewModel.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewToolbarModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.ComplexFiles.cs
- WolvenKit/Views/Dialogs/Windows/ShowChecklistDialog.xaml
- WolvenKit/Views/Dialogs/Windows/ShowChecklistDialog.xaml.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml
- WolvenKit/Views/Shell/MainView.xaml.cs
- WolvenKit/Views/Templates/FilterableChecklistMenu.xaml.cs
- Added a "delete chunk materials by index" to mesh file's "cleanup" menu
- made CheckboxDialog more generic
> Delete chunk materials by index

- WolvenKit.App/ViewModels/Tools/LocKeyBrowserViewModel.cs
- Allow searching of secondary key
- Add `key:` and `value:` search filters
> LockeyBrowser: Search improvements

- WolvenKit.App/ViewModels/Dialogs/CreatePhotoModeAppViewModel.cs
> better default values for NPV creation dialogue

- WolvenKit/Views/Tools/RedTreeView.xaml.cs
> refresh context menu flags when menu opens

- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
> "add dependencies" works for mi and mlsetup again

- WolvenKit.App/ViewModels/Dialogs/CreatePhotoModeAppViewModel.cs
> photomode files: better default dir

- WolvenKit.Common/RED4/CommonFunctions.cs
> consider "normal" and "_rm" for texgroup import

- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit/Themes/App.Sizes.xaml
- WolvenKit/Themes/App.Styles.xaml
- WolvenKit/Views/Dialogs/Windows/AddInkatlasDialog.xaml
- WolvenKit/Views/Templates/FilterableDropdown/FilterableDropdownMenu.xaml
- WolvenKit/Views/Templates/FilterableDropdown/FilterableDropdownMenu.xaml.cs
- docs/CONTRIBUTING.md
> fix display property crash when opening inkatlas dialogue

- WolvenKit.App/Services/WatcherService.cs
> filewatcher: no error msg for temp files

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
> fix out of bound exception in CVM

- WolvenKit.App/Helpers/DocumentTools.cs
- WolvenKit.App/Helpers/StringHelper.cs
- WolvenKit.App/ViewModels/Documents/RedDocumentViewToolbarModel.cs
- WolvenKit.Core/WikiLinks.cs
- WolvenKit/Resources/Styles/ExpressionDark.xaml
- WolvenKit/Themes/App.Styles.xaml
- WolvenKit/Views/Dialogs/Windows/ShowChecklistDialog.xaml.cs
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml
- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
- WolvenKit/Views/GraphEditor/GraphEditorView.xaml
- WolvenKit/Views/Shell/DockingAdapter.xaml
- WolvenKit/Views/Templates/FilterableChecklistMenu.xaml
- WolvenKit/Views/Templates/FilterableChecklistMenu.xaml.cs
- WolvenKit/Views/Tools/ProjectExplorerView.xaml
> feature: copy appearances to mesh(es)

- WolvenKit/Views/Documents/RedDocumentViewMenuBar.xaml.cs
> Better user feedback for Add Dependencies (again)

- WolvenKit/Views/Dialogs/Windows/ChangeComponentPropertiesDialog.xaml.cs
- WolvenKit/Views/Dialogs/Windows/DeleteOrDuplicateComponentDialog.xaml
- WolvenKit/Views/Dialogs/Windows/DeleteOrDuplicateComponentDialog.xaml.cs
> made two dialogues close on escape

- WolvenKit.RED4/Archive/IO/CR2WReader.cs
- WolvenKit.RED4/Archive/IO/RedPackageReader.cs
Reverts WolvenKit/WolvenKit#2583
> Revert "cr2reader: ignore warning for known suspects"

- WolvenKit.App/WolvenKit.App.csproj
- WolvenKit.CLI/WolvenKit.CLI.csproj
- WolvenKit.Common/WolvenKit.Common.csproj
- WolvenKit.Core/WolvenKit.Core.csproj
- WolvenKit.Modkit/WolvenKit.Modkit.csproj
- WolvenKit.RED4/WolvenKit.RED4.csproj
- WolvenKit.Unpacker/WolvenKit.Unpacker.csproj
- WolvenKit/Resources/TemplateFiles/inkatlas/single_item_template.inkatlas.json
- WolvenKit/WolvenKit.csproj
> version bump

- WolvenKit/Views/GraphEditor/GraphEditorView.xaml.cs
Added `hide/unhide sockets` option to right click menu in quest and scenes graphs
> feat: added hide/unhide sockets for all nodes in graph view

- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
> CVM: refresh component's IsDefault if chunkMask changes

- WolvenKit.Common/Model/Arguments/ExportArgs.cs
* InkatlasExportArgs: `.png (folder)`
* CommonExportArgs: `` (empty string)
> export-args: tostring

- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.Value.cs
> CVM: appearancePartComponentOverrides show appearanceName

- WolvenKit.App/Helpers/ProjectResourceTools.cs
- WolvenKit.sln.DotSettings
> Added .inkcharactercustomization to search&replace in resources

- WolvenKit.App/ViewModels/Dialogs/ProjectWizardViewModel.cs
- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.Core/Extensions/StringPathExtensions.cs
Might be too intrusive or not intrusive enough?
closes #1962
> Check project path for special characters (#1962)

- .github/workflows/bump-version.yml
created gha to bump version
- gha that bumps the version and makes a pr for it 
closes #2606 
unsure if `WolvenKit.Package\Package.appxmanifest` should also be bumped so left it out for now
> created gha to bump version

- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- added release build check to avoid auto updating on startup for debug builds
closes #2616
> added debug check to auto update

- WolvenKit.App/Helpers/DocumentTools.cs
meshes without appearances can have materials (@context)
> copy materials to other mesh: better check

- All.sln
- Tests/WolvenKit.FunctionalTests/GameUnitTest.cs
- Tests/WolvenKit.Utility/GameUnitTest.cs
**Fixed:**
- Invalid solution settings in `All.sln`
- UnitTest setup issues
> Some small fixes

- WolvenKit.App/ViewModels/Documents/RDTDataViewModel.cs
- WolvenKit/Views/Tools/RedTreeView.xaml
> #2360 show 'copy as handle' for all handles in CVM

- WolvenKit/Views/Shell/MenuBarView.xaml
> fix remaining static links

- WolvenKit.App/ViewModels/Shell/AppViewModel.cs
- WolvenKit.App/ViewModels/Shell/MenuBarViewModel.cs
- WolvenKit.Core/WikiLinks.cs
- WolvenKit/Views/Shell/MenuBarView.xaml
- WolvenKit/Views/Shell/MenuBarView.xaml.cs
Turns out view bindings really hate constants... and that breaks everything. The joy.
> Fix: "view" menu entries

- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.Value.cs
> cvm: added values for phone journal entries

- WolvenKit.App/Services/NodePropertiesSelectionService.cs
- WolvenKit.App/ViewModels/Shell/ChunkViewModel.cs
- WolvenKit.App/ViewModels/Tools/ChunkViewModelExtended/ChunkViewModel.ExpansionStates.cs
- WolvenKit/Converters/RedTypeToChunkViewModelCollectionConverter.cs
> Quest editor: auto select path node

- WolvenKit.App/ViewModels/Tools/ImportableItemViewModel.cs
> importargs: disable garment support param by default for wepaons etc

- WolvenKit.Modkit/RED4/Tools/MeshTools.cs
throw exception if bones are imported into a mesh that doesn't have any
fixes #2680
> throw if bones are imported into a mesh without

- WolvenKit.App/Helpers/ProjectResourceTools.cs
- WolvenKit.App/Helpers/YamlHelper.cs
- WolvenKit.App/Interaction/Interactions.cs
- WolvenKit.App/ViewModels/Dialogs/AddItemsToStoreDialogViewModel.cs
- WolvenKit.App/ViewModels/Shell/MenuBarViewModel.cs
- WolvenKit/Views/Dialogs/Windows/AddItemsToStoreDialog.xaml
- WolvenKit/Views/Dialogs/Windows/AddItemsToStoreDialog.xaml.cs
- WolvenKit/Views/Shell/MainView.xaml.cs
- WolvenKit/Views/Shell/MenuBarView.xaml
- WolvenKit/Views/Shell/MenuBarView.xaml.cs
[source.zip](https://github.com/user-attachments/files/22656070/source.zip)
> Feature: add items to atelier store / ccxl vendor
